### PR TITLE
Tic_Tac_Toe_game

### PR DESCRIPTION
**Pull request by prakhar07msd**
Related Issue
This game almost everyone have played in their childhood. To make it a bit easy, I have created this game.

 LGM-SOC'21 Participant

Closes: #72

Describe the changes you've made
Give a clear description what modifications you have made

Type of change
What sort of change have you made:

 Bug fix (non-breaking change which fixes an issue)
 - [x] New feature (non-breaking change which adds functionality)
 Code style update (formatting, local variables)
 Breaking change (fix or feature that would cause existing functionality to not work as expected)
 This change requires a documentation update
How Has This Been Tested?
Describe how have you verified the changes made

Checklist:
 My code follows the guidelines of this project.
 I have performed a self-review of my own code.
 I have commented my code, particularly wherever it was hard to understand.
 I have made corresponding changes to the documentation.
 My changes generate no new warnings.
 I have added tests that prove my fix is effective or that my feature works.
 Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Follow the project structure
Changes to be done:

- Images and screenshots should be in "Images" folder
- The README.txt should be renamed to "README.md" file
- The project folder should be titled as " Tic Tac Toe Game"
- The file name should be titled as "tic_tac_toe.py".
- Add the imported libraries of project in "requirements.txt" file
- Add appropriate comments in your project file wherever needed to get good understanding of the project.
- README.md file of the project should be elaborative. You can check with the README template available in main repo for reference.

Kindly do the needful changes. @prakhar07msd

**Comment by prakhar07msd** [comment]
> Follow the project structure
> Changes to be done:
> 
> * Images and screenshots should be in "Images" folder
> * The README.txt should be renamed to "README.md" file
> * The project folder should be titled as " Tic Tac Toe Game"
> * The file name should be titled as "tic_tac_toe.py".
> * Add the imported libraries of project in "requirements.txt" file
> * Add appropriate comments in your project file wherever needed to get good understanding of the project.
> * README.md file of the project should be elaborative. You can check with the README template available in main repo for reference.
> 
> Kindly do the needful changes. @prakhar07msd

Please check my PR

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
The project folder should be named as "TicTacToe Game" @prakhar07msd

**Comment by prakhar07msd** [comment]
> The project folder should be named as "TicTacToe Game"
> Add the imported libraries of project in "requirements.txt" file
> 
> @prakhar07msd

Please check my PR.

**Review by prathimacode-hub — COMMENTED** [review]
The project file should be titled as "tictactoe_game.py". Kindly do this change. @prakhar07msd

**Comment by prakhar07msd** [comment]
> The project file should be titled as "tictactoe_game.py". Kindly do this change. @prakhar07msd

Now please check my PR.

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved. Yayy. Congrats. Good work. Your dedication is wow. 🎉👏 @prakhar07msd

**Comment by prakhar07msd** [comment]
> Your PR is approved. Yayy. Congrats. Good work. Your dedication is wow. 🎉👏 @prakhar07msd

Merge my PR

**Pull request merged**
