### PR TITLE
Added checklist app

### PR DESCRIPTION
**Pull request by siddhi-244**
Related Issue 

- Added checklist app in python

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #320 

### Describe the changes you've made

Give a clear description what modifications you have made

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by siddhi-244** [comment]
Plzz add the level label as well @Debashish-hub

**Comment by Debashish-hub** [comment]
> Plzz add the level label as well @Debashish-hub

Don't worry, @siddhi-244  It will be done Once it is approved

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
The file name of the project should be as "checklist_app.py"
Elaborate your README.md. There is template as well provided in README file of the project. @siddhi-244

**Comment by siddhi-244** [comment]
Done @prathimacode-hub

**Comment by siddhi-244** [comment]
@prathimacode-hub done

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changesto be done:

- Add aim, purpose and compilation steps of the project to the README.md file
- The readme file should be titled as "README.md"

Kindly do the needful changes. @siddhi-244

**Comment by siddhi-244** [comment]
I have already added steps for running project

**Comment by siddhi-244** [comment]
Done @prathimacode-hub  plzz check it !

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved. Good script choosen. Wonderful work. Keep rising up. Welcome to the repository. ✨🏷👍@siddhi-244

**Comment by siddhi-244** [comment]
Thank you @prathimacode-hub

**Pull request merged**
