### PR TITLE
Armstrong_number 

### PR DESCRIPTION
**Pull request by Priyanshi-Rai**
<html>
<h1>RELATED ISSUE</h1>

To check whether the number is an Armstrong number or not

- [x] LGMSOC'21 Participant

- [ ] Contributor

Closes :  #311

<h2><i>Type of change</i></h2>
What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x]  New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update  

<h2><i>How Has This Been Tested?</i></h2>

 I have tested the code using Jupyter notebook as well as online compiler (repelit)

<h2>Checklist:</h2>
 
- [x] My code follows the guidelines of this project.
- [x]  I have performed a self-review of my own code.
- [x]  I have commented my code, particularly wherever it was hard to understand.
- [ ]  I have made corresponding changes to the documentation.
- [ ]  My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ]  Any dependent changes have been merged and published in downstream modules

<h2>Output</h2>

output1

output2

</html>

### CODE REVIEW

**Comment by Debashish-hub** [comment]
Never close the PR from your side and do follow PR template @Priyanshi-Rai

**Comment by Priyanshi-Rai** [comment]
Ok sir I will make the mandotary changes

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:

All the images and screenshots should be in "Images" folder
The project should be titled as "Armstrong Number"
The requirements file should be titled as "requirements.txt"
The file name should be titled as "armstrong_number.py"

Kindly do the needful changes. Good to see you create a PR. @Priyanshi-Rai

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done :

Add the proper PR template to your PR commit message
The project folder should be titled as "Armstrong Number"
The requirements should be in "requirements.txt" file
Add workflow, compilation steps and your name at the end of the file in "README.md".
The screenshot you added is in user-images content. It should be the file path of the image that's present in "Images" folder.

Kindly do the needful changes. @Priyanshi-Rai

**Comment by Priyanshi-Rai** [comment]
I've made the changes , please look into it

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Few changes still remaining.

Changes to be done:

- Add workflow steps in your "README.md" file
- The output screenshot links you had added up in "README.md" file are of "user-images" content. Kindly replace it with the file path of the image present in this repo.
- The requirements file should be titled as "requirements.txt"
- The project file should be titled as "armstrong_number.py"

Kindly do the needful changes. @Priyanshi-Rai

**Comment by Priyanshi-Rai** [comment]
> Few changes still remaining.
> 
> Changes to be done:
> 
> * Add workflow steps in your "README.md" file
> * The output screenshot links you had added up in "README.md" file are of "user-images" content. Kindly replace it with the file path of the image present in this repo.
> * The requirements file should be titled as "requirements.txt"
> * The project file should be titled as "armstrong_number.py"
> 
> Kindly do the needful changes. @Priyanshi-Rai

okay Ma'am

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
You did it. One change needed. Sorry, I didn't notice it earlier. 
The project folder should be titled as "Armstrong Number".
Others are in right frame and project structure. First save this files and upload it fairly by following this using New titled folder. Once you do and add the needful files. You can delete up the old folder from the forked repository.

That's it. And you will be done.   @Priyanshi-Rai

**Comment by Priyanshi-Rai** [comment]
> You did it. One change needed. Sorry, I didn't notice it earlier.
> The project folder should be titled as "Armstrong Number".
> Others are in right frame and project structure. First save this files and upload it fairly by following this using New titled folder. Once you do and add the needful files. You can delete up the old folder from the forked repository.
> 
> That's it. And you will be done. @Priyanshi-Rai

okay Ma'am i hope this is the final change :p

**Review by Debashish-hub — APPROVED** [review]
Congrats! @Priyanshi-Rai  Your PR is approved

**Comment by prathimacode-hub** [comment]
Amazing start. Proud of you. Good to see your learning progress. Very well done. Keep it up. Your first PR is approved. Welcome to the repo officially. ✨🎉👍@Priyanshi-Rai

**Review by prathimacode-hub — APPROVED** [review]
Amazing start. Proud of you. Good to see your learning progress. Very well done. Keep it up. Your first PR is approved. Welcome to the repo officially. ✨🎉👍@Priyanshi-Rai

**Pull request merged**
