### PR TITLE
Grade calculator

### PR DESCRIPTION
**Pull request by Ashu-1309**
## Related Issue 
-Grade Calculator

- [x] LGM-SOC'21 Participant 
- [x] Contributor

Closes: #471

### Describe the changes you've made
This code will be used to find the grade of a student.

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested?

I tested the code in Online python compiler as well as in offline compiler.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly where ever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Ashu-1309** [comment]
I have done all the required changes can you check it. @prathimacode-hub

**Comment by Ashu-1309** [comment]
Also I have added the README and along with image link in it .

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Kindly remove the files that doesn't belong to grade calculator. I could see few files which are of ur earlier PR's. @Ashu-1309

**Comment by Ashu-1309** [comment]
They came by default . It didn't do anything. But I remove all those which has option of deleting . But was unable to delete some pics . @prathimacode-hub

**Comment by Debashish-hub** [comment]
> They came by default . It didn't do anything. But I remove all those which has option of deleting . But was unable to delete some pics . @prathimacode-hub

You have another folder 'Days Finder In a Month' which does not belong to this PR. Delete that folder directly

**Comment by Ashu-1309** [comment]
Done .

**Review by prathimacode-hub — APPROVED** [review]
Whoa, PR approved. Good to see your progress. Good going👌🙌 @Ashu-1309

**Review by prathimacode-hub — COMMENTED** [review]
Now, you're on right track of perfection. Impressive. 👌🙌@Ashu-1309

**Comment by Ashu-1309** [comment]
Can j delete this branch ????

**Comment by Debashish-hub** [comment]
> Can j delete this branch ????

Why?

**Comment by prathimacode-hub** [comment]
You shouldn't delete anything from your PR. @Ashu-1309

**Pull request merged**
