### PR TITLE
Voting System

### PR DESCRIPTION
**Pull request by neelshah2409**
Title: Voting System

Description: Here there will be 2 nominees for election and 10 voters when all the voters give their vote then result will be announced and for voter one id is assigned to each one if there id doesn't match then they cannot vote.

- [x] LGM-SOC'21 Participant
- [ ] Contributor

Closes: #252 

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
 - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [ ] This change requires a documentation update

Checklist:
- [x] My code follows the guidelines of this project.
 - [x] I have performed a self-review of my own code.
 - [x] I have commented my code, particularly whereever it was hard to understand.
 - [ ] I have made corresponding changes to the documentation.
- [x]  My changes generate no new warnings.
 - [ ] I have added tests that prove my fix is effective or that my feature works.
 - [ ] Any dependent changes have been merged and published in downstream modules.

Screenshots:
output_1(voting)
output_2(voting)

### CODE REVIEW

**Comment by neelshah2409** [comment]
Mam please review my PR.

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved. @neelshah2409

**Comment by prathimacode-hub** [comment]
Hey sorry, this PR is not merged yet, So your converter got merged into this PR. So kindly remove all the files related to your converter. Once I merge this PR, you can create a new PR. @neelshah2409

**Comment by neelshah2409** [comment]
Mam please merge this so I can add Video to Audio.

**Comment by prathimacode-hub** [comment]
> Mam please merge this so I can add Video to Audio.

Your PR is merged, You can create a new PR. 🙂 @neelshah2409

**Pull request merged**
