### PR TITLE
Added Fruit Ninja Game 

### PR DESCRIPTION
**Pull request by Khushi-sharma07**
Description: It is a Python PyGame Script made for entertainment purpose. It is the script for a game very popular among kids "Fruit Ninja". Player has to run the program and then the first screen will appear and user has to press any key on the keyboard and game will start then they have to slice the fruits which will pop randomly on the screen, but if the player pops a bomb then they will lose 1 life and in total they have 3 lives with them.

- [x]  LGM-SOC'21 Participant
- [ ]  Contributor

Closes: #509 

Type of change
What sort of change have you made:

- [ ]  Bug fix (non-breaking change which fixes an issue)
- [x]  New feature (non-breaking change which adds functionality)
- [ ]  Code style update (formatting, local variables)
- [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ]  This change requires a documentation update

Checklist:

- [x]  My code follows the guidelines of this project.
- [x]  I have performed a self-review of my own code.
- [x]  I have commented my code, particularly where ever it was hard to understand.
- [ ]  I have made corresponding changes to the documentation.
- [x]  My changes generate no new warnings.
- [ ]  I have added tests that prove my fix is effective or that my feature works.
- [ ]  Any dependent changes have been merged and published in downstream modules.

SCREENSHOTS:

FirstScreen

GameScreen

GameOver Screen

### CODE REVIEW

**Review by Debashish-hub — CHANGES_REQUESTED** [review]
Just a small change, rename your images folder to 'Images' and accordingly the link in readme @Khushi-sharma07

**Comment by Khushi-sharma07** [comment]
I had done the changes. Please review

**Comment by prathimacode-hub** [comment]
> I had done the changes. Please review

Changes aren't showing up. Instead of "Images" folder it's in "images" folder.
Kindly change that. And also in "README.md" file, add workflow and compilation steps of the project. @Khushi-sharma07

**Comment by Khushi-sharma07** [comment]
I had renamed the folder to Media, is it fine?
And I had also made the changes wherever required.
Please review again @prathimacode-hub @Debashish-hub

**Review by prathimacode-hub — APPROVED** [review]
Fab and Impressive Work. Adding up fruit slices in your README is fun. Yoooo. You're blazing high. 🤩🤩🤩@Khushi-sharma07

**Comment by Khushi-sharma07** [comment]
Thank you mam.😌
Mam just out of curiosity I wanted to know what is this To-Do tag in github for?

**Review by Debashish-hub — APPROVED** [review]

**Comment by Debashish-hub** [comment]
> Thank you mam.😌
> Mam just out of curiosity I wanted to know what is this To-Do tag in github for?

That's for the scoring purpose i.e. for us. Your PR is approved . Congrats! Keep it up @Khushi-sharma07

**Comment by Khushi-sharma07** [comment]
Thank you!

**Comment by prathimacode-hub** [comment]
Wonderful add on. You did a splendid job. Keep rising. 🤩🤩 @Khushi-sharma07

**Pull request merged**
