### PR TITLE
Pattern 

### PR DESCRIPTION
**Pull request by Ashu-1309**
## Related Issue 

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #521 

### Describe the changes you've made

Through this code we can print out different pattern

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how have you verified the changes made

## Checklist:

- [x] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly whereever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Ashu-1309** [comment]
I will upload the Readme file tomorrow .

**Review by Debashish-hub — CHANGES_REQUESTED** [review]
Please follow the correct folder structure. Add readme.md, requirements.txt files @Ashu-1309

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
This PR is missing a "README.md"  and "requirements.txt" file. Kindly add it. @Ashu-1309

**Comment by Ashu-1309** [comment]
I have done all the required changes .

**Review by prathimacode-hub — APPROVED** [review]
Unique script choosen. Good work. Keeping rising your progress. PR approved. 👌🎊🧨@Ashu-1309

**Comment by Ashu-1309** [comment]
You have mark to do ??? What is the purpose of to do label.

**Comment by prathimacode-hub** [comment]
> You have mark to do ??? What is the purpose of to do label.

This mark is for us to keep track of ur scores. It's our work. Nowhere related to your PR. @Ashu-1309

**Pull request merged**
