### PR TITLE
Added Code for Text Extractor from PDF 

### PR DESCRIPTION
**Pull request by Sakalya100**
## Related Issue 

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #234

### Describe the changes you've made
Made a Python Script using a module named PyPDF2 . The program read the pdf and extracts the text from the pdf and writes it into a new file.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Debashish-hub** [comment]
Add screenshots to an image folder and show them in the readme file.
Add a requirement.txt
Always follow the Contributing Guidelines @Sakalya100

**Comment by Sakalya100** [comment]
@Debashish-hub Ok sir I will make the changes.

**Comment by Sakalya100** [comment]
@Debashish-hub Sir I have made the necessary changes as asked by you. Kindly review it once

**Comment by Debashish-hub** [comment]
No need of readme inside Image folder and add the image source in readme of your image folder i.e. 'Images/imageName.png'  @Sakalya100

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:

The readme file should be titled as "README.md".
Add aim, purpose and compilation steps in your 'README.md' file and as well your name at the end of the file.
Add your project in .py file. Also the project file should be titled as "text_extractor.py"
You don't have to show the installation procedures in your project file. Just a simple program file along with appropriate comments to get good understanding of the program. You can refer with other projects in repo, to know how program file should look like.

Kindly do these needful changes. @Sakalya100

**Comment by Sakalya100** [comment]
@prathimacode-hub Mam I have made the asked changes. Kindly review it once

**Review by prathimacode-hub — APPROVED** [review]
Welcome to the repo officially. Your PR is approved. Good start to your journey. Impressed by your README file. Well done. 👏✨🎉@Sakalya100

**Comment by Sakalya100** [comment]
Thank you so much @Debashish-hub @prathimacode-hub for the guidance and pointing out the improvements.

**Comment by prathimacode-hub** [comment]
> Thank you so much @Debashish-hub @prathimacode-hub for the guidance and pointing out the improvements.

Most welcome

**Pull request merged**
