### PR TITLE
Calculator app added

### PR DESCRIPTION
**Pull request by manognyaa**
I have created calculator using python:-
Here I'm sharing the screenshots of the project
image
image
image

@prathimacode-hub  mam please guide me if any changes are required. 
Thank you.

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Hey, where is the issue created? Before you raise a PR, you should create an issue. The issue you had created earlier isn't considered as it's not created after the concerned time. Do create a new issue with project title. Follow the template to do so. You can refer to assigned issues to know how a template looks like.  Once issue is assigned to you, raise the PR again. Never close issues and PR from your end. Letting you know about the things. @manognyaa

**Comment by prathimacode-hub** [comment]
Follow the PR template, add README.md file. There is a template to know how a README should look like. Add requirements.txt file. Follow the proper project structure to get your PR merged. It's not considered a project, until there is no README file. Screenshot inclusion is must in README. All screenshots and images concerning the project should be added in "Images" folder. File name should in snake case. I elaborated everything in README and CONTRIBUTING GUIDELINES of the project. Do look at it to have a fair idea of how to move forward. @manognyaa

**Comment by prathimacode-hub** [comment]
You should never close PR or issue from your end, it's against open source. @manognyaa

**Comment by manognyaa** [comment]
Sorry mam
Sorry for the inconvenience caused to you.
I will make sure that it would not happen again.

**Comment by prathimacode-hub** [comment]
That's Ok. Correct the other PR you had created with changes needed. @manognyaa

**Pull request closed without merging**
