### PR TITLE
Image Size Compressor

### PR DESCRIPTION
**Pull request by neelshah2409**
# Image Size Compressor 
## Description
Here we change the size of the image using the Image module of PIL library without changing the dimension of the image.
- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

Closes: #809 
## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly where ever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

output_1(img_compressor)
output_2(img_compressor)

### CODE REVIEW

**Review by Debashish-hub — CHANGES_REQUESTED** [review]
It's an image processing script. It should be inside ImageProcessingscripts folder @neelshah2409

**Comment by neelshah2409** [comment]
> It's an image processing script. It should be inside ImageProcessingscripts folder @neelshah2409

Yes ,srry it was my mistake I will change it.

**Comment by neelshah2409** [comment]
@Debashish-hub Please review my PR I had made the changes.

**Review by Debashish-hub — APPROVED** [review]
PR approved @neelshah2409

**Comment by prathimacode-hub** [comment]
Well done. Good to see your spirit in contributing even though you had become a mentor for other program. 😀👌@neelshah2409

**Pull request merged**
