### PR TITLE
covid-19 cases using web scraping

### LINKED ISSUE #205: Want to add a script for COVID cases
Title: want to add a script for COVID cases
Name: **Umesh Singh**
Label: Feature Request
Define You
- [x] LGM-SOC'21 Participant
- [ ] Contributor

### Solution
I want to add a Python script under Web Scraping scripts to fetch the Covid-19 cases for any country. I will be fetching the data from a website to show the details like total cases, death, etc.

### PR DESCRIPTION
**Pull request by Umesh-01**
## Title: Added a python script for Covid19 cases using Web scraping

- [x] LGMSOC-21 Participant

This PR fixes #205 

## Changes done
Added a folder with a python script file for Covid19 cases, appropriate screenshots and a README.md file to explain the details for the module used in Web scraping.

## Types of changes
New Feature

## Screenshot

image

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Needs small changes

- Add project title as "Covid Cases"
- And add "requirements.txt" file with the libraries imported in the project.

Kindly do this change. @Umesh-01

**Comment by Umesh-01** [comment]
@prathimacode-hub mam should I rename the folder also or only the title **"Covid Cases"**??

**Comment by Umesh-01** [comment]
@prathimacode-hub mam done, pls check it 🙂

**Comment by prathimacode-hub** [comment]
> @prathimacode-hub mam should I rename the folder also or only the title **"Covid Cases"**??

Yes, please rename the folder.

**Comment by Umesh-01** [comment]
@prathimacode-hub mam done, now check it...

**Review by prathimacode-hub — APPROVED** [review]
Perfect. You nailed it. Fab work. 🏷😎@Umesh-01

**Pull request merged**
