### PR TITLE
created Image Steganography(CMD)

### PR DESCRIPTION
**Pull request by dilroseR**
### **Related Issue**
- Info about the related issue

- [ ] LGM-SOC'21 Participant
- [x]  DevIncept Participant
- [ ]  Contributor

Closes: #774 

**Describe the changes you've made:**
A system which takes msg from the user and will hide it in a image using encryption with the help of secret key provided by the user.
The msg can be decrypted from the image by giving in the secret key so that only the intender receiver can see it.

**Type of change**
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x]  New feature (non-breaking change which adds functionality)
- [ ]  Code style update (formatting, local variables)
- [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ]  This change requires a documentation update

**Checklist:**
- [x] My code follows the guidelines of this project.
- [x]  I have performed a self-review of my own code.
- [x]  I have commented my code, particularly whereever it was hard to understand.
- [ ]  I have made corresponding changes to the documentation.
- [x]  My changes generate no new warnings.
- [x]  I have added screenshots that prove my fix is effective or that my feature works.
- [ ]  Any dependent changes have been merged and published in downstream modules.

### Screenshots
test

### CODE REVIEW

**Review by prathimacode-hub — COMMENTED** [review]
Follow the project structure given. @dilroseR

**Comment by dilroseR** [comment]
> Follow the project structure given. @dilroseR

done!

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Images should be in "Images" folder
Also there is a README template provided. Follow it. Your README.md lacks details.

@dilroseR

**Comment by dilroseR** [comment]
> Images should be in "Images" folder
> Also there is a README template provided. Follow it. Your README.md lacks details.
> 
> @dilroseR

done

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
The images links you add in README.md file should be the file path of the images present in this repository not "user-images" content
And also all the images should be in "Images" folder.

Your README is perfect. @dilroseR

**Comment by dilroseR** [comment]
> The images links you add in README.md file should be the file path of the images present in this repository not "user-images" content
> And also all the images should be in "Images" folder.
> 
> Your README is perfect. @dilroseR

as you can see all the images are in the Images folder and it was like this before also

**Comment by prathimacode-hub** [comment]
> > The images links you add in README.md file should be the file path of the images present in this repository not "user-images" content
> > And also all the images should be in "Images" folder.
> > Your README is perfect. @dilroseR
> 
> as you can see all the images are in the Images folder and it was like this before also
> 

Then push the contents here. It's not showing up then. @dilroseR

**Comment by dilroseR** [comment]
> > > The images links you add in README.md file should be the file path of the images present in this repository not "user-images" content
> > > And also all the images should be in "Images" folder.
> > > Your README is perfect. @dilroseR
> > 
> > 
> > as you can see all the images are in the Images folder and it was like this before also
> > 
> 
> Then push the contents here. It's not showing up then. @dilroseR



> > > The images links you add in README.md file should be the file path of the images present in this repository not "user-images" content
> > > And also all the images should be in "Images" folder.
> > > Your README is perfect. @dilroseR
> > 
> > 
> > as you can see all the images are in the Images folder and it was like this before also
> > 
> 
> Then push the contents here. It's not showing up then. @dilroseR

Can you check now?

**Review by prathimacode-hub — APPROVED** [review]
Yup, now it shows. There is no need of proof here. And I did say right, it didn't show up earlier. It's upto you if you don't believe. Anyways your PR is approved. Congrats. 🎉✨👏@dilroseR

**Comment by dilroseR** [comment]
> Yup, now it shows. There is no need of proof here. And I did say right, it didn't show up earlier. It's upto you if you don't believe. Anyways your PR is approved. Congrats. 🎉✨👏@dilroseR

Sorry, I didn't mean to offend you. Actually this problem is happening with me on the another projects as well. For the other projects ,I've shown like this that after pushing everything, there are no files to commit . It's just a check on my side that I've pushed and why it is not coming on the other side.

**Comment by prathimacode-hub** [comment]
No worries, that's Ok. I just cleared things. Things should get settled. That's the reason I mentioned it. Chill. 😀👍@dilroseR

**Pull request merged**
