### PR TITLE
Quotes Extractor

### PR DESCRIPTION
**Pull request by Gaurav1401**
## Related Issue 

- Extracting Quotes from Website

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

Closes: #798 

### Describe the changes you've made

Wrote complete code to extract codes from the website along with proper description in the markdowns and proper comments

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Debashish-hub** [comment]
Please follow proper PR template and before that create an issue and get it assigned @Mannuel25

**Comment by Gaurav1401** [comment]
@Debashish-hub I am unable to understand what you said, can you please clarify?, also please accept my request on LinkedIn

**Comment by Gaurav1401** [comment]
@Debashish-hub Now, please check my pull request.

**Comment by Gaurav1401** [comment]
@Debashish-hub I have changed the details and removed the word tutorial, thank you very much, now please consider my pull request, I have updated the read me file also

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Is this not a project first of all? It accepts only projects. And project iles should be only in .py format. There is also a project structure given. Follow it. Your project titles, your file names everything should be changed. You said quotes extractor using web scraping. Add that project. @Gaurav1401

**Comment by Gaurav1401** [comment]
@prathimacode-hub mam I have made a lot of changes in the repository now, please forgive me for my previous mistakes, please let me know is it alright now?

**Comment by prathimacode-hub** [comment]
> @prathimacode-hub mam I have made a lot of changes in the repository now, please forgive me for my previous mistakes, please let me know is it alright now?

No need of forgiveness and this is how we shoudl learn right? So no worries as long as you correct it. @Gaurav1401

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Elaborate your README.md file. It needs more details. Kindly check onto the README template for better understanding. @Gaurav1401

**Comment by Gaurav1401** [comment]
@prathimacode-hub mam, thank you very much.
I actually this is first time I am contributing to open source, that's why don't have idea about the guidelines and syntax.
I seriously learnt a lot with you.

I have added some more information in the README.md file.

I hope now it looks good, please let me know anything else is required to be added or not.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:
Add workflow of the project and compilation steps in README.md file
And also the image links you added up in README.md are of "user-images" content instead it should be the file pathn of the images present in this repo.
The project file name should be as "quotes_extractor.py"

Kindly do these changes. @Gaurav1401

**Comment by prathimacode-hub** [comment]
> @prathimacode-hub mam, thank you very much.
> I actually this is first time I am contributing to open source, that's why don't have idea about the guidelines and syntax.
> I seriously learnt a lot with you.
> 
> I have added some more information in the README.md file.
> 
> I hope now it looks good, please let me know anything else is required to be added or not.

Sure, glad to see you select this project. I had advised the necessary changes and don't worry about being a beginner, that's how you learn it. So you are going good. @Gaurav1401

**Comment by Gaurav1401** [comment]
@prathimacode-hub So mam, now will this project be added on the main repository?
Also please accept my LinkedIn request

**Comment by prathimacode-hub** [comment]
> @prathimacode-hub So mam, now will this project be added on the main repository?
> Also please accept my LinkedIn request

Have you done the changes? I don't find any changes here. And Yeah, I will accept the request. It will be merged into main repo once things are in right place. You can do this. @Gaurav1401

**Comment by Gaurav1401** [comment]
@prathimacode-hub yes mam, I have changed the location of those images and also added more info. in my readme file

**Comment by prathimacode-hub** [comment]
> @prathimacode-hub yes mam, I have changed the location of those images and also added more info. in my readme file


You hadn't done these changes yet. @Gaurav1401 
Add workflow of the project and compilation steps in README.md file
The project file name should be as "quotes_extractor.py"

**Comment by Gaurav1401** [comment]
@prathimacode-hub Sorry for the delay mam,
Actually I forgot to commit and push all the changes, but now I have made it, I hope now it's clear :).

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Yayy, it's perfect. Congrats on your first PR. Keep it up. This was a great start. And welcome to the repo officially. 👏✨🎉@Gaurav1401

**Pull request merged**
