### PR TITLE
File Transfer

### PR DESCRIPTION
**Pull request by kumarjeetray**
## Related Issue 

- Info about the related issue 

- [X] LGM-SOC'21 Participant 
- [X] Contributor

Closes: #449 

### Describe the changes you've made

Give a clear description what modifications you have made

I have made the file

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

I have run and tested the code

## Checklist:

- [X] My code follows the guidelines of this project.
- [X] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly whereever it was hard to understand.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by Debashish-hub — CHANGES_REQUESTED** [review]
Use the image source as the path of your Images folder i.e. 'Images/imageName.jpg' instead of the link in the readme.
@kumarjeetray

**Comment by kumarjeetray** [comment]
> 
> 
> Use the image source as the path of your Images folder i.e. 'Images/imageName.jpg' instead of the link in the readme.
> @kumarjeetray

Done. Please do check.

**Comment by Debashish-hub** [comment]
> > Use the image source as the path of your Images folder i.e. 'Images/imageName.jpg' instead of the link in the readme.
> > @kumarjeetray
> 
> Done. Please do check.

Please add a requirements.txt . I forgot to tell that earlier

**Comment by kumarjeetray** [comment]
> 
> 
> > > Use the image source as the path of your Images folder i.e. 'Images/imageName.jpg' instead of the link in the readme.
> > > @kumarjeetray
> > 
> > 
> > Done. Please do check.
> 
> Please add a requirements.txt . I forgot to tell that earlier

But there are no additional requirements/downloads for running this file, that's why I have not added it

**Comment by Debashish-hub** [comment]
> > > > Use the image source as the path of your Images folder i.e. 'Images/imageName.jpg' instead of the link in the readme.
> > > > @kumarjeetray
> > > 
> > > 
> > > Done. Please do check.
> > 
> > 
> > Please add a requirements.txt . I forgot to tell that earlier
> 
> But there are no additional requirements/downloads for running this file, that's why I have not added it except Python IDE

You can add the libraries you are using like socket

**Comment by kumarjeetray** [comment]
> 
> 
> > > > > Use the image source as the path of your Images folder i.e. 'Images/imageName.jpg' instead of the link in the readme.
> > > > > @kumarjeetray
> > > > 
> > > > 
> > > > Done. Please do check.
> > > 
> > > 
> > > Please add a requirements.txt . I forgot to tell that earlier
> > 
> > 
> > But there are no additional requirements/downloads for running this file, that's why I have not added it except Python IDE
> 
> You can add the libraries you are using like socket

Done, please do check

**Review by Debashish-hub — APPROVED** [review]
Great. Your PR is approved @kumarjeetray  Congratulations

**Pull request merged**
