### PR TITLE
Added Code For KhataBook Script

### PR DESCRIPTION
**Pull request by Knighthawk-Leo**
Closes: #694 

Title: Khatabook UI Script
About: It's an GUI script
Name: Sanskar Dwivedi

Define You:

LGM-SOC'21 Participant
Contributor
# Khatabook Script
This is an UI based Credit Management System App . This Will Manage credits of customers for local shops . As we know in India the credit system is very useful and this will help the shopkeepers to manage their shops. They can manage the customer profiles by just their Id they can perform Multiple Operations Such As

* Add Customer Data
* update The Data
* Delete The Data
* To show All remaining credits.

## Type of change
What sort of change have you made:

* New feature (non-breaking change which adds functionality)

## Checklist:
 * My code follows the guidelines of this project.
 * I have performed a self-review of my own code.
 * I have commented my code, particularly wherever it was hard to understand.
 * I have made corresponding changes to the documentation.
 * My changes generate no new warnings.
 * I have added things that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by Debashish-hub** [comment]
You are not following proper folder structure and also mention the issue number.
@Knighthawk-Leo

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Follow the project structure provided. @Knighthawk-Leo

**Comment by Knighthawk-Leo** [comment]
I have Changed The Folder Structure You Can check that..

**Comment by Knighthawk-Leo** [comment]
I have Added the readme.md file and the requirement.txt

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
It's not in right project structure. Changes to be done

- The folder name shoudl be as "Khata Book Management System"
- The project file should be as khata_book.py
- The README should be as "README.md"
- The README.md is not in right template. Template is provided in README file of this project.
- The requirements file should be as "requirements.txt"
- The images and output screenshots shoudl be place in "Images" folder.

Kindly do these needful changes. @Knighthawk-Leo

**Comment by Knighthawk-Leo** [comment]
I am done with All the canges you mentioned abbove @prathimacode-hub

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Add purpose and workflow of the project in README.md
Also elaborate the compilations steps, not everyone would be aware of SQL. 
Add appropriate comments in the code to get good understanding of the project
The requirements file should be as "requirements.txt"

Do these changes. @Knighthawk-Leo

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
The requirements.txt shows double .txt
Also appropriate comments in code are not added wherever needed in project file.

Kindly correct that. @Knighthawk-Leo

**Comment by Knighthawk-Leo** [comment]
I added comments at all places where it required. And also done with all the changes you mentioned.

**Review by prathimacode-hub — APPROVED** [review]
Congrats and welcome to the repo offiicially. Your PR is approved. Yayy. Well done. Congrats. 👌🎉✨@Knighthawk-Leo

**Comment by Knighthawk-Leo** [comment]
@prathimacode-hub Thank you For guiding me and the support this is the very first time I am  dealing with open souurce and learned a lot from your side. Thankyou

**Comment by prathimacode-hub** [comment]
> @prathimacode-hub Thank you For guiding me and the support this is the very first time I am dealing with open souurce and learned a lot from your side. Thankyou

Most welcome and you are free to do as many contributions as you could. All the best for your open source journey. This is just a  start and you had got a long way to travel. Glad to know my guidance helped you. Well done. 🙌@Knighthawk-Leo

**Comment by Knighthawk-Leo** [comment]
> > @prathimacode-hub Thank you For guiding me and the support this is the very first time I am dealing with open souurce and learned a lot from your side. Thankyou
> 
> Most welcome and you are free to do as many contributions as you could. All the best for your open source journey. This is just a start and you had got a long way to travel. Glad to know my guidance helped you. Well done. @Knighthawk-Leo

Ma'am can I have a certificate of this

**Comment by prathimacode-hub** [comment]
Sure, i would like to send it to you. Your certificate is all ready. I didn't have your mail id. @Knighthawk-Leo

**Comment by Knighthawk-Leo** [comment]
> Sure, i would like to send it to you. Your certificate is all ready. I didn't have your mail id. @Knighthawk-Leo

My mail id is sanskardwivedi003@gmail.com

And my name is Sanskar Dwivedi

**Comment by prathimacode-hub** [comment]
Ok you will get a mail in 2 mins. @Knighthawk-Leo

**Comment by prathimacode-hub** [comment]
Yup, you must have received. Sent. @Knighthawk-Leo

**Pull request merged**
