### PR TITLE
Added Image to Icon Converter in GUI Scripts

### PR DESCRIPTION
**Pull request by akash435**
## Related Issue 

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

fixes : #298
Closes: #298

### Describe the changes you've made

Added a Image to Icon Converter in GUIScripts.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

I have run the script and converted images also.

## Checklist:

- [x] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |

### CODE REVIEW

**Comment by Debashish-hub** [comment]
Please add the link of the images of your image folder to the readme.md @akash435

**Comment by akash435** [comment]
@Debashish-hub , i have already added the github links of all images in the README.md file.

**Comment by Debashish-hub** [comment]
> @Debashish-hub , i have already added the github links of all images in the README.md file. Links of all the 8 images are there in README file under Screenshots heading.

It should be like 'Images/NameOfImage' not the githubusercontent link

**Comment by akash435** [comment]
@Debashish-hub , added the images link as asked , please check it.

**Comment by akash435** [comment]
@Debashish-hub, updated readme with image link, please check it

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved. Yayy. You nailed it. Perfect. Wonderful work and good choice of project. 🎉✨@akash435

**Comment by akash435** [comment]
just want to ask why it is not merged, since it is approved?

**Comment by prathimacode-hub** [comment]
> Thanks, just want to ask why it is not merged, since it is approved? Any issue?

No issue, if it's approved then it's all clean. Nothing to worry. It will be merged soon once labels are decided. @akash435

**Pull request merged**
