### PR TITLE
Adventure Based Game(Text Game)

### PR DESCRIPTION
**Pull request by neelshah2409**
## Adventure Based Game(Text Game)
Description: Here it is a adventure like fun game where you will be asked in every question to choose from 2 options and as you answered another question will be asked and at last if you answered all questions correctly then you will win. 

- [x] LGM-SOC'21 Participant

- [ ] Contributor

Closes: #318 

Type of change
What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
 - [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

Checklist:
- [x] My code follows the guidelines of this project.
 - [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly where ever it was hard to understand.
 - [ ] I have made corresponding changes to the documentation.
 - [x] My changes generate no new warnings.
 - [ ] I have added tests that prove my fix is effective or that my feature works.
 - [ ] Any dependent changes have been merged and published in downstream modules.

Screenshots:
output_1(adventure)
output_2(adventure)

### CODE REVIEW

**Comment by neelshah2409** [comment]
Mam please review it so I can go with desktop notification.

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved. You can take up another issue. Great going. 🙌🎇@neelshah2409

**Comment by neelshah2409** [comment]
Mam please merge this so I can make another PR for desktop notification.

**Comment by prathimacode-hub** [comment]
Yes, this PR is merged, You can create a next PR on Desktop Notification. @neelshah2409

**Pull request merged**
