### PR TITLE
Document Converter App using python

### PR DESCRIPTION
**Pull request by chandu6111**
## Related Issue 

- Info about the related issue 
**Title**: Document Converter App using Python
**Name**: Chandana (chandu6111)
**Label**: Feature Request
- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #513 

### Changes I've made
- Added a folder **Document Converter App** under the **Basic Python Scripts** folder.
- The folder contains 8 files which consist of the code scripts of 8 different types of conversions along with comments on each line.
- It also has a **Readme.MD** file and **requirements.txt** file which explains everything about the code.
- It has a folder named **Demo Videos** which contains output videos.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by chandu6111** [comment]
@prathimacode-hub please do review my PR and lemme know the changes required :)

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
There is no code in pdf to ppt, ppt to pdf. Also README should be elaborate. Follow the template given. @chandu6111

**Comment by chandu6111** [comment]
> There is no code in pdf to ppt, ppt to pdf. Also, README should be elaborate. Follow the template given. @chandu6111 

@prathimacode-hub for pdf to ppt and ppt to pdf you can directly execute the commands (given in the comments) in the terminal. That's why I didn't write code, I just wrote the commands in comments. You don't need a code for that, after installing the requirements, if you execute the command given in comments of ppt_to_pdf and pdf_to_ppt in the terminal, they directly get converted. Tell me if this is Okay for you, because I didn't find the other way for these 2 conversions.

I will check the Readme template once.

**Comment by Debashish-hub** [comment]
> > There is no code in pdf to ppt, ppt to pdf. Also, README should be elaborate. Follow the template given. @chandu6111
> 
> @prathimacode-hub for pdf to ppt and ppt to pdf you can directly execute the commands (given in the comments) in the terminal. That's why I didn't write code, I just wrote the commands in comments. You don't need a code for that, after installing the requirements, if you execute the command given in comments of ppt_to_pdf and pdf_to_ppt in the terminal, they directly get converted. Tell me if this is Okay for you, because I didn't find the other way for these 2 conversions.
> 
> I will check the Readme template once.



> > There is no code in pdf to ppt, ppt to pdf. Also, README should be elaborate. Follow the template given. @chandu6111
> 
> @prathimacode-hub for pdf to ppt and ppt to pdf you can directly execute the commands (given in the comments) in the terminal. That's why I didn't write code, I just wrote the commands in comments. You don't need a code for that, after installing the requirements, if you execute the command given in comments of ppt_to_pdf and pdf_to_ppt in the terminal, they directly get converted. Tell me if this is Okay for you, because I didn't find the other way for these 2 conversions.
> 
> I will check the Readme template once.

Doesn't it require the name of file or path of file to be converted? 

You can add all the steps with comments in that file and the required code

**Comment by chandu6111** [comment]
The path of the file should be mentioned in the command executed in the terminal itself. Could you please watch the demo video under 
- Demo Videos >
- ppt_to_pdf.mp4 and pdf_to_ppt.mp4

You will get a clear idea of how it works
@Debashish-hub and @prathimacode-hub

**Comment by Debashish-hub** [comment]
> The path of the file should be mentioned in the command executed in the terminal itself. Could you please watch the demo video under
> 
> * Demo Videos >
> * ppt_to_pdf.mp4 and pdf_to_ppt.mp4
> 
> You will get a clear idea of how it works
> @Debashish-hub and @prathimacode-hub

You just add all the details that you are doing in the file.

**Comment by prathimacode-hub** [comment]
Have you done the changes? @chandu6111

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
README.md needs more details, since you had done multiple conversions. It should show all the things you had done and also check on with README template given if you had missed up anything. @chandu6111

**Comment by chandu6111** [comment]
So, I have removed those 2 files and added the commands in the Readme itself. Once please review the changes @prathimacode-hub 

And I made some more changes in Readme including links for particular code files. It is descriptive now...

**Review by prathimacode-hub — APPROVED** [review]
Fab and outstanding work. PR approved. Keep rocking. Good to see your initiation to do all the conversions. 🤩🙌👏@chandu6111

**Pull request merged**
