### PR TITLE
Google Meet Automation

### PR DESCRIPTION
**Pull request by Knighthawk-Leo**
Related Issue
A Google Meet Automation Script to attend Online Classes

 Hacktoberfest2021 Participant
 Contributor
Closes: #1007

Type of change
What sort of change have you made:
Added The Script to automate google meet .

 Bug fix (non-breaking change which fixes an issue)
 New feature (non-breaking change which adds functionality)
 Code style update (formatting, local variables)
 Breaking change (fix or feature that would cause existing functionality to not work as expected)
 This change requires a documentation update
How Has This Been Tested?
Tested the script on my local machine for different test cases.

Checklist:

 My code follows the guidelines of this project.
 I have performed a self-review of my own code.
 I have commented my code, particularly wherever it was hard to understand.
 I have made corresponding changes to the documentation.
 My changes generate no new warnings.
 I have added tests that prove my fix is effective or that my feature works.
 Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Knighthawk-Leo** [comment]
@prathimacode-hub Can you review this

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done : 

Elaborate your README.md file. You can check out the template provided. It needs to be briefer. 
All your .py file names should be in snake case. 
Add appropriate comments in your code to get good understanding of the project
Create an "Images" folder and place output screenshots in it and as well add out those links in README.md

Kindly do these changes. @Knighthawk-Leo

**Comment by Knighthawk-Leo** [comment]
@prathimacode-hub Please check the changes

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Great work. ✔✨@Knighthawk-Leo

**Pull request merged**
