### PR TITLE
Levels and Points #303

### LINKED ISSUE #303: Add LGM-SOC'21 score card in readme.md
Add LGM-SOC'21 score card in readme.md

### PR DESCRIPTION
**Pull request by ishitakapoor26**
[x]-LGM-SOC'21 Participant
[x]- Contributor
Closes: #303 

Describe the changes you've made:
Added Levels and Points Section in readme.md

Type of change
What sort of change have you made:

 [ ]-Bug fix (non-breaking change which fixes an issue)
 [x]-New feature (non-breaking change which adds functionality)
 [ ]-Code style update (formatting, local variables)
 [ ]-Breaking change (fix or feature that would cause existing functionality to not work as expected)
 [ ]-This change requires a documentation update

How Has This Been Tested?
This code has been tried on my local machine.

Checklist:
[x]- My code follows the guidelines of this project.
[x]- I have performed a self-review of my own code.
[x]- I have commented on my code, particularly wherever it was hard to understand.
[x]- I have made corresponding changes to the documentation.
[x]- My changes generate no new warnings.
[x]- I have added tests that prove my fix is effective or that my feature works.
[x]- Any dependent changes have been merged and published in downstream modules.

Screenshots

lvl

### CODE REVIEW

**Comment by ishitakapoor26** [comment]
@prathimacode-hub pls review my pr.

**Comment by prathimacode-hub** [comment]
> @prathimacode-hub pls review my pr.

Add the PR template to it. @ishitakapoor26

**Comment by ishitakapoor26** [comment]
@prathimacode-hub pls check now added pr template.

**Comment by prathimacode-hub** [comment]
Yup, checked thanks for the changes. PR is approved and merged. 👏@ishitakapoor26

**Pull request merged**
