### PR TITLE
Password Validator

### PR DESCRIPTION
**Pull request by Mannuel25**
## Related Issue 

- Info about the related issue 

- [ ] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [x] Contributor

Closes: #805 

### Describe the changes you've made

Give a clear description what modifications you have made

This program validates passwords to match specific rules. A valid password is one that conforms to the following rules:
- Minimum length is 6;
- Maximum length is 12;
- Contains at least an uppercase letter or a lowercase letter
- Contains at least a number;
- Contains at least a special character (such as @,+,£,$,%,*^,etc);
- Doesn't contain space(s).

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how have you verified the changes made

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots
screenshot_1

screenshot_2

screenshot_3

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Kindly follow the project structure given in README file of the project. @Mannuel25

**Comment by Mannuel25** [comment]
> Kindly follow the project structure given in README file of the project. @Mannuel25

Okay, I'll work on it. Thanks

**Comment by Mannuel25** [comment]
> > Kindly follow the project structure given in README file of the project. @Mannuel25
> 
> Okay, I'll work on it. Thanks

I've made some changes @prathimacode-hub, please help verify the changes made. Thanks.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:
In README.md, add aim and compilation steps.
All images and screenshots should be in  "Images" folder in "Password Validator" and also change the file paths of the image links present in README.md accordingly. 
The project file should be titled as "password_validatorpy"
In "requirements.txt" file, add all the libraries imported in this project. 

Kindly do these changes. @Mannuel25

**Comment by Mannuel25** [comment]
> Changes to be done:
> In README.md, add aim and compilation steps.
> All images and screenshots should be in "Images" folder in "Password Validator" and also change the file paths of the image links present in README.md accordingly.
> The project file should be titled as "password_validatorpy"
> In "requirements.txt" file, add all the libraries imported in this project.
> 
> Kindly do these changes. @Mannuel25

Okay, I'll make amendments. Thanks

**Comment by Mannuel25** [comment]
> > Changes to be done:
> > In README.md, add aim and compilation steps.
> > All images and screenshots should be in "Images" folder in "Password Validator" and also change the file paths of the image links present in README.md accordingly.
> > The project file should be titled as "password_validatorpy"
> > In "requirements.txt" file, add all the libraries imported in this project.
> > Kindly do these changes. @Mannuel25
> 
> Okay, I'll make amendments. Thanks

Changes made, help verify I made the right changes. Thanks

**Review by prathimacode-hub — APPROVED** [review]
Congrats and welcome to the repo officially. Your PR is approved. Amazing work and good dedication. Keep contributing. 🎉✨🤩@Mannuel25

**Comment by prathimacode-hub** [comment]
Can you let me know of your mail id and your full name? @Mannuel25

**Comment by Mannuel25** [comment]
> Can you let me know of your mail id and your full name? @Mannuel25

Yeah, sure. I'm Emmanuel Tanimowo, and my mail id is oluwasegunprosperity@gmail.com.

**Pull request merged**
