### PR TITLE
Web Scraping Flipkart website using BeautifulSoup Library of Python [WebScrapingScripts Folder ]

### PR DESCRIPTION
**Pull request by singhmansi25**
Related Issue: #1095 

- [ ] Hacktoberfest2022 Participant

- [ ] Contributor

Closes: #1095

**Description**
We will be scraping data from Flipkart website and then will use the data to create a DataFrame, which used for data analysis.

**Type of change**

- [ ]  New feature (non-breaking change which adds functionality)
- [ ]  Code style update (formatting, local variables)

**How Has This Been Tested?**
I have self verified the codes.

**Checklist:**

- [ ]  My code follows the guidelines of this project.
- [ ]  I have performed a self-review of my own code.
- [ ]  I have commented my code, particularly where ever it was hard to understand.
- [ ]  I have made corresponding changes to the documentation.
- [ ]  My changes generate no new warnings.
- [ ]  I have added tests that prove my fix is effective or that my feature works.
- [ ]  Any dependent changes have been merged and published in downstream modules.

**Screenshots**
Screenshots are attached for reference.

### CODE REVIEW

**Comment by singhmansi25** [comment]
@prathimacode-hub 
Please review my PR

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done :

Write your project folder as "Flipkart Mobiles Scraping"
Rename the readme file as README.md
Add the scraped project file in .py format rather than .ipynb

Kindly do these changes. @singhmansi25

**Comment by singhmansi25** [comment]
ok @prathimacode-hub

**Comment by singhmansi25** [comment]
@prathimacode-hub 
Please review my PR again.

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Well done. 👍👏@singhmansi25

**Pull request merged**
