### PR TITLE
Collage Mosaic Generator

### PR DESCRIPTION
**Pull request by rammya29**
## Related Issue 

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #476 

### Describe the changes you've made

Give a clear description what modifications you have made

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how have you verified the changes made
 Tested in command prompt and the command is mentioned in README.md and also added the image for testing.                 

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done :
The project file should titled as "mosaic_generator.py"
Add appropriate comments in the code wherever necessary to get good understanding of the project.
Add aim, purpose, workflow, compilation steps in the "README.md" file and also the images links in "README.md" file are of "user-images" content. But instead it should be the file path of the output screenshots present in this repo. 
And the image links added up in "README.md" file, add them in separate "Images" folder.
Add the libraries imported in this project in "requirements.txt" file.

Kindly do these needful changes. @rammya29

**Comment by rammya29** [comment]
I have done all the changes except the image folder name. I am using it in the web version I am unable to do it. Can anyone help how to do it?.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
All changes aren't done yet. @Debashish-hub would guide you.

Changes to be done :
The project file should titled as "mosaic_generator.py"
Add purpose, workflow in the "README.md" file and also the images links in "README.md" file are of "user-images" content. But instead it should be the file path of the output screenshots present in this repo.
And the image links added up in "README.md" file, add them in separate "Images" folder.

Kindly do these needful changes. @rammya29

**Comment by rammya29** [comment]
I changed the following requirements, isn't changed?

**Comment by prathimacode-hub** [comment]
> I changed the following requirements, isn't changed?

No, it didn't show up the changes over here.

**Comment by rammya29** [comment]
Is it changed right now mam?

**Comment by Debashish-hub** [comment]
> Is it changed right now mam?

Add all the images to an Images folder and add the links in readme as 'Images/imageName.jpg'  @rammya29

**Review by prathimacode-hub — APPROVED** [review]
Amazing work. First of all wonderful choice of the project. Keep growing. Your dedication is wow. Well done.  Congrats. Your PR is approved. Yayy. ✨🎉@rammya29

**Pull request merged**
