### PR TITLE
Calculator app added

### PR DESCRIPTION
**Pull request by manognyaa**
## Related Issue 
- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #82 

### Describe the changes you've made

I have created a calculator app using python. The most frequently used language. 

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
I have executed the python script on my local computer and it executes successfully.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

Here I'm sharing Screenshot of the project

 Original           | Updated
 :--------------------: |:--------------------:
1 image
2 image
3 image
   | Updated Screenshot |

@prathimacode-hub mam guide me if any changes are required.

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
I had guided you everything over your previous PR created. Do check it out. @manognyaa

**Comment by prathimacode-hub** [comment]
Kindly do the changes needed. @manognyaa

**Comment by Debashish-hub** [comment]
Hey @manognyaa, Please go through the README and CONTRIBUTING GUIDELINES of the project and do the required changes like adding a README (in proper format), adding requirement.txt, naming of the file etc.

**Comment by manognyaa** [comment]
> Hey @manognyaa, Please go through the README and CONTRIBUTING GUIDELINES of the project and do the required changes like adding a README (in proper format), adding requirement.txt, naming of the file etc.

yes sir, I will be doing it. Thank you sir @Debashish-hub

**Comment by manognyaa** [comment]
> Kindly do the changes needed. @manognyaa

yes mam,  I will do the changes now.
thank you for guiding me. @prathimacode-hub

**Comment by prathimacode-hub** [comment]
> > Kindly do the changes needed. @manognyaa
> 
> yes mam, I will do the changes now.
> thank you for guiding me. @prathimacode-hub

You're welcome. You had followed the right PR template. But in your PR i couldn't see your files. Kindly push your project files to your PR. @manognyaa

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to done:

Follow the project structure mentioned in README file of the project
- Where had you added the files? What kind of script is this? You should create  project folder in the zone it belongs to and add the relevant project files.
- It's a calculator. Is it a "BasicPythonScript" or "GUIScript"?
- The file name of the project should be as calculator.py
- Add the appropriate comments in the project file wherever necessary
- README file should be elaborative. It should comprise of purpose, uses, steps to followed, compilation process, output screenshot
- The images and screenshots you add should go into "Images" Folder

Do the needful changes. @manognyaa

**Comment by Debashish-hub** [comment]
Do update your work and tell if you have any problem @manognyaa

**Comment by manognyaa** [comment]
> Do update your work and tell if you have any problem @manognyaa

ok sir, Thank you @Debashish-hub

**Comment by manognyaa** [comment]
hello,
I have added the readme file and added calculator app.  If there any changes required, pls guide me 
@prathimacode-hub @Debashish-hub

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
It's not in right frame of contributing guidelines.

Changes needed:

- The readme file should be titled as "README.md"
- The project repository should be titled as "Calculator App"
- Here the project, it's a GUI script. This project should move into "GUIScripts" folder.
- In README file, always add the image links of the images available in the forked repository
- Add all the images and screenshots in "Images" folder.
- Add an appropriate comments in your project file wherever necessary for better understanding of the program.
- The README file should be elaborative. Add compilation steps and workflow of the project.

Kindly do the needful changes. @manognyaa

**Comment by manognyaa** [comment]
Hello mam,
I have shifted the app to GUI Script and added READ.md file into it. And also created a folder for images.
If there are any changes please guide me mam @prathimacode-hub

**Review by thegautamkumarjaiswal — COMMENTED** [review]
I would like to suggest top ad python comments to describe little bit about code and what they work.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:

- The images links you had added are of user-images fomat. Kindly add the image links of file path provided in "Images" folder. 
- In project file, add appropriate comments to get good understanding of the project.

You're doing a wonderful work. You can do this. 
@manognyaa

**Comment by manognyaa** [comment]
hello mam,
I have added the images link of the images folder in the README.md file and added the comments where required. 
Pls guide me if there any changes to make @prathimacode-hub

**Review by prathimacode-hub — APPROVED** [review]
No changes needed. You did this perfect. Nailed it. Proud of you. Your PR is approved and merged successfully. 👌👌👏🙌 @manognyaa

**Pull request merged**
