### PR TITLE
Day Finder In A Month

### PR DESCRIPTION
**Pull request by Ashu-1309**
Find the number of days in a month

### CODE REVIEW

**Review by prathimacode-hub — COMMENTED** [review]
Changes to be done :

No proper PR template. Neither an issue number nor a screenshot
The project file should be titled as "days_finder.py"
Add the output screenshot in your README.md file. That's not a proper link. it should be the file path. 

Kindly do these changes. @Ashu-1309

**Comment by prathimacode-hub** [comment]
Why do you create new PR's for changes asked? @Ashu-1309

**Comment by Ashu-1309** [comment]
I was getting that issue again and again . I try a lot and this Create in that try only .  Should I close this PR  ??

**Comment by prathimacode-hub** [comment]
> I was getting that issue again and again . I try a lot and this Create in that try only . Should I close this PR ??

First, let me know of the PR your want to be active in. I had mentioned the changes that needs to be done.  With respect to errors, once you say the PR you want to prolong. I shall guide you with the process. @Ashu-1309

**Comment by Ashu-1309** [comment]
Okay

**Pull request closed without merging**
