### PR TITLE
Internship - Internshala

### PR DESCRIPTION
**Pull request by rammya29**
## Related Issue 

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #806

### Describe the changes you've made

I have chosen a popular internship website where internships can be scrapped using some module in python

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

It has been tested and verified in idle environment

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Kindly follow the right project structure. @rammya29

**Comment by rammya29** [comment]
What need to be corrected mam?

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
The file names of .py files are not in right format. And also README needs few more details. You had missed up few sections. @rammya29

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Only chnage it needs add appropriate comments in project files to get good understanding of the project. @rammya29

**Comment by prathimacode-hub** [comment]
Kindly do the changes. @rammya29

**Comment by prathimacode-hub** [comment]
Plz do the changes needed. @rammya29

**Comment by prathimacode-hub** [comment]
Though changes aren't done I'm merging it as I don't want your  efforts to go wasted. That's Ok. I will add up the comments to the project file. 👍@rammya29

**Review by prathimacode-hub — APPROVED** [review]
PR approved. You had done wonderful work as always. Clean and finest PR. 🏆😎@rammya29

**Pull request merged**
