### PR TITLE
Fibonacci Series Generator

### PR DESCRIPTION
**Pull request by Priyanshi-Rai**
<html>
<h1>Related Issue</h1>
<i>To print the Fibonacci series upto a defined term</i>

- [x]  LGM-SOC'21 Participant

- [x] Contributor

Closes: #277

**_<h2>Describe the changes you've made</h2>_**
<i>I created a program to print Fibonacci series using the conditional and looping statements.</i>

**_<h2>Type of changes </h2>_**

 
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

**_<h2>How Has This Been Tested?</h2>_**
I tested the code in Online python compiler (repelit) as well as in offline compiler (jupyter notebook).

**_<h2>Checklist:</h2>_**
 
- [x] My code follows the guidelines of this project.
- [x]  I have performed a self-review of my own code.
- [x]  I have commented my code, particularly where ever it was hard to understand.
- [x]  I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x]  I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

<h2>SCREENSHOT</h2>

Fib_ouput1

Fib_ouput2

Fib_ouput3

</html>

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
PR template please? @Priyanshi-Rai

**Comment by Priyanshi-Rai** [comment]
> PR template please? And the folder should be titled as "Fibonacci Sequence Generator". @Priyanshi-Rai

oh sorry mam just give me few minutes. 
;)

**Comment by Priyanshi-Rai** [comment]
done :P

**Review by Debashish-hub — APPROVED** [review]
Congrats! @Priyanshi-Rai Your PR is approved

**Review by prathimacode-hub — APPROVED** [review]
Picture perfect PR. Amazing work. Yayy. PR approved. 🙌🙌🙌@Priyanshi-Rai

**Comment by Priyanshi-Rai** [comment]
Wohoooo😁🥳

**Pull request merged**
