### PR TITLE
Added Shivji Sketch Using Turtle.

### PR DESCRIPTION
**Pull request by Kushal997-das**
shiv (2)

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Good to see your initiation to contribute. Go through the contributing guidelines 👍🙂 
I will make things simple for you by stating the changes needed.

- Kindly add this project under "GUIScripts" repository.  
- In this folder, add your project with repository name as "FaceSketching". Also, add Face_Sketching.py and README.md as file name.
- Add Jpg file and GIF file in separate "Images" folder and direct them to the README.md file.

Scripts are perfect. Do these required changes and its done. @Kushal997-das

**Comment by Kushal997-das** [comment]
> Good to see your initiation to contribute. Go through the contributing guidelines 👍🙂
> I will make things simple for you by stating the changes needed.
> 
> * Kindly add this project under "GUIScripts" repository.
> * In this folder, add your project with repository name as "FaceSketching". Also, add Face_Sketching.py and README.md as file name.
> * Add Jpg file and GIF file in separate "Images" folder and direct them to the README.md file.
> 
> Scripts are perfect. Do these required changes and its done. @Kushal997-das

Please add these points in `contributing.md` so that anyone can't fall into trouble after sending PR .
Moreover i can put this file under `GUI` but i can't change the project name because this is not face kind of things .

**Comment by prathimacode-hub** [comment]
Ok. Sure. The points I have mentioned are in template. Anyways thanks for your suggestions. I will modify the changes needed in a single file.  @Kushal997-das

**Comment by Kushal997-das** [comment]
> Ok. Sure. The points I have mentioned are in template. Anyways thanks for your suggestions. I will modify the changes needed in a single file. @Kushal997-das

So you will do this or i will do from my end ?

**Comment by prathimacode-hub** [comment]
I had done the changes needed. I have merged both the template and contributing guidelines into one. @Kushal997-das

**Comment by Kushal997-das** [comment]
> I had done the changes needed. I have merged both the template and contributing guidelines into one. @Kushal997-das

Now check

**Review by prathimacode-hub — APPROVED** [review]
Thank you for your contribution and also for suggesting the changes needed. It was a good addon to this repository. 👍@Kushal997-das

**Comment by Kushal997-das** [comment]
> Thank you for your contribution and also for suggesting the changes needed. It was a good addon to this repository. 👍@Kushal997-das

Most welcome dear check your mail i send you invitation you can join my organisation thank you :)

**Comment by prathimacode-hub** [comment]
I had already joined. Thanks for the invitation.🙂@Kushal997-das

**Pull request merged**
