### PR TITLE
Pie Chart Creator

### PR DESCRIPTION
**Pull request by Khushi-sharma07**
Related Issue
A basic python script to create pie chart from the data entered by user.

- [x] Hacktoberfest2021 Participant
- [x]  Contributor

Closes: #1071 

Describe the changes you've made
Added required files as per the requirement of Pie Chart Creator.

Type of change
What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

How Has This Been Tested?
Tested the script on my local machine for different test cases.

Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

Screenshots:

Screenshot 1

Screenshot 2

### CODE REVIEW

**Comment by Khushi-sharma07** [comment]
Mam in the pull request I had added the requirements.txt file which was missing in my Image Background Remover P.R. If it is a wrong way to do so then I am really sorry for that but I just now noticed that it was missing so added it. @prathimacode-hub

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Fab. 👏👌@Khushi-sharma07

**Comment by Khushi-sharma07** [comment]
Thank you mam😊

**Comment by prathimacode-hub** [comment]
You're super active and delivered in time as said. Fab spirit you have got. @Khushi-sharma07

**Comment by Khushi-sharma07** [comment]
> You're super active and delivered in time as said. Fab spirit you have got. 😊@Khushi-sharma07

Thank you mam for you praising words 😊. Your repository has really many opportunities for contribution in python.

**Comment by prathimacode-hub** [comment]
Welcome and thanks a lot Khushi. Glad to know you. This repo is always open for your contributions. If all of your PR's are merged, you can update in this [link](https://github.com/prathimacode-hub/Hacktober-Fest-2021/blob/main/CONTRIBUTORS.md)✔🙌 @Khushi-sharma07

**Comment by Khushi-sharma07** [comment]
Yes mam same here.....thank you😄

**Pull request merged**
