### PR TITLE
Rolling Dice game added

### PR DESCRIPTION
**Pull request by bindaldhara**
Info about the related issue
Title: Rolling Dice game
Name:Dhara Bindal
Label: Feature request

LGM-SOC'21 Participant

Closes: #396 

Changes I have made
Added a folder Rolling_Dice under the Pygame scripts folder
The folder contains the Rolling_Dice.py file which consist of code script.
It also has a README.md file which explains everything about the code.

Type of change:

[] Bug fix (non-breaking change which fixes an issue)
[x] New feature (non-breaking change which adds functionality)
[] Code style update (formatting, local variables)
[] Breaking change (fix or feature that would cause existing functionality to not work as expected)
[] This change requires a documentation update

Checklist:
My code follows the guidelines of this project.
 I have performed a self-review of my own code.
 I have added tests that prove my fix is effective or that my feature works.
 Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Follow the project structure and contributing guidelines. This is not a valid PR. There is a template to follow.  And also your project needs more files and format given. @bindaldhara

**Comment by bindaldhara** [comment]
Maam please review my request .. Anymore changes do I need to do ??

**Comment by Debashish-hub** [comment]
Please follow the folder structure @bindaldhara You can refer to the Contributing guidelines

**Comment by bindaldhara** [comment]
Am not able to change the folder name 
Please can u tell me how to do that

**Comment by prathimacode-hub** [comment]
> Am not able to change the folder name
> Please can u tell me how to do that

Do the changes in your forked repository and push the code again. There is project structure given, kindly follow it. @bindaldhara

**Comment by bindaldhara** [comment]
Is it fine now??

**Comment by Debashish-hub** [comment]
Add screen shots to an Images folder and also show them in readme @bindaldhara

**Comment by bindaldhara** [comment]
Added screenshots to README.md file
deleted same files as well

**Comment by bindaldhara** [comment]
Is it fine now??

**Comment by Debashish-hub** [comment]
Add images inside Images folder
Add the path of images from Images folder to the readme i.e. 'Images/imageName.png'
Add requirement.txt
Do comment your code wherever necessary

@bindaldhara

**Comment by bindaldhara** [comment]
Is it fine now??

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
The file name should be as "rolling_dice.py"
The requirements file should be as "requirements.txt"
Elaborate your README file. It should gave purpose, workflow and compilation steps. 

Kindly do this change. @bindaldhara

**Comment by bindaldhara** [comment]
Maam the file name of both are as same as told by u 
I have given the whole information in readme file. Can u suggest some points to include in that??

**Comment by prathimacode-hub** [comment]
> Maam the file name of both are as same as told by u
> I have given the whole information in readme file. Can u suggest some points to include in that??

Your README isn't in the right template. That's the reason I had mentioned things that weren't included. Purpose of the project, workflow of the project, compilation steps to execute and your name at the end of the file. Other than this, it's all good. @bindaldhara

**Comment by bindaldhara** [comment]
Anymore changes need to do maam??

**Review by prathimacode-hub — APPROVED** [review]
Perfect. Welcome to the repo officially. Good start. Keep contributing. Well done. Your PR is approved. 👏✨🎉@bindaldhara

**Comment by bindaldhara** [comment]
Thank uh maam

**Pull request merged**
