### PR TITLE
Add Knapsack problem on BasicPythonScript

### PR DESCRIPTION
**Pull request by danangharissetiawan**
# Knapsack Problem - #1002
The knapsack problem is a problem in combinatorial optimization: Given a set of items, each with a weight and a value, determine the number of each item to include in a collection so that the total weight is less than or equal to a given limit and the total value is as large as possible. It derives its name from the problem faced by someone who is constrained by a fixed-size knapsack and must fill it with the most valuable items. The problem often arises in resource allocation where the decision-makers have to choose from a set of non-divisible projects or tasks under a fixed budget or time constraint, respectively.

## Related Issue 

- Info about the related issue 
- #1002 

- [x] Hacktoberfest2021 Participant 
- [ ] Contributor

Closes: #issue number that will be closed through this PR
### Describe the changes you've made

A naive recursive implementation of 0-1 Knapsack Problem

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

- I have included the test-knapsack file with the unittest method for testing.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Kindly follow the guidelines and add proper PR template with issue details and issue number. First create an issue and get it assigned before you start working and create your PR. @danangharissetiawan

**Comment by danangharissetiawan** [comment]
> Kindly follow the guidelines and add proper PR template with issue details and issue number. First create an issue and get it assigned before you start working and create your PR. @danangharissetiawan

> Thank you, I have fixed it, is it acceptable?

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done :

Elaborate your README.md file. It needs more detailing, you can find readme template there.
Remove _init.py file
Add the output screenshot in "Images" folder
Also add the libraries used in "requirements.txt" file.

Kindly work on it. @danangharissetiawan

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Your README needs more elaboration.You can check up with the README template provided. @danangharissetiawan

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Welcome to repo officially. Yayy, you had done a great work. Keep it up. ✨🎉@danangharissetiawan

**Pull request merged**
