### PR TITLE
GUI based YouTube Video Downloader

### PR DESCRIPTION
**Pull request by chandu6111**
## Related Issue 

- Info about the related issue 
**Title**: GUI based Youtube Video Downloader in python
**Name**: Chandana (@chandu6111 )
**Label**: Feature Request
- [x] LGM-SOC'21 Participant 

Closes: #79 

### Changes I've made
- Added a folder **Youtube Video Downloader** under the **GUIScripts** folder.
The folder contains:
- youtube_video_downloader.py file (contains the main script for downloading)
- Readme.MD file (giving description of the project)
- requirements.txt file (contains requirements to be installed priorly)
- Images folder (contains screenshots)

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by chandu6111** [comment]
@prathimacode-hub please do review my PR once and let me know if any changes are required

**Review by Debashish-hub — CHANGES_REQUESTED** [review]
Add workflow and compilation steps in readme @chandu6111

**Comment by chandu6111** [comment]
@Debashish-hub and @prathimacode-hub 
is the readme okay now?

**Review by prathimacode-hub — APPROVED** [review]
Clean and Perfect. Outstanding work. Wow. Your efforts are seen through your PR's. 🙌🎊@chandu6111

**Comment by chandu6111** [comment]
You have been a major supporter of my open source journey @prathimacode-hub , Thank you so much! 👍

**Comment by prathimacode-hub** [comment]
> You have been a major supporter of my open source journey @prathimacode-hub , Thank you so much! 👍

My pleasure indeed and most welcome. 🤩@chandu6111

**Pull request merged**
