### PR TITLE
Added Code to Detect Lane from Image 

### PR DESCRIPTION
**Pull request by harshved**
## Related Issue 

- Info about the related issue 

- [ ] LGM-SOC'21 Participant 
- [x] DevIncept Participant
- [ ] Contributor

Closes: #123 

### Describe the changes you've made

Added the Code which detect Lane from the image and gives the output.
Note: If you use your image just set the area of interest as per the image to get better and perfect output.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how have you verified the changes made

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots
Detected Lane

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Follow the PR template, edit it and add the project details to check onto your PR. @harshved

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Needs changes to be done in project structure:
Images and output screenshots should be in "Images" folder
Readme file should be as README.md and it needs more elaboration. Lacks details on the project
The project file should be as "lane_detector.py"
Also a "requirements.txt" file which lists out all the libraries used in this project. 
Kindly do these changes. @harshved

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:
All images and output screenshots should be in "Images" folder
Also add compilation steps and purpose of the project in README.md

Kindly do these changes. @harshved

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Impressive and good take up. 👌👏@harshved

**Comment by prathimacode-hub** [comment]
Hey, I could see you haven't filled up the form yet with your PR link. Kindly do it to let your contribution count. Form is available in project channel of the slack. Do fill it up and let me know. I need to add your score. Do it by tomorrow evening as I have to send up the scores to DCP team. @harshved

**Comment by harshved** [comment]
Hey, I am done with the form.👍
Sorry I just forget to fill it out.

Regards, Harsh.

**Pull request merged**
