### PR TITLE
Binary Calculator GUI

### PR DESCRIPTION
**Pull request by manognyaa**
## Related Issue 
Binary Calculator GUI ✨✨
- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #515

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
Once, you download the code, it will work successfully 🙌.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:

gif 😃

screen-capture (8) (1)

overview 

overview

input 

input

output

output

| Updated Screenshot |

please guid eme mam, if any changes required mam

### CODE REVIEW

**Comment by manognyaa** [comment]
please guide me mam, if any changes required @prathimacode-hub mam.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done :

The project file should be titled as "binary_calculator.py"
Add appropriate comments in code wherever needed to get good understanding of the project.
The readme file should be titled as "README.md"
In "README.md", add aim, purpose, workflow, compilation steps.
In "README.md", the image links added up are in "user-images" content. Kindly add the file path for screenshots of overview, input and output like you did it for adding the link of "Images" folder.

Kindly do the needful changes. @manognyaa

**Comment by manognyaa** [comment]
> Changes to be done :
> 
> The project file should be titled as "binary_calculator.py"
> Add appropriate comments in code wherever needed to get good understanding of the project.
> The readme file should be titled as "README.md"
> In "README.md", add aim, purpose, workflow, compilation steps.
> In "README.md", the image links added up are in "user-images" content. Kindly add the file path for screenshots of overview, input and output like you did it for adding the link of "Images" folder.
> 
> Kindly do the needful changes. @manognyaa

Yes mam, thank you. I will be doing now @prathimacode-hub mam.

**Comment by manognyaa** [comment]
hello mam, i have updated the requirements. please guide me mam, if any changes required @prathimacode-hub mam.

**Comment by prathimacode-hub** [comment]
> hello mam, i have updated the requirements. please guide me mam, if any changes required @prathimacode-hub mam.

In "README.md", the image links added up are in "user-images" content. Kindly add the file path for screenshots of overview, input and output like you did it for adding the link of "Images" folder. This change isn't done yet. @manognyaa

**Review by prathimacode-hub — APPROVED** [review]
Hurray, your PR is approved. Fab dedication you had got. Congo. Good choice of project. 🎇🤩👌@manognyaa

**Pull request merged**
