### PR TITLE
Facts Generator added

### PR DESCRIPTION
**Pull request by pratimakush10**
Title: Facts Generator

LGM-SOC'21 Participant

Closes: #344 

Description : This script is the python program which generate random facts using python module **randfacts.**

Type of change
What sort of change have you made:
👍 New feature (non-breaking change which adds functionality)
Bug fix (non-breaking change which fixes an issue)
Code style update (formatting, local variables)
Breaking change (fix or feature that would cause existing functionality to not work as expected)
This change requires a documentation update

Checklist:
👍 My code follows the guidelines of this project.
👍 I have performed a self-review of my own code.
👍 I have commented my code, particularly where ever it was hard to understand.
I have made corresponding changes to the documentation.
👍My changes generate no new warnings.
I have added tests that prove my fix is effective or that my feature works.
Any dependent changes have been merged and published in downstream modules.

Output:
Output

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes needed :
Add pupose, description and complication steps of the project.
The requirements should be in "requirements.txt" file
Add appropriate comments in your code wherever needed.

Kindly do these changes. @pratimakush10

**Comment by pratimakush10** [comment]
Changes Updated please review @prathimacode-hub  mam

**Comment by prathimacode-hub** [comment]
> Changes Updated please review @prathimacode-hub mam

I cannot see your changes here.Kindly check if it's pushed properly. @pratimakush10

**Comment by pratimakush10** [comment]
Now, I have pushed the changed properly 
please review @prathimacode-hub mam

**Review by prathimacode-hub — APPROVED** [review]
Yes, now it looks perfect. Earlier, it didn't show up the changes. PR approved. Good to see you take up this issue. Impressive work. 🎇🙌@pratimakush10

**Pull request merged**
