### PR TITLE
Days Finder In A Month

### PR DESCRIPTION
**Pull request by Ashu-1309**
## Related Issue 

-Days Finder In A Month

- [x] LGM-SOC'21 Participant 
- [x] Contributor

Closes: #436 

### Describe the changes you've made

This is used to find the number of days in a month.

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested?

I tested the code in Online python compiler as well as in offline compiler.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly where ever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done :

Changes your project title as "Days Finder In A Month"
All images and screenshots should be in "Images" folder
You had added a earlier PR project file temperature converter here. Add project files for this project.
There is no "README.md" file here.

Kindly addressed these changes. @Ashu-1309

**Comment by Ashu-1309** [comment]
Okay I will do it

**Comment by Ashu-1309** [comment]
Do I have to  upload temperature converter here also ???

**Review by Ashu-1309 — COMMENTED** [review]
Retrieving temp_converter

**Comment by Ashu-1309** [comment]
It is not working properly can i closed this issue and start another one  ???

**Review by Ashu-1309 — COMMENTED** [review]
Trial of temp_converter

**Comment by prathimacode-hub** [comment]
> Do I have to upload temperature converter here also ???

Only upload the files related to your project. Your earlier project isn't needed here. @Ashu-1309

**Comment by prathimacode-hub** [comment]
> It is not working properly can i closed this issue and start another one ???

You should never close an issue or PR. Do changes asked for in your forked repository and repush your changes. @Ashu-1309

**Comment by Ashu-1309** [comment]
Untitled

**Comment by Ashu-1309** [comment]
I am getting this error what should I do know ??

**Comment by prathimacode-hub** [comment]
> I am getting this error what should I do know ??

First thing this repo is ahead of your forked repo. Kindly make that even. For that in your forked repository, select fetch upstream and make it updated. Then do it again. @Ashu-1309

**Comment by Ashu-1309** [comment]
Now can you please check that is it okay ??

**Comment by prathimacode-hub** [comment]
> Now can you please check that is it okay ??

What's happening. You had again created new PR? What should I take into consideration. There is no need to create new PR's for each changes. Just do the changes in your forked repository and push it again. It would by default show up the changes here. @Ashu-1309

**Comment by Ashu-1309** [comment]
What should I do Now ???
Please help me.

**Comment by prathimacode-hub** [comment]
> What should I do Now ???
> Please help me.

You want guidance? @Ashu-1309

**Comment by Ashu-1309** [comment]
Yes please guide me .

**Comment by prathimacode-hub** [comment]
> Yes please guide me . @prathimacode-hub

Ok, I will back at 10. I shall guide you briefly along with the link on how to create PR easier. @Ashu-1309

**Comment by Ashu-1309** [comment]
Okay , what I have to do now, ?? Will I have to close the PR that was mistakenly create @prathimacode-hub

**Comment by prathimacode-hub** [comment]
> Okay , what I have to do now, ?? Will I have to close the PR that was mistakenly create @prathimacode-hub

You don't close PR's, that we shall look after. I shall revert back with a link. Wait. @Ashu-1309

**Comment by Ashu-1309** [comment]
What are the Changes now required can you please suggest  me ???

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done :

Add appropriate comments in code wherever necessary to get good understanding of the project.
In README.md file add the image link of the output screenshot you added up in "Image" folder. It should be the file path not user-images content. The thing you had added is not a link. Check it out.
Add imported library of your project in "requirements.txt" file.

Kindly do these changes. @Ashu-1309

**Comment by Ashu-1309** [comment]
I have done all the required changes . Can you please crosscheck it .

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:

The requirements file should be titled as "requirements.txt"
In "README.md" file, the image link you added up is not a file path, it doesn't show up any visualization. Add the file path of the image present in "Images" folder. Don't add "user-images" content.
Add appropriate comments in your code wherever necessary to get good understanding of the project. 

Kindly do these changes. @Ashu-1309

**Comment by Ashu-1309** [comment]
All the required changes are done .

**Review by prathimacode-hub — APPROVED** [review]
Whoaaa, congrats. Your PR is approved. Good initiation and dedication. Keep growing. Well done. 🎊👌✨@Ashu-1309

**Comment by Ashu-1309** [comment]
Thank You 😁😁 @prathimacode-hub

**Pull request merged**
