### PR TITLE
issue #937 (Are You Pawned) added 

### PR DESCRIPTION
**Pull request by Developer-R-7**
## Related Issue #937 

- Making API request to ihavebeenpwned  to check if a password is pwned! or not

- [x] Hacktoberfest2021 Participant 
- [ ] Contributor

Closes: #937 

### Changes you've made

1. Added are_you_pawned.py (main file)
2. A user can take give input with password masked or without masked
3. Added a Images folder and the folder contains working screenshots of the program
4. Added requirements.txt file and README.md

## Type of change

What sort of change have you made:
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

This program is tested on windows PowerShell

## Checklist:
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots
`APIScripts/Have I Been Pawned/Images/`

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Hey, but issue wasn't assigned to you. First comment over the issue to get it assigned. I can then look over the PR. Also while getting assigned let me know if you are part of any open source program? 

Actually you have to work once issue is assigned to you. That's the workflow. @Developer-R-7

**Comment by Developer-R-7** [comment]
Sorry about it , I am new to open-source next time ,I will definitely get assigned then and follow the workflow of it.

**Comment by prathimacode-hub** [comment]
No worries. You can do it now also. Comment on the specified issue and get it assigned. Then i can check up your PR. @Developer-R-7

**Comment by Developer-R-7** [comment]
Thank you for guiding me about the workflow system and I have commented on the issue .

**Comment by prathimacode-hub** [comment]
Ok, I shall check it. @Developer-R-7

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done : 

Keep your project title as "Have I Been Pawned".  Also add a "requirements.txt" file with libraries imported and screenshots in "Images" folder.. @Developer-R-7

**Comment by prathimacode-hub** [comment]
> I have done the changes as mentioned :)

Also add a PR template in your comment above with the issue number and respective details. @Developer-R-7

**Comment by prathimacode-hub** [comment]
> > I have done the changes as mentioned :)
> 
> Also add a PR template in your comment above with the issue number and respective details so that I could merge it. @Developer-R-7

**Comment by Developer-R-7** [comment]
@prathimacode-hub I have edited the PR as per the PR template mention in the repo ,Thank You ,I have learned a lot form this

**Review by prathimacode-hub — APPROVED** [review]
This looks perfect. You're a quick learner. PR is approved. Great start. 👏✨@Developer-R-7

**Pull request merged**
