### PR TITLE
Weather Notifier Script

### PR DESCRIPTION
**Pull request by Komal-99**
## Related Issue 
#120 

- Info about the related issue 

- [X] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #120 

### Describe the changes you've made

Give a clear description what modifications you have made
Added REAME.md
Added requirements.txt
Added weather.py 
Added Images 

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how have you verified the changes made

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Update Screenshot|

image

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done

- Elaborate the README file
- You have a README template to follow in README file of the project.
- Add project title to your PR. Just adding PR title as "weather" won't say what your project is.
- This is a weather notifier script. The file name as well should be as weather_notifier.py

Kindly do the needful changes. @Komal-99

**Comment by Komal-99** [comment]
Okay template one i will do but I don't have content for readme.md  so shall i leave it that's it?

**Comment by prathimacode-hub** [comment]
> Okay template one i will do but I don't have content for readme.md so shall i leave it that's it?

Ok no issue. You can. Do the template one. @Komal-99

**Comment by Komal-99** [comment]
Done

**Comment by prathimacode-hub** [comment]
> Done

Check the above comment

**Comment by Komal-99** [comment]
> > Done
> 
> Check the above comment

yes i did and i have fulfill rest two points of editing name of PR and renaming .py file

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved and merged successfully. Finally, you did it. Congrats. Keep contributing. @Komal-99

**Comment by Komal-99** [comment]
> Your PR is approved and merged successfully. Finally, you did it. Congrats. Keep contributing. @Komal-99

yeah finally so now can i create new Issue for Covid bot which give notification about total cases recovered and deaths?

**Comment by prathimacode-hub** [comment]
Yes, finally you can. Is covid bot an automation script? @Komal-99

**Comment by Komal-99** [comment]
Yes 

> Yes, finally you can. Is covid bot an automation script? @Komal-99
Yes   similar to this one

**Comment by prathimacode-hub** [comment]
Ok, cool you can raise an issue stating the same using template. @Komal-99

**Pull request merged**
