### PR TITLE
Added Password Generator Game.

### PR DESCRIPTION
**Pull request by tjanhvi**
Info about the related issue
LGM-SOC'21 Participant

Closes: #569

Describe the changes you've made
Give a clear description what modifications you have made

Type of change
What sort of change have you made:

image

[x] Bug fix (non-breaking change which fixes an issue)
[x] New feature (non-breaking change which adds functionality)
[x] Code style update (formatting, local variables)
[x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
[x] This change requires a documentation update

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
This is not a game script and it should not come under "PyGamesScripts". Instead it shoud go under "BasicPythonScripts". @tjanhvi

**Comment by tjanhvi** [comment]
> This is not a game script and it should not come under "PyGamesScripts". Instead it shoud go under "BasicPythonScripts". @tjanhvi

okay.

**Review by prathimacode-hub — APPROVED** [review]
Impressive. Good going. I appreciate your efforts. 🙌🎊@tjanhvi

**Comment by tjanhvi** [comment]
> Impressive. Good going. I appreciate your efforts. 🙌🎊@tjanhvi

thankyou :)

**Pull request merged**
