### PR TITLE
Issue 70: Added python text translator

### PR DESCRIPTION
**Pull request by sherin527**
## Python Text Translator

- A python script for text translator with GUI using googletrans library of python

- [X] LGM-SOC'21 Participant 

Closes: #70

### Describe the changes you've made
It is a basic text translator written in python language using GUI, where the user can enter input of any language and get the desired output according to the user's desire. Here I have used googletrans library of python for text translation.
Also added an updated Readme file for the same.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
Successfully tested the source code in the local machine.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Updated Screenshot
demo1

@prathimacode-hub ma'am, kindly review this PR and if any changes required pls let me know.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Folder name should be "Images" not "images".
File name of readme file should be README.md.
README needs good elaboration. Add the workflow. Since this is a GUI script, it would have buttons to operate. Write it in step by step procedure. 
Add pre-requisites in requirements.txt file.
There is a README template in the README file of the project. Do follow that.  @sherin527

**Comment by sherin527** [comment]
ok ma'am

**Comment by prathimacode-hub** [comment]
README needs good elaboration. Add the workflow. Since this is a GUI script, it would have buttons to operate. Write it in step by step procedure. @sherin527

**Review by prathimacode-hub — COMMENTED** [review]
Official labels had come out. I would merge this PR with the labels once I clarify about it. So you are good to take up a new issue to work on. You had done a fab work.✔✨ @sherin527

**Comment by sherin527** [comment]
@prathimacode-hub ma'am. pls, check this once.

**Comment by sherin527** [comment]
Thank you @prathimacode-hub ma'am.

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved. 🎇@sherin527

**Pull request merged**
