### PR TITLE
Preview your link

### PR DESCRIPTION
**Pull request by manognyaa**
## Related Issue 
It is quite hard to find some information related to a given URL. So, i have created this issue. 
- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #373 

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
once you download the code, install the required librabies, then it will work successfully.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 Untitled | Updated Screenshot |

hello mam, please guide me, if any changes required @prathimacode-hub mam.

### CODE REVIEW

**Comment by Debashish-hub** [comment]
Add the images to an Images folder, and add the path of image in Image folder to readme i.e. 'Images/imageName.png'
@manognyaa

**Comment by manognyaa** [comment]
> Add the images to an Images folder, and add the path of image in Image folder to readme i.e. 'Images/imageName.png'
> @manognyaa

yes sir, I have added images to the images folder and uploaded the image path link to the readme file. 
please guide me sir, if any changes required @Debashish-hub sir

**Comment by Debashish-hub** [comment]
Add the path of your Images folder to your readme i.e. 'Images/imageName.png' @manognyaa

**Comment by manognyaa** [comment]
> Add the path of your Images folder to your readme i.e. 'Images/imageName.png' @manognyaa

yes sir, I have updated the readme file. Thank you for your co-operation sir.
please guide me, if any changes required  @Debashish-hub sir.

**Comment by Debashish-hub** [comment]
Replace the githubuser content link with 'Images/preview.png' in your readme @manognyaa

**Comment by manognyaa** [comment]
now is it fine sir @Debashish-hub sir

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
The project file name should be titled as "link_preview.py".

Do this change. @manognyaa

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved. Whooa, you had shown a good rise in your level of issue. That sounds awesome. Fab turnover it was from you to see ur growth. Crystal Clear. Keep shining. 👌👌👌@manognyaa

**Pull request merged**
