### PR TITLE
I love you in python

### PR DESCRIPTION
**Pull request by manognyaa**
## Related Issue 

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

Closes: #648 

### Describe the changes you've made
I made project wherein the cursor itself will write `I love you`  and after writing the 3 words, it will draw a love symbol.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Once, you download the code, it will run successfully.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 
gif link : https://github.com/manognyaa/Awesome_Python_Scripts/blob/main/GUIScripts/love/Images/screen-capture%20(11)%20(1).gif
screen-capture (11) (1)

initial stage  link : https://github.com/manognyaa/Awesome_Python_Scripts/blob/main/GUIScripts/love/Images/initial.png
initial

last stage link : https://github.com/manognyaa/Awesome_Python_Scripts/blob/main/GUIScripts/love/Images/end.png
end
 | Updated Screenshot |

### CODE REVIEW

**Comment by manognyaa** [comment]
Hello mam, I made a pr.
 Please review and guide me if any changes required @prathimacode-hub  mam.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
The project folder should be as "Message - I Love You". Other than this, all perfect. Kidnly do these changes. @manognyaa

**Comment by manognyaa** [comment]
okay mam. thank you @prathimacode-hub mam. one minute

**Comment by manognyaa** [comment]
yes mam, i have named the folder as "Message- I Love You ".  is it okay @prathimacode-hub  mam ?

**Review by Debashish-hub — CHANGES_REQUESTED** [review]
Replace the githubusercontent links of images with image path in the readme i.e. 'Images/imageName.png'
 @manognyaa

**Comment by manognyaa** [comment]
yes sir, I have replaced the image path in the readme file. Please guide me if any changes are required @Debashish-hub sir.

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved. Great going. Keep rocking like this.  🤩👌@manognyaa

**Pull request merged**
