### PR TITLE
Added Enhanced Version of Registration Form using Tkinter 

### PR DESCRIPTION
**Pull request by thejaswin123**
## Related Issue 

Added Enhanced Version of Registration Form using Tkinter 

- [ ] LGM-SOC'21 Participant 
- [x] DevIncept Participant
- [x] Contributor

Closes: #700 

### Describe the changes you've made

To Build Registration form using tKinter and SQlite3
User has the option to store the details store in database and also to view the database.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

The program is run multiple times and is tested for any bugs.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Follow the project structure given in README file of the project.
And also in README, don't write one line answers. Explain briefly, more elaboraiton is required. 
It's not in right project structure.
@thejaswin123

**Comment by thejaswin123** [comment]
> Follow the project structure given in README file of the project.
> And also in README, don't write one line answers. Explain briefly, more elaboraiton is required.
> It's not in right project structure.
> @thejaswin123

Changes made to maintain project structure

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Only change it needs, add workflow of the project in README.md file @thejaswin123

**Comment by thejaswin123** [comment]
> Only change it needs, add workflow of the project in README.md file @thejaswin123

Workflow of the project is now added.

**Review by prathimacode-hub — APPROVED** [review]
Impressive work. Great start. Welcome to repo officially. Congrats on your first PR. Yayy. Your PR is approved. 🎉✨👏@thejaswin123

**Comment by prathimacode-hub** [comment]
Kindly fill the form with your PR link. Your response hasn't turned up yet. Form is available in slack project channel. @thejaswin123

**Comment by thejaswin123** [comment]
> Kindly fill the form with your PR link. Your response hasn't turned up yet. Form is available in slack project channel. @thejaswin123

Filled the form, kindly please check.

**Comment by prathimacode-hub** [comment]
You have to fill the form again, as the form is updated. It's provided in project channel at slack. Kindly refill it again. @thejaswin123

**Comment by prathimacode-hub** [comment]
Yes, got your responses now. Cool. @thejaswin123

**Pull request merged**
