### PR TITLE
BMI Calculator GUI

### PR DESCRIPTION
**Pull request by Khushi-sharma07**
Description:
Here with the help of tkinter module I had designed a helpful system for calculating the Body Mass Index Ratio. The user will enter his/her age, gender, height(in cm) and weight(in kg). The system will calculate and show the BMI of the person and will also tell that the person is underweight, healthy or overweight.

- [x] LGM-SOC'21 Participant
- [ ] Contributor

Closes: #420 

Types Of Changes
What sort of changes have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly where ever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

Screenshots:
INPUT SCREEN
InputScreen

OUTPUT SCREEN:
CalculatedValue

### CODE REVIEW

**Comment by Debashish-hub** [comment]
Add screenshots to your readme with the path as  'Media/ImageName.png'
Do comment your code wherever necessary
Add a requirements.txt fiel

@Khushi-sharma07

**Comment by Khushi-sharma07** [comment]
Mam I had added comments in the project are there any more needed? 
I had defined almost every function which I thought is required.

I will update the README file also with more description.

**Review by prathimacode-hub — APPROVED** [review]
Yayy. You had nailed it. Picture perfect. Amazing work. Huge applause for you. Your PR is approved. Wonderful choice of the script. Kudos.  👌🎉✨

**Comment by Khushi-sharma07** [comment]
Thank you mam!☺️

**Pull request merged**
