### PR TITLE
All Information About Country

### PR DESCRIPTION
**Pull request by neelshah2409**
Title: All Information About Country

Description :Here by using the python script we can get all the information about any country by using countryinfo library and getting capital , border, currency ,area ,time zone ,population and all the things.

- [x] LGM-SOC'21 Participant
 - [ ] Contributor

Closes: #233 

Type of change
What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
 - [ ] Code style update (formatting, local variables)
 - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [ ] This change requires a documentation update

Checklist:
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly where ever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
 - [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ]  Any dependent changes have been merged and published in downstream modules.

Screenshots
Input :
input_1(country)
input_2(country)

Output :  
output(country)

### CODE REVIEW

**Review by prathimacode-hub — APPROVED** [review]
Can you suggest a different title for your project. @neelshah2409

**Comment by neelshah2409** [comment]
Country Detailer or mam you can tell any other or it is fine with this only.

**Comment by prathimacode-hub** [comment]
> Country Detailer or mam you can tell any other or it is fine with this only.

Country Notifier @neelshah2409

**Comment by neelshah2409** [comment]
Mam I had changed the folder name and added here , it is needed to make another PR or it is fine.

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved. Good to see your enthusiasm. 😎@neelshah2409

**Pull request merged**
