### PR TITLE
Hotel Management System

### PR DESCRIPTION
**Pull request by rammya29**
## Related Issue 

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

Closes: #701 

### Describe the changes you've made

It has a features like check-in , check-out, information bout guests, list of guests in the hotel and exit operation are available in the code. It created by the python scripts using tkinter for GUI application

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

The code is tested in the idle environment.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
You had enabled both, LGMSOC and Devincept. You can select ony 1 out of it
@rammya29

**Comment by rammya29** [comment]
I choose LGMSOC

**Comment by rammya29** [comment]
If there are no faults please merge it mam. If i create new folder it shows merge conflicts.

**Review by Debashish-hub — APPROVED** [review]
PR  is approved @rammya29

**Review by prathimacode-hub — COMMENTED** [review]
Just saw this PR. It's well executed project. You're rocking. 🎇✔@rammya29

**Pull request merged**
