### PR TITLE
Added All Indian Trains in GUIScripts

### PR DESCRIPTION
**Pull request by akash435**
## Related Issue 

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

fixes : #519
Closes: #519

### Describe the changes you've made
- A "All Indian Trains" is an application created in python with tkinter gui.
- In this application, user can get the information about how many trains are there in India with given Train Name.
- Along with that, this scripts also gives us details about Train No., Starting Junction and Ending Junction of each train with same Train Name.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

yes , below i have provided the a screenshots and video link for showing how it works. and video of its working also.

## Checklist:

- [x] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |

### CODE REVIEW

**Review by Debashish-hub — APPROVED** [review]
Good work @akash435  Your PR is approved

**Review by prathimacode-hub — COMMENTED** [review]
As usual, spot on. Choice of your scripts are always well needed and creative. Firecracker. 😊🧨@akash435

**Comment by prathimacode-hub** [comment]
Scores are now upto date. It's updated. As mentioned, it's already said scores would be updated once in 4 days. If you don't find your scores added up, it means that isn't included yet. And one more thing, to know if scores are included or not, we had added a separate label to PR's to know pending scores that aren't counted. You can check out through that way. Any queries, you can ask. @akash435

**Comment by akash435** [comment]
ok thanks mam.

**Pull request merged**
