### PR TITLE
Added Twitter API

### PR DESCRIPTION
**Pull request by pragyakhanna11**
# Twitter API
- Extract tweets based on username or keyword

------------

- [x] LGM-SOC Participant

Closes: #68
## Describe the changes made:
- Added the code for the twitter API
- Added the Readme file for the same

## Type of change:
- [x] New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done :

- File name should be in .py format. 
- File name should be in snake case (twitter_api.py)
- README.md needs little more elaboration on descriptive part. Also add how did you compile the script. 
- Also add comments in .py file whenever needed to get better vision of the program file.
That would helps user understand better.

Do the needful changes. @pragyakhanna11

**Review by prathimacode-hub — COMMENTED** [review]
As I said earlier, README should be elaborative. You had added purpose, workflow, screenshot and libraries. Also include how the script can be compiled. In set up instructions, you had mentioned about account, mounting the google drive and run the code. Brief how you can run the code. What you do in command line? @pragyakhanna11

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
In twitter_api.py file, you hadn't modified the file name inside the program file. @pragyakhanna11

**Comment by prathimacode-hub** [comment]
Thanks for rectifying the changes. Official labels would come out at noon. So you are good to take up a new issue to work on. I shall merge this PR, when official labels are tagged to this PR. @pragyakhanna11

**Comment by prathimacode-hub** [comment]
You had done a wonderful job. 👏✨ @pragyakhanna11

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Hey, @pragyakhanna11 In README.md file, the output screenshot, you had directed it to other source. Can you put up this screenshot in "Images" folder in your project and push the code again

**Comment by pragyakhanna11** [comment]
@prathimacode-hub Please check

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved 🎇@pragyakhanna11

**Pull request merged**
