### PR TITLE
Typing Speed Test

### PR DESCRIPTION
**Pull request by neelshah2409**
Title:   Typing Speed Test
  

-> LGM-SOC'21 Participant
      Contributor
  

Closes: #71

**Description** :There are 3 methods define in the program one to find error , speed and time .So here we use time library for getting the starting and ending time.
For finding the error we will split each word and then check if any word is missing or not. For finding the speed we will get length of the correct word and then dividing it by time taken.

Type of change
What sort of change have you made:

 -> New feature (non-breaking change which adds functionality)
      Bug fix (non-breaking change which fixes an issue)
      Code style update (formatting, local variables)
      Breaking change (fix or feature that would cause existing functionality to not work as expected)
      This change requires a documentation update

Checklist:
-> My code follows the guidelines of this project.
-> I have performed a self-review of my own code.
-> I have commented my code, particularly where ever it was hard to understand.
     I have made corresponding changes to the documentation.
-> My changes generate no new warnings.
     I have added tests that prove my fix is effective or that my feature works.
     Any dependent changes have been merged and published in downstream modules.

Screenshots
| col 1      | col 2      |
|------------|-------------|
| image 1 | image 2 |
 

Result_1
Result_2

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done 

- Follow the project structure mentioned in the README file of the project.
- README file should be elaborative, you can find the template in README file of the project.
- The file name should be "requirements.txt" not "Requirements.txt".
- All the images and screenshots should be in "Images" folder.
- Along the the detailed README, screenshot inclusion is must in this file.

Do the needful changes. @neelshah2409

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
In a program file, kindly add comments wherever need to get good understanding of the script. @neelshah2409

**Review by prathimacode-hub — COMMENTED** [review]
Typo error in 2nd line of program file. Do the change. And Thanks for rectifying the changes. Official labels had come. So you are good to take up a new issue to work on. I shall merge this PR very soon. @neelshah2409

**Comment by prathimacode-hub** [comment]
You had done an amazing work. ✨👏 @neelshah2409

**Comment by neelshah2409** [comment]
Thank you so much mam and also a great thank to you mam as I was doing for the first time and you helped a lot mam.

**Comment by prathimacode-hub** [comment]
You're a quick learner. Can't wait to see your next creative issue coming from you. Well done @neelshah2409

**Review by prathimacode-hub — COMMENTED** [review]
Hey, raise a seperate PR for Caesar Encryption using template mentioned. Else you won't get points. Combining both projects would fetch only points for single project. Remove these caesar encryption files from this PR and create a new one. All the best. @neelshah2409

**Comment by neelshah2409** [comment]
Mam please guide me how to remove this files from this pr and also I was not able to make another pr so please help me

**Comment by prathimacode-hub** [comment]
Just go to my forked repository in your system. And delete the files regarding caesar encryption.  Now push the changes to my repo. Then those files won't be shown up while merging. Last, I shall merge the PR now with level tag for time being.  Once I get a final call from LGM, i shall assign the perfect tag. @neelshah2409

**Comment by prathimacode-hub** [comment]
Are you able to do it? @neelshah2409

**Comment by neelshah2409** [comment]
Mam now please merge this ,so I could have a new PR.

**Review by prathimacode-hub — APPROVED** [review]
Perfect. I shall merge this PR now. Kudos to you. 🎇@neelshah2409

**Pull request merged**
