### PR TITLE
Acronym Of The Word

### PR DESCRIPTION
**Pull request by Khushi-sharma07**
Description: It is a basic Python Script which will simply give you the acronym of the word entered i.e; the initials of the words entered. Eg: Artificial Intelligence will give output as AI.

- [x] LGM-SOC'21 Participant
- [ ] Contributor

Closes: #488 

Type of change
What sort of change have you made:

- [ ]  Bug fix (non-breaking change which fixes an issue)
- [x]  New feature (non-breaking change which adds functionality)
- [ ]  Code style update (formatting, local variables)
- [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ]  This change requires a documentation update

Checklist:

- [x]  My code follows the guidelines of this project.
- [x]  I have performed a self-review of my own code.
- [x]  I have commented my code, particularly where ever it was hard to understand.
- [ ]  I have made corresponding changes to the documentation.
- [x]  My changes generate no new warnings.
- [ ]  I have added tests that prove my fix is effective or that my feature works.
- [ ]  Any dependent changes have been merged and published in downstream modules. 

Screenshot Of Output:
Output

### CODE REVIEW

**Review by Debashish-hub — CHANGES_REQUESTED** [review]
Add purpose, workflow in the "README.md" , be more elaborative.
Rename your python file to 'acronym_of_the_word.py'

Do these changes @Khushi-sharma07

**Review by Debashish-hub — APPROVED** [review]
Congrats! Your PR is approved @Khushi-sharma07

**Review by prathimacode-hub — APPROVED** [review]
Good job @Khushi-sharma07. Well done. Keep it up. Welcome to the repo officially. Yayy. Your PR is approved. ✨👏

**Comment by Khushi-sharma07** [comment]
Thank you mam and sir 😊

**Pull request merged**
