### PR TITLE
Backup WhatsApp Chats To Excel Sheet 

### PR DESCRIPTION
**Pull request by Iamtripathisatyam**
- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #210 

### Describe the changes you've made
Create a WhatsApp Backup Chats using some major libraries like **pandas**, **pushbullet**, **OS**, and **requests**.

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
This code has been tried on my local machine.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots
Output

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
The project folder title should be as "WhatsApp Backup To Excel" and file name as "whatsapp.py"

Kindly do this change. @Iamtripathisatyam

**Comment by Debashish-hub** [comment]
Add the link of the image from image folder in the readme i.e. 'Images/imageName'  @Iamtripathisatyam

**Comment by Iamtripathisatyam** [comment]
Sir If I'll add a link to the image in the PR, then it will not show any image, and till I am just doing this thing in my all projects.

**Comment by Iamtripathisatyam** [comment]
Please reply something

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved and merged. Congo. Good selection of project and very well showcased. 👌🎇@Iamtripathisatyam

**Comment by Iamtripathisatyam** [comment]
Thank you so much ma'am

**Pull request merged**
