### PR TITLE
Temperature Converter

### PR DESCRIPTION
**Pull request by Ashu-1309**
## Related Issue 

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #333 

### Describe the changes you've made
This is calculator that is used to convert Celsius into Fahrenheit  and Vice versa.

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
it is tested to Pycharm and it is working fine and gave the desired result . 

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly where ever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots
Temp

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Why had you closed it? @Ashu-1309

**Comment by Ashu-1309** [comment]
By mistake I did that

**Comment by prathimacode-hub** [comment]
> By mistake I did that

Ok, no issue. But you shouldn't do this again. Kindly follow the project structure and do the changes and add up all the related files to your project. @Ashu-1309

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Plz do the changes
This is not the right format
Every project should have a project file, README file, requirements file and output screenshots placed in images folder. This is the project structure of the basic projects.
Always follow the README and CONTRIBUTING GUIDELINES of the project.
This is how you learn and grow.

Let's help you out with the changes to be done:

The project folder should be titled as "Temperature Converter"
Add all the images and output screenshots in "Images" folder
Add a "README.md" file about the project and describe it all. There is a template of 'README' file that's enclosed in README file of this repo. README should always be elaborative and expressive.
In project file, add appropriate comments wherever necessary to get gopd understanding of the project.
We're not adding "requirements.txt" file as there are no libraries included in this project. 

Kindly do the needful changes.  Any queries, don't hesitate to ask. @Ashu-1309

**Comment by Ashu-1309** [comment]
I will update the Readme file as early as possible.

**Comment by Ashu-1309** [comment]
@prathimacode-hub ,Can you please cross check that I have uploaded  Readme file and images related to program.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:

The project folder should be titled as " Temperature Converter"
The images and screenshots should be in "Images" folder
And the image link in 'README.md file' should be of image file path present in this repo, not user-images content.
Add the PR template in your PR commit message along with your issue number. 

Kindly do these changes. @Ashu-1309

**Comment by Ashu-1309** [comment]
Added Readme file along with image link and changed the file name to Temperature  Converter.

**Comment by Ashu-1309** [comment]
How I can add PR template?
what will be its extension ?

**Comment by prathimacode-hub** [comment]
> How I can add PR template?
> what will be its extension ?

There is a PR template to be be followed in README file of the project. You can add that template in your PR commit message along with your issue number and modifications according to your project. This doesn't go into your repo neither it doesn't have any extension. It's just a message to be added up to get you counted under LGMSOC. 👍@Ashu-1309

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:

The project folder should be titled as " Temperature Converter"
The images and screenshots should be in "Images" folder
And the image link in 'README.md file' should be of image file path present in this repo, not user-images content.
Correct the spelling of your project title.
Remove the old files from this repo. 
Add aim, purpose, workflow and compilation steps in your 'README.md' file
Add the PR template in your PR commit message along with your issue number.

Kindly do these changes. @Ashu-1309

**Comment by Ashu-1309** [comment]
Now, is it okay ??

**Comment by prathimacode-hub** [comment]
> Now, is it okay ??

You hadn't done all the changes requested. Kindly do that. @Ashu-1309

**Comment by Ashu-1309** [comment]
I add aim , purpose ,workflow and compilation steps.

**Comment by Ashu-1309** [comment]
Do have to do more changes rather than that ??

**Comment by prathimacode-hub** [comment]
> Do have to do more changes rather than that ??

These are the changes, do check if you had missed something. Bcoz I could lots of changes not done yet. 

Changes to be done:

The project folder should be titled as " Temperature Converter"
The images and screenshots should be in "Images" folder
And the image link in 'README.md file' should be of image file path present in this repo, not user-images content.
Correct the spelling of your project title.
Remove the old files from this repo.
Add aim, purpose, workflow and compilation steps in your 'README.md' file
Add the PR template in your PR commit message along with your issue number.

Kindly do these changes.  @Ashu-1309

**Comment by Ashu-1309** [comment]
All the Changes are done .

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
A small change. In README.md file, the image link you had added should be the file path of an image you provided in this repo. Not an 'user-images' content. @Ashu-1309

**Comment by Ashu-1309** [comment]
Changes are done . Can you please cross check .

**Review by prathimacode-hub — APPROVED** [review]
Looks clean. Welcome to the repo officially. Yayy. Good work. Your PR is approved. Well done. 👌✨🎉@Ashu-1309

**Comment by Ashu-1309** [comment]
Thanks you ☺️☺️

**Pull request merged**
