### PR TITLE
Earthquakes

### PR DESCRIPTION
**Pull request by RandallWert**
Hi, thanks for all your help. I hope I did this right!

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Small correction needed :

Folder Name should be titled as "Earthquake API".

Others are perfectly done. @RandallWert

**Comment by RandallWert** [comment]
OK, I recreated the folder under the specified name of "Earthquake API".

**Review by prathimacode-hub — APPROVED** [review]
Thanks for opening this pull request!🤗 


Congrats on merging your first PR. Welcome to this repository by being a first official contributor. 🎉🎉

It was a wonderful initiation from you to contribute. Keep doing the great work.👍

Do ✨this repository, if it helped you in contributing to open source and added you a green square.

Are you looking for more beginner-friendly issues? Check out this [repo](https://github.com/prathimacode-hub/HelloWorld).

**Comment by RandallWert** [comment]
Thank you! I will definitely star it.

Is it OK to delete my Earthquakes branch, or do you do that?

I will also try to contribute a Thesaurus API. Let's see if I can do it more smoothly this time :)

**Comment by RandallWert** [comment]
OK, I deleted the branch. I think I will delete my fork and start the whole process over again, just to learn it better.

Thanks again!

**Comment by prathimacode-hub** [comment]
That's great to see your spirit. 👍@RandallWert

**Pull request merged**
