### PR TITLE
Added Solar System Objects Details in Python Scripts

### PR DESCRIPTION
**Pull request by akash435**
## Related Issue 

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

fixes : #527
Closes: #527

### Describe the changes you've made
- A "Solar System Object Details" created in python with tkinter gui.
- In this script, the user will be able select any object from 24 solar system object listed in drop down OptionMenu, cna can get the details about it.
- Also the details will be in terms of 1.)  Radius (km), 2.)  Mass (10e24 kg), 3.)  Density (g/cm3), 4.)  Gravity (m/s2), 5.)  Semi-major axis (km), 6.)  Orbital period (days), 7.)  Type (either planet, moon or star), 8.)  Moon of which planet (if its a moon), 9.)  Year of discovery, 10.)  Position n solar system.
- Along with this details, also user will be able to see the images of each solar system object.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

yes , below i have provided the a screenshots and video link for showing how it works. and video of its working also.

## Checklist:

- [x] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Add your name at end of the README file
Add appropriate comments in your code wherever necessary. @akash435

**Comment by akash435** [comment]
@prathimacode-hub , done the requested changes

**Review by Debashish-hub — APPROVED** [review]
Great! Your PR is approved @akash435

**Review by prathimacode-hub — APPROVED** [review]
Exceptional Work. 🎇@akash435

**Pull request merged**
