### PR TITLE
Voice Calculator

### PR DESCRIPTION
**Pull request by Khushi-sharma07**
Related Issue
A Python script to generate the calculator which work on voice commands.

- [x] Hacktoberfest2021 Participant
- [x]  Contributor

Closes: #927  

Describe the changes you've made
Added required files as per the requirement of Voice Calculator generation.

Type of change
What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

How Has This Been Tested?
Tested the script on my local machine for different test cases.

Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

Screenshots:

Screenshot (121)

### CODE REVIEW

**Comment by Khushi-sharma07** [comment]
Mam please review my code.😊

**Comment by Khushi-sharma07** [comment]
Mam please review the p.r 🙏 @prathimacode-hub

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
README can elaborated briefly. @Khushi-sharma07

**Review by Khushi-sharma07 — COMMENTED** [review]
Mam I had tried to add more details in the README.md file, I am not getting anymore ideas to add in this as it is a simple GUI script.

**Review by prathimacode-hub — APPROVED** [review]
PR approved. 👏👌@Khushi-sharma07

**Comment by Khushi-sharma07** [comment]
Thank you mam

**Pull request merged**
