### PR TITLE
ADDED THE CODE FOR MEMORY_PUZZLE_GAME (issue-231)

### PR DESCRIPTION
**Pull request by HitainKakkar**
## Related Issue 

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [x] Contributor

Closes: #231 
### Describe the add-ons or changes you've made
For this I have prepared 3 python files for the main code/analysis and a few picture for dataset.

### MEMORY_PUZZLE_GAME

- The program runs a memory game that allows you to turn over cards by clicking the mouse.
- Each grey box represents the image of an animal hidden by default.
- If there is a match, the two cards will disappear, leaving a blank white space and giving a message "MATCHED". 
- If not, they will flip back over.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how it has been tested
Describe how have you verified the changes made

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by Debashish-hub — CHANGES_REQUESTED** [review]
Why you have created Dataset and Model folders? If they are necessary then keep your README file outside Model folder i.e. just inside Memory Puzzle Game folder. @HitainKakkar

**Comment by HitainKakkar** [comment]
Kindly read the instructions given in #457.
It is mentioned that I have to make dataset and model folders.
Also when when my last PR was merged I was told to keep the readme file in the model folder.

**Comment by Debashish-hub** [comment]
> Kindly read the instructions given in #457.
> It is mentioned that I have to make dataset and model folders.
> Also when when my last PR was merged I was told to keep the readme file in the model folder.

First of all Don't create multiple PRs for a single issue and Read the instructions again given in #457

**Comment by prathimacode-hub** [comment]
> Kindly read the instructions given in #457.
> It is mentioned that I have to make dataset and model folders.
> Also when when my last PR was merged I was told to keep the readme file in the model folder.

I guess you got confused, but that was other project you're mentioning. This project is different. Every project has own set of contributing guidelines. This is completely different from other project you just mentioned. So those guidelines aren't appropriate in this project. Here in README.md file, project structure is clearly mentioned.  @HitainKakkar

**Comment by prathimacode-hub** [comment]
Follow the project structure given here. This is not a similar repo to your earlier PR. These are the changes to be done from your end.

Changes to be done :

The project folder should be titled as "Memory Puzzle Game"
There are no such folders of "Dataset" and "Model" here
The images and screenshots of your project should be in "Images" folder
Add the libraries imported in your project in "requirements.txt" file
The app.py, animal.py and game_config.py should be directly uploaded in "Memory Puzzle Game"
Add appropriate comments in your code wherever necessary to get good understanding of the project.
There is a separate README.md template present in README file of the project. This is not the format. It should have aim, purpose, description, workflow, compilation steps, output screenshots and your name at the end of the file.
And the image links you add up in your README file should be a file path of the images present in this repo, not user-images content.

Kindly do the changes needed. @HitainKakkar

**Comment by Debashish-hub** [comment]
Hey! @HitainKakkar Please give updates about your work.

**Comment by HitainKakkar** [comment]
Will update soon!!
My exams are going on!!

**Comment by prathimacode-hub** [comment]
Are your exams not finished yet? @HitainKakkar

**Comment by HitainKakkar** [comment]
Yes!!
I am resuming the work on it!!

**Pull request closed without merging**
