### PR TITLE
Face Lock Open CV

### PR DESCRIPTION
**Pull request by TusharAMD**
## Related Issue 

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

Closes: #254 

### Describe the changes you've made

Give a clear description what modifications you have made

I have made a screen lock application using python, OpenCV, and Tkinter. The script can display the lock screen, disable the mouse and keyboard temporarily, and also play music in background till user unlocks it using face detection. Demo can be found here https://www.youtube.com/watch?v=PjGLWq3LrhM&ab_channel=TusharAmdoskar

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how have you verified the changes made
I have tried to detect multiple faces and it worked successfully everytime

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly whereever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |

### CODE REVIEW

**Review by Debashish-hub — CHANGES_REQUESTED** [review]
Follow proper folder structure. Keep all images in an Images folder and link it to readme @TusharAMD

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
In your project files, add appropriates comments in code wherever needed to get good understanding of the project. Others are perfect. @TusharAMD

**Comment by prathimacode-hub** [comment]
Also change the PR title to your Project Name. @TusharAMD

**Comment by TusharAMD** [comment]
Added comments and changed title

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved. Outstanding work. Welcome to the repo oficially. Congrats. Yayy. ✨🎉👏@TusharAMD

**Pull request merged**
