### PR TITLE
Reddit Video Downloader

### PR DESCRIPTION
**Pull request by Akash20x**
## Reddit Video Downloader

- This is a python script which will download the video of the post in reddit by asking user url of page of the post .
- Display post title,subreddit and author name on the console.
- The video is stored in our local system as download.mp4

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #631 

### Describe the changes you've made

Give a clear description what modifications you have made

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

I tested this application on my local system and perfectly works fine and also provided its screenshots.
## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |

output

### CODE REVIEW

**Review by Debashish-hub — CHANGES_REQUESTED** [review]
Be more elaborative in the README @Akash20x 
add aim, purpose, worfklow of the project and compilation steps.

**Comment by Akash20x** [comment]
> Be more elaborative in the README @Akash20x
> add aim, purpose, worfklow of the project and compilation steps.

OK

**Comment by Akash20x** [comment]
@Debashish-hub Please check my pull request

**Comment by Akash20x** [comment]
@Debashish-hub Please check my pull request

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved. Congo. Keep rocking. Good choice of script. Well done. 🎇🙌@Akash20x

**Pull request merged**
