### PR TITLE
Wifi Password Fetcher

### PR DESCRIPTION
**Pull request by neelshah2409**
Wifi Password Fetcher

Info about the related issue

- [x] LGM-SOC'21 Participant
- [ ] Contributor

Closes: #338 

 Description :We will get all the wifi passwords from the device using the subprocess library and its function and copying to our clipboard using pyperclip.

Type of change
What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x]  New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
 - [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
 - [ ] This change requires a documentation update

Checklist:
- [x]  My code follows the guidelines of this project.
 - [x] I have performed a self-review of my own code.
 - [x] I have commented my code, particularly where ever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
 - [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

Screenshots:
output_1(wifi)
output_2(wifi)

### CODE REVIEW

**Comment by Debashish-hub** [comment]
Add the images in readme from your Image folder i.e. the links should be 'Images/imageName'
No need of readme inside image folder
Do these changes @neelshah2409

**Comment by neelshah2409** [comment]
@Debashish-hub sir I am not getting the proper link of images folder as I am a beginner so sir please guide me or else it will be fine .
@prathimacode-hub  Mam please see this.

**Comment by Debashish-hub** [comment]
Just replace this link (https://user-images.githubusercontent.com/71593494/122568292-3ab3c180-d067-11eb-973d-908a1ca3cf91.png)  with (Images/ImageName.png) in the readme @neelshah2409

**Comment by neelshah2409** [comment]
@Debashish-hub Sir thank you for helping I had done changes.

**Comment by Debashish-hub** [comment]
You have not done it @neelshah2409  Just have a look at the following link, how the screenshot has been added
https://github.com/prathimacode-hub/Awesome_Python_Scripts/pull/340/files#diff-2706130f9313218060767ea20f52ab8bbfd2ad99b0ab26ae7d84c35ea6a47f43

**Comment by neelshah2409** [comment]
@Debashish-hub Sir done please review it.

**Comment by Debashish-hub** [comment]
You need to replace the githubusercontent link ( the link you have used for image in readme) with (Image/output_1(wifi).png) @neelshah2409

**Comment by neelshah2409** [comment]
@Debashish-hub Sir I had done up to my capabilities , please see it and sorry but I am not getting the proper way so sir kindly approve this PR so I can go for another issue.
@prathimacode-hub Mam kindly see this.

**Comment by Debashish-hub** [comment]
> @Debashish-hub Sir I had done up to my capabilities , please see it and sorry but I am not getting the proper way so sir kindly approve this PR so I can go for another issue.
> @prathimacode-hub Mam kindly see this.

You have not done any changes @neelshah2409  If you are not getting it then just message me on slack

**Comment by Debashish-hub** [comment]
Congratulations @neelshah2409  Your PR is approved. Great work
It will be merged soon

**Pull request merged**
