### PR TITLE
Added Chess Game

### PR DESCRIPTION
**Pull request by sahilsingh2402**
## Related Issue

- Added Chess Game

- [x] LGM-SOC'21 Participant
- [ ] Contributor

Closes: #306 

### Describe the changes you've made

It is a CLI based memory efficient chess game which uses only a single library 'itertools'. It is a two player game, where both the players get their turns iteratively.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

I have played this game many times and tested all possible corner cases where the code could break.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots
output

### CODE REVIEW

**Comment by sahilsingh2402** [comment]
@prathimacode-hub Please review this.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done :

The README.md file should be elaborative. Add purpose, workflow of your program and your name at the end of the file
The project file should be titled as "chess_game.py"
Add appropriate comments wherever necessary in your code to get good understanding of the project. 
Add "requirements.txt" file with libraries imported in your program.

Kindly do these needful changes. Always follow the project structure given in README file of this repo. @sahilsingh2402

**Comment by sahilsingh2402** [comment]
I have made the required changes. Please review it. @prathimacode-hub

**Review by Debashish-hub — APPROVED** [review]

**Review by prathimacode-hub — APPROVED** [review]
Good job. Perfect and clean. Wonderful choice of the script. Good going. Keep it up. Welcome to the repo officially.  Congrats. Your PR is approved. ✨🎉🏷@sahilsingh2402

**Pull request merged**
