### PR TITLE
Sorting hat game added

### PR DESCRIPTION
**Pull request by kamakshi829**
**Sorting Hat Game **

- Info about the related issue
- [x]  LGM-SOC'21 Participant 
- [ ]  Contributor

Closes: #426 

**Description**
In this program a house is assigned to the user when he/she clicks on the button, house name which is assigned to the user is displayed. 

**Type of change**
- [x]  New Feature(non-breaking change which adds functionality)

**Checklist:**
- [x] My code follows the guidelines of this project.
- [x]   I have performed a self-review of my own code.
- [x] I have commented my code, particularly where ever it was hard to understand.
- [ ]  I have made corresponding changes to the documentation.
- [x]  My changes generate no new warnings.
-  [ ]  I have added tests that prove my fix is effective or that my feature works.
- [ ]  Any dependent changes have been merged and published in downstream modules.

**Screenshots**
initial_img
first_output
second_output

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Small changes :

The Readme file should be titled as "README.md"
The project folder should be "Sorting Hat Game"

Kindly do these changes. @kamakshi829

**Comment by kamakshi829** [comment]
@prathimacode-hub ma'am, I have made the changes. Please check.

**Comment by kamakshi829** [comment]
@prathimacode-hub , @Debashish-hub Please check as I have made all necessary changes.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Kindly check it. Changes had been applied only for "README.md" file. All the other files are in wrong folder of "sorting hat game".  @kamakshi829

**Comment by Debashish-hub** [comment]
You have kept the 'Images' folder in 'sorting hat game' folder instead of 'Sorting Hat Game' folder. Just keep one folder "Sorting Hat Game" and keep everything inside it @kamakshi829

**Comment by kamakshi829** [comment]
@Debashish-hub and @prathimacode-hub Now,Please have a look.

**Review by Debashish-hub — APPROVED** [review]
Congrats! @kamakshi829 Your PR is approved.

**Review by prathimacode-hub — APPROVED** [review]
Good work. Keep it up. Welcome to the repo officially. Well done. Keep growing. Yayy. Your PR is approved. ✨👏🎉

**Comment by kamakshi829** [comment]
Thanku So much☺

**Pull request merged**
