### PR TITLE
City weather

### LINKED ISSUE #120: weather  notification script
Title: Weather Notification Using Python
About: I will try to implement a python script that will get weather notification of any city on youscreen
Name: Koaml
Label: Feature Request
Assignee: ''

Define You:

- [X] LGM-SOC'21 Participant
- [X] Contributor

Describe the solution you'd like...
It is python program which uses beautifulsoup  library and fetch the data from google and display it on your desktop as a notification reminder after every 20 seconds when program executed.

### PR DESCRIPTION
**Pull request by Komal-99**
## Related Issue 

- Info about the related issue 

- [X] LGM-SOC'21 Participant 
- [x] Contributor

Closes: #120 

### Describe the changes you've made

Give a clear description what modifications you have made
Added REAME.md
Added requirements.txt
Added weather.py 
Added Images 

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how have you verified the changes made

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Update Screenshot|

image

### CODE REVIEW

**Comment by Debashish-hub** [comment]
Please add a screenshot in readme file @Komal-99

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes needed:

- The program file should have comments wherever needed.
- The readme file should be named as README.md
- Elaborate the README of your project - purpose, use, steps of the workflow, compilation process, output screenshot etc. There is README template to follow in README file of the project
- The project folder should be titled as "Weather Notifier" as you had mentioned in the issue.
- The screenshot you add should be in "Images" folder.

Do the needful changes. @Komal-99

**Comment by Komal-99** [comment]
okay

**Comment by prathimacode-hub** [comment]
> okay @prathimacode-hub I am unable to add images in images folder while trying to upload it is showing site crash try again
> Rest changes are done kindly review

Changes to be done:

Ok, the PR commit message is not in template format yet.
And images and screenshots should be added in "Images" folder
Do create a repo of Images in your forked respository, Add the screenshot image to it.
And in the README file of your project. don't add "user-images" link. Add the image link that is added in the "Images" folder of your forked repository. The image link should be the link of the file that is added in this particular folder.
When you use user-images, it won't work as it doesn't support it.

Do the needful changes. @Komal-99

**Comment by Komal-99** [comment]
@prathimacode-hub  
I tried many times creating images folder and then uploading screenshot to that but while uploading it is giving me this error. Rest i have updated PR request as per template

image

**Comment by prathimacode-hub** [comment]
> @prathimacode-hub
> I tried many times creating images folder and then uploading screenshot to that but while uploading it is giving me this error. Rest i have updated PR request as per template
> 
> image

Read my earlier reply to gain clarity of why it isn't uploading. I suggested you not to use "user-images". Instead use the screenshot uploaded in the repo. If you had followed right format, it should have been solved. @Komal-99 

@Debashish-hub Kindly look into this issue and guide.

**Comment by Komal-99** [comment]
> > @prathimacode-hub
> > I tried many times creating images folder and then uploading screenshot to that but while uploading it is giving me this error. Rest i have updated PR request as per template
> > image
> 
> Read my earlier reply to gain clarity of why it isn't uploading. I suggested you not to use "user-images". Instead use the screenshot uploaded in the repo. If you had followed right format, it should have been solved. @Komal-99
> 
> @Debashish-hub Kindly look into this issue and guide.

I checked your reply and tried in similar way . but don't know why this error is occurring  the screenshot i added in readme earlier i was using same not user-images 
Still if you can tell step wise  i can try . As in other automation scripts I am unable to find this sort of things like images folder

**Comment by Debashish-hub** [comment]
Just create an image folder and add your screen shots into it. What's the problem you are facing @Komal-99

**Comment by prathimacode-hub** [comment]
> > > @prathimacode-hub
> > > I tried many times creating images folder and then uploading screenshot to that but while uploading it is giving me this error. Rest i have updated PR request as per template
> > > image
> > 
> > 
> > Read my earlier reply to gain clarity of why it isn't uploading. I suggested you not to use "user-images". Instead use the screenshot uploaded in the repo. If you had followed right format, it should have been solved. @Komal-99
> > @Debashish-hub Kindly look into this issue and guide.
> 
> I checked your reply and tried in similar way . but don't know why this error is occurring the screenshot i added in readme earlier i was using same not user-images
> Still if you can tell step wise i can try . As in other automation scripts I am unable to find this sort of things like images folder

That's because they were not a part of LGMSOC program. This is to be fair with everyone. It isn't really tough. We can help you out. Just let me know of how you're following or trying to add. So that we can suggest accordingly.  @Komal-99

**Comment by Debashish-hub** [comment]
Why did you closed it @Komal-99

**Comment by Komal-99** [comment]
Creating New one

**Pull request closed without merging**
