### PR TITLE
added Turtle race Game

### PR DESCRIPTION
**Pull request by archismansaha**
## Related Issue 

- Added Turtle race game

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #410 

### Describe the changes you've made

I have added the turtle racing game script
## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
I have played the game by my own to test 
screenshot

Describe how have you verified the changes made

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |

### CODE REVIEW

**Review by Debashish-hub — CHANGES_REQUESTED** [review]
Just a small change, rename your folder to Turtle Race and your python file to turtle_race.py
@archismansaha

**Comment by archismansaha** [comment]
@Debashish-hub  ok  changes are done.anymore change  I have to do?

**Review by prathimacode-hub — COMMENTED** [review]
Elaborate your README.md file. Add aim, purpose, workflow, compilation steps.
Kindly do this change. @archismansaha

**Comment by archismansaha** [comment]
@prathimacode-hub  mam is it ok now?

**Review by Debashish-hub — APPROVED** [review]
Good job @archismansaha Your PR is approved. Keep it up

**Review by prathimacode-hub — COMMENTED** [review]
Amazing work. Good to see your progress. Very well done. Keep it up. Congrats. Your PR is approved. 👌✨👏@archismansaha

**Pull request merged**
