### PR TITLE
Image Neon Effect Filter

### PR DESCRIPTION
**Pull request by Khushi-sharma07**
Related Issue
A basic image processing python script to generate the neon/glow filter image of the given image.

- [x] Hacktoberfest2021 Participant
- [x]  Contributor

Closes: #941   

Describe the changes you've made
Added required files as per the requirement of Image Neon Filter Converter.

Type of change
What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

How Has This Been Tested?
Tested the script on my local machine for different test cases.

Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

Screenshots:

Neon of plate

Neon of dog1

Neon of dark

### CODE REVIEW

**Comment by Khushi-sharma07** [comment]
Mam please review this pr🙏 @prathimacode-hub

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Add workflow, setup, detailed instructions, compilation steps and conclusion in your README file

@Khushi-sharma07

**Comment by Khushi-sharma07** [comment]
Mam please review the changes @prathimacode-hub

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Impressing work. 🙌👌✔@Khushi-sharma07

**Pull request merged**
