### PR TITLE
Added Website Blocker

### LINKED ISSUE #218: Website Blocker
Title: Website Blocker
About:I would like to build a GUI based website blocker.I'll write a Python script to create a GUI Website blocker that will take input the sites one wants to block as input and As a result, that site will remain blocked for some particular time.
Name: Rutuj Runwal
Label: Feature Request

Define You:

- [x]  LGM-SOC'21 Participant  

Please assign @prathimacode-hub

### PR DESCRIPTION
**Pull request by Rutuj-Runwal**
Title: Website Blocker

Description:  GUI Website blocker that will take input the sites one wants to block as input and As a result, that site will remain blocked for some particular specific time.

- [x] LGM-SOC'21 Participant

Fixed #218 

### Type of change
What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x]  New feature (non-breaking change which adds functionality)
- [ ]  Code style update (formatting, local variables)
- [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ]  This change requires a documentation update
### Checklist:
- [x]  My code follows the guidelines of this project.
- [x]  I have performed a self-review of my own code.
- [x]  My changes generate no new warnings.
- [x]  I have added tests that prove my fix is effective or that my feature works.
- [x]  Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:

- All the images and screenshots should be in "Images" folder
- The image links you add in README.md file shouldn't be of "user-images" but instead the file path.
- The file name should be titled as "website_blocker.py"
- Add all the libraries imported in the project in 'requirements.txt" file
- Add the workflow of the project in README.md as well.
- Add appropriate comments in the code wherever necessary to get good understanding of the program.

Kindly do the needful changes.
@Rutuj-Runwal

**Comment by Rutuj-Runwal** [comment]
> Changes to be done:
> 
> * All the images and screenshots should be in "Images" folder
> * The image links you add in README.md file shouldn't be of "user-images" but instead the file path.
> * The file name should be titled as "website_blocker.py"
> * Add all the libraries imported in the project in 'requirements.txt" file
> * Add the workflow of the project in README.md as well.
> * Add appropriate comments in the code wherever necessary to get good understanding of the program.
> 
> Kindly do the needful changes.
> @Rutuj-Runwal

I have done the necessary changes.
I have not added requirements.txt because there are no third party libraries used.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Add all the imported libraries of your project in "requirements.txt" file.

Kindly do this change. @Rutuj-Runwal

**Review by prathimacode-hub — APPROVED** [review]
Congrats. Your PR is approved. Welcome to the repo. Different script choosen. Keep up your great work. 🎇🎉🏷@Rutuj-Runwal

**Pull request merged**
