### PR TITLE
Matchmaker Game

### PR DESCRIPTION
**Pull request by neelshah2409**
Title: Matchmaker Game

-> LGM-SOC'21 Participant

   Contributor

Closes: #176 

Description:: Here we had made a game in which all cards are hidden if we can find 2 cards having same symbol at a time then only the cards will unhide. For this game we will use random ,tkinter ,time library.

Type of change
What sort of change have you made:

-> New feature (non-breaking change which adds functionality)
    Bug fix (non-breaking change which fixes an issue)
    Code style update (formatting, local variables)
    Breaking change (fix or feature that would cause existing functionality to not work as expected)
    This change requires a documentation update

Checklist:
-> My code follows the guidelines of this project.
 ->I have performed a self-review of my own code.
    I have commented my code, particularly where ever it was hard to understand.
 ->I have made corresponding changes to the documentation.
 ->My changes generate no new warnings.
    I have added tests that prove my fix is effective or that my feature works.
    Any dependent changes have been merged and published in downstream modules.

Screenshots:
output(matchmaker_starting)
output(matchmaker_going)
output(matchmaker_ending)

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:

The output screenshots you had added in README.md file should be of the image links that's present in "Images" folder
Can you elaborate your README more briefly.
Add appropriate comments in project file to get good understanding of the program
The project folder should be titled as "Matchmaker Game".

Kindly do the needful changes. @neelshah2409

**Comment by neelshah2409** [comment]
Mam > the images are same at both but ordered differently
         > updated readme and comments 
        >changing the name of folder I was unable to do that please help me for that or if its fine
and mam so sorry for closing the issue of calculator gui.

**Comment by prathimacode-hub** [comment]
That's Ok, but make sure you don't close it next time. To change the name of the folder. You have to repeat the workflow of it. You can't change it over here directly. You should make the appropriate changes in your forked repository and then push the changes here. About image links, you had added them in "Images" folder. Just add those images  links to your README. When you add image links from this repository, it woudn't show up as user-images but instead shows as file path. @neelshah2409

**Comment by neelshah2409** [comment]
Mam please check now.

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved. It will be merged soon. Good going. 💡@neelshah2409

**Pull request merged**
