### PR TITLE
Covid CasesAPI

### PR DESCRIPTION
**Pull request by Gaurav1401**
## Covid records

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [x] Contributor

Closes: #843

### Describe the changes you've made

Wrote complete code to get covid 19 updates about the number of cases around the world

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly where ever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:
Add workflow, description and compilation steps in README.md file.

@Gaurav1401

**Comment by Gaurav1401** [comment]
@prathimacode-hub mam, do i need to remove the .vscode folder?

**Comment by Gaurav1401** [comment]
@prathimacode-hub mam, I have added the project workflow and the description of that has already been covered in Purpose, please have a look :)

**Review by Debashish-hub — APPROVED** [review]
Good job @Gaurav1401

**Pull request merged**
