### PR TITLE
Added script for Jokes

### PR DESCRIPTION
**Pull request by Umesh-01**
## Title: Added a python script for jokes 

- [x] LGMSOC-21 Participant

This PR fixes the **ISSUE** #155 

## Changes done
Added a folder with a python script file for jokes, appropriate screenshots and a readme file to explain the details for the module of Jokes.

## Types of changes
New Feature

## Screenshots

image

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes needed to be done:

- Add your name at the end of the README file of the project
- The images you used in README.md file are user-images. Add images link as uploaded one's in the current repository
- All the images and screenshots should be in "Images" folder
- Add the compilation steps in your README file of the project.
- Rename the project file as "jokes_automation.py"

Kindly do the needful changes. @Umesh-01

**Comment by Umesh-01** [comment]
@prathimacode-hub mam give me 15 minutes...

**Comment by Umesh-01** [comment]
@prathimacode-hub mam done 👍

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes needed

The images and screenshots you had added in "images" folder.
But it should be in "Images" folder. Here it's case sensitive. Do correct this. 

@Umesh-01

**Comment by Umesh-01** [comment]
> Changes needed
> 
> The images and screenshots you had added in "images" folder.
> But it should be in "Images" folder. Here it's case sensitive. Do correct this.
> 
> @Umesh-01

Ooh sorry, I will do it now... 👍

**Comment by prathimacode-hub** [comment]
> > Changes needed
> > The images and screenshots you had added in "images" folder.
> > But it should be in "Images" folder. Here it's case sensitive. Do correct this.
> > @Umesh-01
> 
> Ooh sorry, I will do it now... 👍

You are allowed to make mistakes. No issues. @Umesh-01

**Comment by Umesh-01** [comment]
@prathimacode-hub mam now check it 🙂

**Review by prathimacode-hub — APPROVED** [review]
Congrats, Your PR is approved and merged successfully. 🎇👏@Umesh-01

**Pull request merged**
