### PR TITLE
To Do List GUI

### PR DESCRIPTION
**Pull request by rammya29**
## Related Issue 

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #563 

### Describe the changes you've made

I have created a new GUI app where we can create to-do list items and save for further purpose also we can edit it next time

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

It has been tested in the python idle environment where it irks perfectly without error.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by prathimacode-hub — APPROVED** [review]
Perfect and clean PR. Impressive work. Keep it up. 🤩🎊@rammya29

**Comment by prathimacode-hub** [comment]
Your PR has merge conflicts in your README.md file of your "To Do List". kindly check it, what's going wrong. @rammya29

**Comment by rammya29** [comment]
I don't know what error mam

**Comment by prathimacode-hub** [comment]
> I don't know what error mam

I am not able to merge it due to that. There is no wrong in your PR. But It still shows conflict. Try resolving it else create new PR. Don't close this PR. @rammya29

**Comment by prathimacode-hub** [comment]
Kindly raise a PR again. To let go of the conflicts. @rammya29

**Comment by rammya29** [comment]
I can't Create pull request again. I don't know why?

**Comment by prathimacode-hub** [comment]
> I can't Create pull request again. I don't know why?

I shall do one thing, I will close this PR from my end. Do try creating PR again. @rammya29

**Comment by rammya29** [comment]
Okay mam

**Comment by rammya29** [comment]
Can't merge automatically it's showing, mam.

**Pull request closed without merging**
