### PR TITLE
Added the splash screen in Zodiac Sign Finder in GUIScripts

### PR DESCRIPTION
**Pull request by akash435**
## Related Issue 

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

fixes : #342
Closes: #342

### Describe the changes you've made

Added a splash screen to Zodiac Sign Finder in GUIScripts.
The splash screen will appear for 5 sec before the application opens.

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

yes , below i have provided the a video for showing how it works.

## Checklist:

- [x] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |

## Below is the video showing how it looks like with splash screen,

https://user-images.githubusercontent.com/57003737/122636982-cbdb7480-d109-11eb-82a5-1df7dabe3509.mp4

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Small change:

Instead of adding "user-images content" imaages link, add up the file path of the images saved in this repo. @akash435

**Comment by akash435** [comment]
ok

**Comment by akash435** [comment]
the last link is video link, so i think that cannot be added as Images

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved and merged. Good initiation to enhance the existing project. I appreciate your efforts in taking this chance. Good going. 🎇👌🏷@akash435

**Pull request merged**
