### PR TITLE
Adding a new alien invasion game

### PR DESCRIPTION
**Pull request by Jordistyd**
**Related Issue**
**Info about related issue**
**Title**: The classic alien invaders game using pygame module in Python
**Name**: Yarden (Jordistyd)
**Label**: Feature Request

**Changes I've made**

- Added a folder AlienInvaders game under PyGamesScripts folder.
- The folder contains the alien invader files which consists of the code script along with comments wherever needed.
- It also has a Readme.MD file which explains everything about the code.
- It has a folder named images which contains output and other images required.

**Type of change**
What sort of change have you made:

-  New feature (non-breaking change which adds functionality)

**Checklist**:
 My code follows the guidelines of this project.
 I have performed a self-review of my own code.
 I have commented my code, particularly wherever it was hard to understand.
 I have made corresponding changes to the documentation.
 My changes generate no new warnings.
 I have added tests that prove my fix is effective or that my feature works.
 Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Is this a hangman game? 
@Jordistyd

**Comment by Jordistyd** [comment]
Accidentally wrote the wrong title :) fixed it to alien invasion

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
There are no files added to this PR. Kindly add up your project files. @Jordistyd

**Comment by Jordistyd** [comment]
Can I add the files to this PR or do I need to open a new one?

**Comment by prathimacode-hub** [comment]
> Can I add the files to this PR or do I need to open a new one?

Nope, you can add it to this PR. Since it's empty. @Jordistyd

**Comment by Jordistyd** [comment]
Great, I uploaded the right folder with all .py files and images.
thank you!

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Need changes:

- The project should be titled as "Alien Invasion"
- All images and screenshots should be in "Images" folder
- Add a "README.md" file for this project which describes, aim, purpose, worksflow, compilation steps, complete procedure, output screenshot and your name at the end. 
- Add appropriate comments wherever needed in your .py files to get good understanding of the project.
- Add all the libraries imported in your project in "requirements.txt" file

Kindly do these needful changes. @Jordistyd

**Comment by Jordistyd** [comment]
I have made the changes.
Thank you

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Small changes:

Kindly remove the extra ".txt" from README.md and "requirements.txt"
Also folder should be titled as "Images" not "images".
The README.md file has output screenshot. The screenshot link should be added as "file path"of the image and not the "user-images" content.

Do these minor changes. @Jordistyd

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
README.md file is empty. @Jordistyd

**Comment by Jordistyd** [comment]
Hi, 
no Idea what made readme empty, I wrote it in visual studio code.
the new file I pushed should work fine

**Review by prathimacode-hub — APPROVED** [review]
Yeah, now it's showing up. Thanks for all the changes. Glad to include your project in this repo. Your contribution is highly appreciated. It was an interesting game to add on. Kudos to you. Amazing work showcased. Congrats. Your PR is approved. ✨👏🎉@Jordistyd

**Comment by Jordistyd** [comment]
Thank you for all the patience and help during this first steps!
I really appreciate it and hope you keep up the good work!

**Comment by prathimacode-hub** [comment]
> Thank you for all the patience and help during this first steps!
> I really appreciate it and hope you keep up the good work!

Keep contributing and enjoy your open source journey ahead. !! 👏 @Jordistyd

**Pull request merged**
