### PR TITLE
Flames 

### PR DESCRIPTION
**Pull request by manognyaa**
## Related Issue 

- This game almost everyone have played in their childhood. To make it a bit easy, I have created this game.

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #270 
### Describe the changes you've made

Give a clear description what modifications you have made

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how have you verified the changes made

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
Overview
over view
Input
input

Output
ouput

GIF
gif

 | Updated Screenshot |

### CODE REVIEW

**Comment by manognyaa** [comment]
Hello mam,
I have made a pr, Please guide me, if any changes required @prathimacode-hub mam.
Thank you mam for your kind support. Because of you, I got to learn many things. I was not able to reply your comments mam ;(

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:

README needs more elaboration.
And project file should be titled as "flames.py"

Kindly do these needful changes. @manognyaa

**Comment by prathimacode-hub** [comment]
> Hello mam,
> I have made a pr, Please guide me, if any changes required @prathimacode-hub mam.
> Thank you mam for your kind support. Because of you, I got to learn many things. I was not able to reply your comments mam ;(

You're welcome. You had shown lot of improvement since your first PR. Glad to know you. Keep contributing. Good to see you grow. You're doing an amazing work. Did I mention this? You are a quick learner. Any queries, never hesitate to ask. Don't worry about delay as well. That happens. @manognyaa

**Comment by manognyaa** [comment]
> > Hello mam,
> > I have made a pr, Please guide me, if any changes required @prathimacode-hub mam.
> > Thank you mam for your kind support. Because of you, I got to learn many things. I was not able to reply your comments mam ;(
> 
> You're welcome. You had shown lot of improvement since your first PR. Glad to know you. Keep contributing. Good to see you grow. You're doing an amazing work. Did I mention this? You are a quick learner. Any queries, never hesitate to ask. Don't worry about delay as well. That happens. @manognyaa

Thank you very much mam.  
I have updated everything wherever required mam. Updated readme file, added images and elaborated the process.
please guide me, If any changes required @prathimacode-hub mam

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved. Yayyy. You had done a fab work. 🎇🎇🎇@manognyaa

**Pull request merged**
