### PR TITLE
Solitaire game

### PR DESCRIPTION
**Pull request by Akash20x**
## Solitaire game

- I successfully added a python GUI script to implement solitaire game .

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #468 

### Describe the changes you've made
- A "Solitaire Game" is an application created in python with PyQt5 GUI.
- In this application, user can play solitaire game with 52 cards.

Give a clear description what modifications you have made

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

I tested this application on my local system and perfect works fine and also provided its screenshots.
## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |

alt text

alt text

alt text

alt text

### CODE REVIEW

**Comment by Debashish-hub** [comment]
Please follow the PR template and project structure @Akash20x

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Follow the project structure given in the README file of this program. This is not in right format. Also your PR needs the template. @Akash20x

**Comment by Akash20x** [comment]
> Follow the project structure given in the README file of this program. This is not in right format. Also your PR needs the template. @Akash20x

OK

**Comment by Akash20x** [comment]
@prathimacode-hub
I have done all the required changes, please check it now.

**Review by Debashish-hub — CHANGES_REQUESTED** [review]
Replace the usercontent link of the images with the path of the images i.e. "Images/imageName.jpg" in readme. You can check some other PR for better understanding. @Akash20x

**Comment by Akash20x** [comment]
@Debashish-hub
I have done the required changes, please check it now.

**Review by Debashish-hub — APPROVED** [review]
Good job! @Akash20x Your PR is approved.

**Comment by prathimacode-hub** [comment]
Impressive Work @Akash20x. Congrats, Welcome to the repo officially. You nailed it.

**Pull request merged**
