### PR TITLE
Snake_game

### PR DESCRIPTION
**Pull request by muskantayal123**
Related Issue
Info about the related issue
LGM-SOC'21 Participant

Contributor

Closes: #77

Describe the changes you've made
My project works on Snake game.
I have used the turtle , random and time library.

Type of change
What sort of change have you made:
Bug fix (non-breaking change which fixes an issue)
New feature (non-breaking change which adds functionality)

How Has This Been Tested?
I have tested my code on my laptop.

Describe how have you verified the changes made.

Checklist:
My code follows the guidelines of this project.
I have performed a self-review of my own code.
I have commented my code, particularly whereever it was hard to understand.
I have made corresponding changes to the documentation.
I have added tests that prove my fix is effective or that my feature works.
Any dependent changes have been merged and published in downstream modules.

Screenshot:
Screenshot (1620)

### CODE REVIEW

**Comment by muskantayal123** [comment]
@prathimacode-hub Mam review it.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:

- The project folder should be as "Snake Game"
- Elaborate the README.md file of the project. You can look through the README.md files of the other approved PR's to know how it looks like. And there is also a template provided in README file of this repository for reference. 
- The file name should be as snake_game.py
- Add images and screenshots in "Images" folder
- And add the image links in README.md file of the project. 

Kindly do the needful changes.

@muskantayal123

**Comment by muskantayal123** [comment]
@prathimacode-hub Ma'am done all the changes.

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved. It will be merged soon. Well done. Your efforts are highly appreciated. 🙌🎇@muskantayal123

**Pull request merged**
