### PR TITLE
Add Bank Management System

### LINKED ISSUE #216: ADD: Bank Management System
This is an DataBase Management system for Bank's employee. I will made it using `python`, `tkinter` and `sqlite3`.

### PR DESCRIPTION
**Pull request by ghost**
## Related Issue 

- This is a Database management system for bank to maintain their employee data.

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #216 

### Describe the changes you've made

I haven't modified anything because it's a feature update.

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

I have checked whole project in my local machine after adding feature and it is working properly without any bug.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly where ever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots

bank
bank2
bank3

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Kindly follow the PR template. @thegautamkumarjaiswal

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:

Create project folder as "Bank Management Systems"
Elaborate the README.md file of your project.
All the backend related files should be in "Backend" folder
All the frontend related files should be in "Frontend" folder
All images should be in "Images" folder.

Kindly do the needul changes. @thegautamkumarjaiswal

**Comment by thegautamkumarjaiswal** [comment]
> Changes to be done:
> 
> Create project folder as "Bank Management Systems"
> Elaborate the README.md file of your project.
> All the backend related files should be in "Backend" folder
> All the frontend related files should be in "Frontend" folder
> All images should be in "Images" folder.
> 
> Kindly do the needul changes. @thegautamkumarjaiswal

ok, I will done.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Kindly add the workflow of the program, compilation steps and purpose of the project in the README.md file. Not many would be aware of SQL or databases processes. @thegautamkumarjaiswal

**Comment by prathimacode-hub** [comment]
There is a conflict in your PR due to the changes you had done in README.md file of the GUIScripts. Kindly correct it. @thegautamkumarjaiswal

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved. You had done a fab work. Congrats. ✨👏 @thegautamkumarjaiswal

**Comment by thegautamkumarjaiswal** [comment]
> Your PR is approved. You had done a fab work. Congrats.  @thegautamkumarjaiswal

Thank you @prathimacode-hub 😅

**Pull request merged**
