### PR TITLE
Integer to Roman numerals 

### PR DESCRIPTION
**Pull request by pratimakush10**
Title: Integer to Roman Numerals Program

LGM-SOC'21 Participant

Closes: #301 

Description : This script is the basic program in which user input Integer and it get converted into roman numerals.

Type of change
What sort of change have you made:
👍 New feature (non-breaking change which adds functionality)
Bug fix (non-breaking change which fixes an issue)
Code style update (formatting, local variables)
Breaking change (fix or feature that would cause existing functionality to not work as expected)
This change requires a documentation update

Checklist:
👍 My code follows the guidelines of this project.
👍 I have performed a self-review of my own code.
👍 I have commented my code, particularly where ever it was hard to understand.
I have made corresponding changes to the documentation.
👍My changes generate no new warnings.
I have added tests that prove my fix is effective or that my feature works.
Any dependent changes have been merged and published in downstream modules.

**Screenshot:**
Screenshot (93)****

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Kindly follow the project structure. Lots of guidelines missing. @pratimakush10

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Kindly follow the guidelines of the project structure. @pratimakush10

**Comment by pratimakush10** [comment]
Ma'am can you please elaborate the issue
 I have checked the guidelines from my side , I didn't understand the problem.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Please follow the instructions carefully given in README file of the project. @pratimakush10

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:

The project folder should be titled as "Integer To Roman Numeral"
The file name should be as integer_to_roman_numeral.py"
Add "requirements'txt" file and include libraries imported in the project.
Elaborate your "README.md" file. It needs aim, purpose, workflow, compilation steps, output screenshot(file path) and your name.
Add proper file name to image file stored in " Images" folder.

Kindly do the needful changes. @pratimakush10

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved. Kudos to you. Good work. Looking forward to more issues coming from you. Well done.  ✨🎉👏@pratimakush10

**Pull request merged**
