### PR TITLE
Minesweeper Game using 2D Python Implementation

### PR DESCRIPTION
**Pull request by codeaholic-shub**
## Related Issue 

- Made Minesweeper Game using 2D Implementation of Python

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #193 

### Describe the changes you've made

I have made a Minesweeper Game using 2D Python Implementation

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how have you verified the changes made

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots

First Projedct – minesweeper py PyCharm 13-06-2021 20_26_34
First Projedct – minesweeper py PyCharm 13-06-2021 20_26_45

Hello @prathimacode-hub mam,
Kindly Review my PR !

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:

Add imported libraries in the "requirements.txt" file
Elaborate the README.md file. Give short intro about the game. Aim. Purpose, workflow of the project, compilation steps. 
Add the images and screenshots in "Images" folder
Provide the image links file path that's added up in "Images" folder. Not user-images.

Kindly do the needful changes. @codeaholic-shub

**Comment by codeaholic-shub** [comment]
> Changes to be done:
> 
> Add imported libraries in the "requirements.txt" file
> Elaborate the README.md file. Give short intro about the game. Aim. Purpose, workflow of the project, compilation steps.
> Add the images and screenshots in "Images" folder
> Provide the image links file path that's added up in "Images" folder. Not user-images.
> 
> Kindly do the needful changes. @codeaholic-shub

Hello @prathimacode-hub mam,
As per yours instructions and guidelines ,I have made changes,
Kindly Review my PR !

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Add imported libraries in the "requirements.txt" file
Provide the image links file path that's added up in "Images" folder. Not user-images it should show the file path of the image present in "Images" folder.

These aren't done I guess. Correct me, if i am wrong. @codeaholic-shub

**Comment by codeaholic-shub** [comment]
> Add imported libraries in the "requirements.txt" file
> Provide the image links file path that's added up in "Images" folder. Not user-images it should show the file path of the image present in "Images" folder.
> 
> These aren't done I guess. Correct me, if i am wrong. @codeaholic-shub

@prathimacode-hub Mam,
As per yours instructions, I have made changes,
Kindly Review PR !

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved and merged. Good job. 👏✨@codeaholic-shub

**Pull request merged**
