### PR TITLE
Scientific Calculator

### PR DESCRIPTION
**Pull request by prakhar07msd**
Related Issue
Info about the related issue

 LGM-SOC'21 Participant

 Contributor

Closes: #371 

Describe the changes you've made
Give a clear description what modifications you have made

Type of change
What sort of change have you made:

 Bug fix (non-breaking change which fixes an issue)
 New feature (non-breaking change which adds functionality)
 Code style update (formatting, local variables)
 Breaking change (fix or feature that would cause existing functionality to not work as expected)
 This change requires a documentation update
How Has This Been Tested?
Describe how have you verified the changes made
Tested in command prompt and the command is mentioned in README.md and also added the image for testing.

Checklist:
 My code follows the guidelines of this project.
 I have performed a self-review of my own code.
 I have commented on my code, particularly wherever it was hard to understand.
 I have made corresponding changes to the documentation.
 My changes generate no new warnings.
 I have added tests that prove my fix is effective or that my feature works.
 Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by Debashish-hub — CHANGES_REQUESTED** [review]
Add workflow, compilation steps and be more elaborative in "README.md".
Add the correct image path so that it can be seen i.e. 'Images/imageName.png'
Do comment your code wherever necessary

Do these changes @prakhar07msd

**Comment by prakhar07msd** [comment]
> Add workflow, compilation steps and be more elaborative in "README.md".
> Add the correct image path so that it can be seen i.e. 'Images/imageName.png'
> Do comment your code wherever necessary
> 
> Do these changes @prakhar07msd

Please check my PR now

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:
The requirements file should be titled as "requirements.txt"
The project file should be titled as "scientific_calculator.py"

Kindly do these changes. @prakhar07msd

**Comment by prakhar07msd** [comment]
> Changes to be done:
> The requirements file should be titled as "requirements.txt"
> The project file should be titled as "scientific_calculator.py"
> 
> Kindly do these changes. @prakhar07msd

Now please check

**Review by Debashish-hub — CHANGES_REQUESTED** [review]
Rename your file to "requirements.txt" and 
Make sure the images are visible in the readme @prakhar07msd

**Review by prathimacode-hub — APPROVED** [review]
Whooaa, great going. Your PR is approved. Good work. Keep it up. 👌🧨🎊@prakhar07msd

**Comment by prakhar07msd** [comment]
> Whooaa, great going. Your PR is approved. Good work. Keep it up. 👌🧨🎊@prakhar07msd

Thank you

**Review by Debashish-hub — APPROVED** [review]

**Comment by prakhar07msd** [comment]
> Whooaa, great going. Your PR is approved. Good work. Keep it up. 👌🧨🎊@prakhar07msd

Merge my PR

**Comment by prathimacode-hub** [comment]
> > Whooaa, great going. Your PR is approved. Good work. Keep it up. 👌🧨🎊@prakhar07msd
> 
> Merge my PR

Yes, it will be done. No worries. @prakhar07msd

**Pull request merged**
