### PR TITLE
Added ImBored API Scripts.

### PR DESCRIPTION
**Pull request by SirishC**
## Related Issue 

- Info about the related issue 
Issue  :  #1001

- [x] Hacktoberfest2021 Participant 
- [ ] Contributor

Closes: #issue number that will be closed through this PR

### Describe the changes you've made

Added  a ImBored Script to API Scripts.
- A creative way to find an interesting ideas that you can do when you feel bored.
- ImBored uses boredapi to generate ideas.
- Added a the scripts in the below folder
`Path : Awesome_Python_Scripts/APIScripts/`

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
Steps followed : 
- Drafted all possible scenarios.
- Manually Tested each scenarios making sure its working as expected.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly whereever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

-Happy Coding :)

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Add issue number in PR template and along with that first create an issue using template and get it assigned to you. Then your files are not in project structure. You can find the details to follow in README and contributing guidelines. @SirishC

**Comment by SirishC** [comment]
Hi @prathimacode-hub 
I have created the issue and added to this PR. 
Can you instruct me regarding the changes need to be done on the structure of the project.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done :

Keep your project title as "I am Bored"
All images should be in "Images" folder
Elaborate your README file, it needs more detailing. You can check for README template provided.
And .py file shoudl be titled as "i_am_bored.py"
There are extra 3 .DS_Store files available kindly delete them.

Kindly work on it. @SirishC

**Comment by SirishC** [comment]
Hi @prathimacode-hub 
Changes requested : 
- [x] Keep your project title as "I am Bored"
- [x] All images should be in "Images" folder
- [x] Elaborate your README file, it needs more detailing. You can check for README template provided.
- [x]  .py file should be titled as "i_am_bored.py"
- [x] There are extra 3 .DS_Store files available kindly delete them.

All the changes as per the requirements are updates.
Kindly review and provide me with changes if any. 😄

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
README.md can be more elaborative. It need detailed. You can refer to README template provided to understand what could be added up. @SirishC

**Comment by SirishC** [comment]
> README.md can be more elaborative. It need detailed. You can refer to README template provided to understand what could be added up. @SirishC

Updated the README referring the template provided.

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Welcome to repo officially. Yayy. Congrats. ✨🎉@SirishC

**Pull request merged**
