### PR TITLE
Added World Bank GDP Ranking in GUIScripts

### PR DESCRIPTION
**Pull request by akash435**
## Related Issue 

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

fixes : #467
Closes: #467

### Describe the changes you've made
- A "World Bank GDP Ranking" is an application created in python with tkinter gui.
- In this application, user can find the GDP Ranking of any country entring just country code.
- The information can be like Ranking , Economy, and how many US Dollars.
- for the data, used the gdp.csv data, and read using pandas library.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

yes , below i have provided the a screenshots and video link for showing how it works. and video of its working also.

## Checklist:

- [x] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:

- Add purpose and compilation steps in your README.md file
- The project folder should be titled as "World Bank GDP Ranking"

Kindly do these changes. @akash435

**Comment by akash435** [comment]
ok mam

**Comment by akash435** [comment]
@prathimacode-hub , Added purpose and compilation steps in readme and changed the folder name, please check it

**Comment by prathimacode-hub** [comment]
> @prathimacode-hub , Added purpose and compilation steps in readme and changed the folder name, please check it

I don't find the changes in the foldername. Can you recheck it? Also the old files are still up there. @akash435

**Comment by akash435** [comment]
means I have to add new folder by deleting old folder , is this?

**Comment by prathimacode-hub** [comment]
> means I have to add new folder by deleting old folder , is this?

Yes. Add the project files in new folder in your forked repository. Delete old repository and push the changes.  @akash435

**Comment by akash435** [comment]
ok mam

**Pull request closed without merging**
