### PR TITLE
Added Card_game

### PR DESCRIPTION
**Pull request by Manasa2811**
Info: Added a new game called Card_game to the pygamescripts.

LGM-SOC'21: Participant

Closes: #97 

Description of changes: Added a game folder called Card_game which contains the game script along with the readme file.

Type of change: New feature

changes: changed folder name, modified README.md, inserted screenshot in image folder.

This code has been tested by running it and checking that there are no errors or warnings.

Checklist:
 My code follows the guidelines of this project.
 I have performed a self-review of my own code.
 I have commented my code, particularly whereever it was hard to understand.
 I have made corresponding changes to the documentation.
 My changes generate no new warnings.
 I have added tests that prove my fix is effective or that my feature works.
 Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done 

- The project folder name should be "Card Game"
- Images and screenshots should be in "Images" folder.
- Can you elaborate README more briefly. Purpose, how to compile, uses etc. 

Kindly do the needful changes. @Manasa2811

**Comment by Manasa2811** [comment]
Okay, sure.

**Review by prathimacode-hub — APPROVED** [review]
You had done an amazing work. Congrats. Your PR is approved and merged successfully. Keep doing and enriching yourself. 👌✨@Manasa2811

**Comment by Manasa2811** [comment]
Thank you:)

**Pull request merged**
