### PR TITLE
 Added Gwen - voice assistant using python

### LINKED ISSUE #235: Voice Assistant using Python
I want to add a voice assistant which can perform tasks such as : 
i) get information and read it
ii) play music
iii) send emails.
@prathimacode-hub @Debashish-hub  can you please assign it to me under LGM-SoC.

### PR DESCRIPTION
**Pull request by Paras0-7**
Fixes #235
Added a voice assistant using python.

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Follow the PR template. And this PR has conflicts due to the changes you had done in README file of the "AutomationScripts". Kindly correct it. @Paras0-7

**Comment by Paras0-7** [comment]
> Follow the PR template. And this PR has conflicts due to the changes you had done in README file of the "AutomationScripts". Kindly correct it. @Paras0-7

@prathimacode-hub  Do I need to add my script in the Automation readme too?

**Comment by prathimacode-hub** [comment]
> > Follow the PR template. And this PR has conflicts due to the changes you had done in README file of the "AutomationScripts". Kindly correct it. @Paras0-7
> 
> @prathimacode-hub Do I need to add my script name in the Automation readme too?

That's not needed. Remove that change and add the PR template in PR commit message along with issue number. @Paras0-7

**Comment by Paras0-7** [comment]
> > > Follow the PR template. And this PR has conflicts due to the changes you had done in README file of the "AutomationScripts". Kindly correct it. @Paras0-7
> > 
> > 
> > @prathimacode-hub Do I need to add my script name in the Automation readme too?
> 
> That's not needed. Remove that change and add the PR template in PR commit message along with issue number. @Paras0-7

@prathimacode-hub 
I didn't made any changes in the readme file of Automation Scripts.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
But it still shows the conflict and reason behind it due to which I'm unable to review. If there is a trouble from your end about not able to rectify or solve this, you can create a PR again. But for that I have to close this PR. Should I? @Paras0-7

**Comment by Paras0-7** [comment]
> But it still shows the conflict and reason behind it due to which I'm unable to review. If there is a trouble from your end about not able to rectify or solve this, you can create a PR again. But for that I have to close this PR. Should I? @Paras0-7

@prathimacode-hub you can close this PR. I'll request a new one.

**Comment by prathimacode-hub** [comment]
> > But it still shows the conflict and reason behind it due to which I'm unable to review. If there is a trouble from your end about not able to rectify or solve this, you can create a PR again. But for that I have to close this PR. Should I? @Paras0-7
> 
> @prathimacode-hub you can close this PR. I'll request a new one.

It's closed. You can create  a new one. @Paras0-7

**Pull request closed without merging**
