### PR TITLE
Facebook Messenger Automation

### PR DESCRIPTION
**Pull request by neelshah2409**
Title: Facebook Messenger Automation

Info about the related issue: Here we will message a person by just running the script

-> LGM-SOC'21 Participant

  Contributor

Closes: #141 

Description: First we need to open messenger in browser and then we have to open chat with targeted person to whom we need to send message and then run the program.

Type of change
What sort of change have you made:

 
 ->New feature (non-breaking change which adds functionality)
    Bug fix (non-breaking change which fixes an issue)
   Code style update (formatting, local variables)
   Breaking change (fix or feature that would cause existing functionality to not work as expected)
   This change requires a documentation update

Checklist:
-> My code follows the guidelines of this project.
->I have performed a self-review of my own code.
-> I have commented my code, particularly where ever it was hard to understand.
 ->I have made corresponding changes to the documentation.
-> My changes generate no new warnings.
    I have added tests that prove my fix is effective or that my feature works.
    Any dependent changes have been merged and published in downstream modules.

Screenshots
output(facebook messenger)
output(facebook)

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes needed 👍 

- Do add more text to your input for automation
- Just automating single line won't suffice the program
- Also elaborate the README.md file.

Do the needful changes. @neelshah2409

**Comment by neelshah2409** [comment]
Mam please review if any changes needed.

**Comment by prathimacode-hub** [comment]
> Mam please review if any changes needed.

I couldn't find any changes you made. Make sure to check had you pushed the changes to this repo. @neelshah2409

**Comment by neelshah2409** [comment]
Mam I had updated readme and also kept another image of output in images as well as in PR description also.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Yeah, you had done that.
Changes:

But you hadn't elaborated the README file of your project. (This means it needs more brief to let users understand the project)
You hadn't done the changes to your program file according to the output you had got or put up in PR. 

@neelshah2409

**Review by prathimacode-hub — APPROVED** [review]
Finally, your PR is approved and merged. You're such an enthusiastic and determined person. Loved your spirit. 👏🎇@neelshah2409

**Pull request merged**
