### PR TITLE
Add WaterMark Inserter project to Image processing Scripts

### PR DESCRIPTION
**Pull request by rivelez65**
Hello prathimacode-hub, 

I am a new programer, currently learning how to collaborate on projects. 
I noticed you have an Image Processing folder to contribute and would like to propose adding this Watermark Inserter GUI I made a while ago. 

Kind regards, 
Ricardo

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Good to see your interest to learn collaborating. Need a change and a add up. The program file should be as file_name.py
Your project should include a README file which elaborates for users to understand what project is about. You can go through other projects for reference of how README file should look like. And also whenever you create  a pull request, it's preferrable for you to first raise an issue and get it assigned to you. So that when you open up a pull request, you can link that issue number to this pull request (For example : #issuenumber). Then describe your script. In issue you should state of what the project is and how it's going to work.  So that, project once pushed, it would help in notifying me of what I can expect from this. Whenever you start collaborating, once should have a good glance of project [README.md](https://github.com/prathimacode-hub/Awesome_Python_Scripts/blob/main/README.md) and [CONTRIBUTING_GUIDELINES](https://github.com/prathimacode-hub/Awesome_Python_Scripts/blob/main/CONTRIBUTING_GUIDELINES.md). Can you raise an issue now about the scipt you had added here, link the issue to PR and do the changes needed. Glad to go through your project. It's a wonderful add-on. No worries, you can do this. It all happens when you are new to it. Just letting you know of how things work in open source, that's how you learn and grow right. Hope this helps you in getting things better. Looking forward to merge your PR once you rectify the things. 👍@rivelez65

**Review by prathimacode-hub — APPROVED** [review]
Congrats on merging your first pull request in this repository. You had done an exceptional work. Keep going. Kudos to you. 👏 @rivelez65

**Comment by rivelez65** [comment]
Thank you very much for your prompt reply, advice and guidance. 
I look forward to keep contributing.

**Comment by prathimacode-hub** [comment]
> Thank you very much for your prompt reply, advice and guidance.
> I look forward to keep contributing.

Sure, i would love to see various projects coming up from you. You catch up things very fast. Most welcome. Keep contributing to open source. Any queries, drop me a message. ✔

**Pull request merged**
