### PR TITLE
Dog Breed Identification 

### PR DESCRIPTION
**Pull request by Knighthawk-Leo**
Issue #1106 
 

- [x] Hacktoberfest2022 Participant

Description
It's A Python -Django based Script build  to find the breed of the dog the user uploaded 
Files Changed
- [ ] Upload the Django Script for the Web app 
- [ ] Includes Webapp , Templates and static files.
Type of change

Checklist:

 My code follows the guidelines of this project.
 I have performed a self-review of my own code.
 I have commented my code, particularly where ever it was hard to understand.
 I have made corresponding changes to the documentation.
 My changes generate no new warnings.
 I have added tests that prove my fix is effective or that my feature works.
 Any dependent changes have been merged and published in downstream modules.
Screenshots
Screenshots are attached for reference.

### CODE REVIEW

**Comment by Knighthawk-Leo** [comment]
@prathimacode-hub please review my PR

**Review by prathimacode-hub — COMMENTED** [review]
Can you make things clear of what are the files you had included in your PR? @Knighthawk-Leo

**Comment by Knighthawk-Leo** [comment]
> Can you make things clear of what are the files you had included in your PR? @Knighthawk-Leo 

Yes ma'am updated the PR

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Appreciate work. 👍👏@Knighthawk-Leo

**Comment by prathimacode-hub** [comment]
Correct the README file. You have also included contributing guidelines in it and also refer to the README template provided as well for better understanding of the project. You can elaborate much briefer about the project. @Knighthawk-Leo

**Comment by Knighthawk-Leo** [comment]
@prathimacode-hub Done

**Review by prathimacode-hub — COMMENTED** [review]
Have you seen the README template? @Knighthawk-Leo

**Comment by Knighthawk-Leo** [comment]
@prathimacode-hub Updated the Readme.md

**Review by prathimacode-hub — APPROVED** [review]
PR approved. ✔👌@Knighthawk-Leo

**Pull request merged**
