### PR TITLE
Added sudoku game

### PR DESCRIPTION
**Pull request by pragyakhanna11**
# Sudoku
- Play the classic sudoku game

------------

- [x] LGM-SOC Participant

Closes: #65 
## Describe the changes made:
- Added the code for the game with multiple levels
- Added the Readme file for the same

## Type of change:
- [x] New feature (non-breaking change which adds functionality)

## Checklist:
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly whereever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshot:
sudoku

### CODE REVIEW

**Comment by Debashish-hub** [comment]
Add a requirements.txt and do comment your code wherever necessary @pragyakhanna11

**Comment by pragyakhanna11** [comment]
Please check @Debashish-hub

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Just a small change. Kindly add a short introduction about sudoku game in your README.md file. Other than that, it's all perfect. @pragyakhanna11

**Review by prathimacode-hub — APPROVED** [review]
Congrats. This PR is approved, and will be merged soon. You can take up an another issue to work on. It was a fab and impressive job. Keep doing sparkling things ahead. 🎇👌👌@pragyakhanna11

**Comment by pragyakhanna11** [comment]
@prathimacode-hub thank you 😊

**Pull request merged**
