### PR TITLE
MCQ

### PR DESCRIPTION
**Pull request by kumarjeetray**
## Related Issue 

- Info about the related issue 

- [X] LGM-SOC'21 Participant 
- [X] Contributor

Closes: #544 

### Describe the changes you've made

Give a clear description what modifications you have made

I have made the file

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

I have run and tested the code

## Checklist:

- [X] My code follows the guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly whereever it was hard to understand.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:
Don't create folder name in shortcuts. Instead write the folder name as "Multiple Choice Questions"
Add aim, purpose and workflow of the project in "README.md" file.

Kindly do the needful changes. @kumarjeetray

**Review by prathimacode-hub — APPROVED** [review]
Good to see your progress in coming up with new issues. You're doing great. Whooa, your PR is approved. 🎇🎇🤩@kumarjeetray

**Comment by kumarjeetray** [comment]
> 
> 
> Good to see your progress in coming up with new issues. You're doing great. Whooa, your PR is approved. 🎇🎇🤩@kumarjeetray

Did you get a chance to check the one I sent you in LinkedIn. The one I had done using Flask in Python?

**Comment by prathimacode-hub** [comment]
No, I haven't. I will check now. @kumarjeetray

**Pull request merged**
