### PR TITLE
Create scrap_news.py

### PR DESCRIPTION
**Pull request by Umesh-01**
Using web scraping to fetch latest news headlines

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
That's great to see ur initiation to contribute. Kindly follow the contributing guidelines to merge it successfully. It should be like :

prathimcode-hub/Awesome_Python_Scripts/WebScrapingScripts/NewsScraping/News_Scraping.py

@Umesh-01

**Comment by Umesh-01** [comment]
should I delete this scrap_news.py file first??
then I have to create a folder for it??

**Comment by prathimacode-hub** [comment]
Yup, I will check on them and merge it soon @Umesh-01

**Review by prathimacode-hub — APPROVED** [review]
Wonderful contribution. That was a well documented and a good basic script to start on with Web Scraping.

Yay, you have successfully merged your first PR. 🎉
Do star the repository, if it helped you in open sourcing and adding up your green square.

Thanks for opening this pull request! 🤗                                                                                

**Are you looking for more beginner-friendly issues? Check out [this](https://github.com/prathimacode-hub/HelloWorld/) repo.**

**Review by prathimacode-hub — APPROVED** [review]
Congrats on merging your first PR. 🎉
Do star this repository, if it helped you in contributing to open source and added you a green square.

It was a wonderful initiation from you to contribute. Loved your spirit. Keep doing the great work. You have added up a amazing web scraping script for newbies to get started.

Thanks for opening this pull request! 🤗 **Are you looking for more beginner-friendly issues? Check out [this](https://github.com/prathimacode-hub/HelloWorld/) repo.**

**Pull request merged**
