### PR TITLE
Added Zoom bot Auto Attend

### LINKED ISSUE #925: Zoom Auto Attendant
Hey contributors, good to see you. 

This project is a zoom bot that automatically joins zoom calls for you and saves the meeting id and password.

Repo : Automation Scripts 

If you like to work on this issue, follow the given guidelines for code as well as for the README.

### PR DESCRIPTION
**Pull request by NEERAJAP2001**
## Fixes #925 

- Zoom Bot Auto Attend

- [x] Hacktoberfest2021 Participant 
- [ ] Contributor

### Describe the changes you've made
Added New Project

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
Screenshot 

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Is this not done by you. It's showing some one else name in MIT License? @NEERAJAP2001

**Comment by NEERAJAP2001** [comment]
Yes! But ofcourse there are changes!  It's just a copy! Inspired from him.

**Comment by prathimacode-hub** [comment]
> Yes! But ofcourse there are changes! It's just a copy! Inspired from him.

I don't think hacktober fest would accept it. @NEERAJAP2001

**Comment by NEERAJAP2001** [comment]
Well in that case I'll come with more changes and also change the licence.
Would that be okay?

**Comment by prathimacode-hub** [comment]
That would be better but come with new PR. As they review it more deeper. @NEERAJAP2001

**Comment by NEERAJAP2001** [comment]
Done @prathimacode-hub

**Pull request closed without merging**
