### PR TITLE
Marksheet - GUI

### PR DESCRIPTION
**Pull request by rammya29**
## Related Issue 

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #575 

### Describe the changes you've made

I have mad the python script where it can allows use to enter grade to calculate SGPA

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

 It has been tested under idle environment
## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by Debashish-hub — CHANGES_REQUESTED** [review]
Why have you added two projects in a single PR. Make separate PRs for each one @rammya29

**Comment by rammya29** [comment]
I did seperate one but I don't why it became like this?

**Comment by Debashish-hub** [comment]
> I did seperate one but I don't why it became like this?

Just delete one project, create PR for one and wait for the PR to get merged and then create another PR or you can learn to create multiple PRs @rammya29

**Review by prathimacode-hub — APPROVED** [review]
Finally, its done. PR approved. Great work. 👏🤩@rammya29

**Pull request merged**
