### PR TITLE
Issue 414: Added Image Stitching 

### PR DESCRIPTION
**Pull request by sherin527**
`<h1>Image Stitching</h1>

- Implemented a feature-based automatic image stitching algorithm wherein we input two images with overlapping fields and a wide seamless panorama is obtained at the end of the result.

Closes: #414 

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #[issue number that will be closed through this PR]

### Describe the changes you've made

I have implemented a feature-based automatic image stitching algorithm wherein we input two images with overlapped fields, and we get a wide seamless panorama. I have used OpenCV to implement this. This includes steps such as:
1.Feature extraction using SIFT descriptor of OpenCV
2.Matching correspondences between images
3.Compute Homography
4.Warping & Stitching

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested?

Successfully tested the source code in the local machine.
## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### Original image
hill1
hill2

### Output
result

@prathimacode-hub ma'am, pls review this PR and let me know any changes required.

### CODE REVIEW

**Review by Debashish-hub — CHANGES_REQUESTED** [review]
Add a requirements.txt file @sherin527

**Comment by sherin527** [comment]
ok @Debashish-hub

**Comment by sherin527** [comment]
Added requirements.txt file @Debashish-hub

**Review by Debashish-hub — APPROVED** [review]
Great! Your PR is approved @sherin527 Congratulations

**Pull request merged**
