### PR TITLE
Real-Time Bitcoin Rate

### PR DESCRIPTION
**Pull request by Aditya8821**
- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #149 

### Describe the changes you've made
This project is on Rea-Time Bitcoin rate, it is made with the help of the BeautifulSoup module which helps in extracting the data from HTML and XML pages and then accessing required data from that extracted text.

Give a clear description of what modifications you have made

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
I have tested my code on Local Machine

Describe how have you verified the changes made

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots
Demo Output

### CODE REVIEW

**Comment by Debashish-hub** [comment]
Which issue are you fixing @Aditya8821

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:

- Add libraries in "requirements.txt" file
- File name of the project should be snake case. It should be as bitcoin_rate.py
- Add issue number in your PR template.
- The output you had added in your README file is from your local souce. CHange the image link to this repository. 
- Add real-time use and purpose of this script in README file.
- Also add how did you compile the script. 

Kindly do the needful changes. @Aditya8821

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved and merged succesfully. Keep up your good work. Kudos. 👏👌@Aditya8821

**Comment by Aditya8821** [comment]
Thank You so much mam🙌

**Comment by prathimacode-hub** [comment]
> Thank You so much mam🙌

Mention not. 🙂

**Pull request merged**
