### PR TITLE
Password Checker

### PR DESCRIPTION
**Pull request by hr1shu**

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:

- PR commit message isn't in right template.
- PR title doesn't show the project title.
- You hadn't added your issue number in commit message
- Follow the project structure and guidelines mentioned.
- The project file name should be "password_checker.py"
- Your project repository should be as "Password Checker"
- Elaborate your README. md file.
- Add the output screenshot to your README.md file.
- In your project file, add comments wherever necessary
- All images and screenshots should be in "Images" folder.

Always read the CONTRIBUTING GUIDELINES and README of the project before you raise a PR.
@hr1shu

**Comment by hr1shu** [comment]
On it!!!

**Comment by hr1shu** [comment]
Title: Password Checker
Info about the related issue:
You have to enter your password keyword to check how many times your password has been compromised.

->LGM-SOC'21 Participant

Closes: #101

Type of change
What sort of change have you made:

-> New feature (non-breaking change which adds functionality)
Bug fix (non-breaking change which fixes an issue)
Code style update (formatting, local variables)
Breaking change (fix or feature that would cause existing functionality to not work as expected)
This change requires a documentation update

Checklist:
-> My code follows the guidelines of this project.
->I have performed a self-review of my own code.
->I have commented my code, particularly where ever it was hard to understand.
->I have made corresponding changes to the documentation.
->My changes generate no new warnings.
I have added tests that prove my fix is effective or that my feature works.
Any dependent changes have been merged and published in downstream modules.
Screenshots

Output

**Comment by hr1shu** [comment]
The image file is not appearing in readme file, plz help!!

**Comment by prathimacode-hub** [comment]
> The image file is not appearing in readme file, plz help

Image file is in which format?

**Comment by hr1shu** [comment]
> > The image file is not appearing in readme file, plz help
> 
> Image file is in which format?

Png

**Comment by Debashish-hub** [comment]
> The image file is not appearing in readme file, plz help!!

Try this

**Comment by hr1shu** [comment]
> > The image file is not appearing in readme file, plz help!!
> 
> Try this - img src="Images/Output.png"

This didn't worked, but I tried something different and it works now.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Hey, kindly change the output screenshot link to the latest added image link in README file
In program file, add comments wherever needed to know the right workflow as it's not been added in README. 

Do these changes. @hr1shu

**Review by prathimacode-hub — APPROVED** [review]
Congrats, your PR is approved and will be merged soon. You can take another issue to work upon. 👏@hr1shu

**Pull request merged**
