### PR TITLE
Simple Oddly Satisfying Animation/Game using PyGame #67

### PR DESCRIPTION
**Pull request by AK-Subodh**
## Related Issue 

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #67

### Describe the changes you've made

- My project is an animation of oddly satisfying type of  games where animation goes on in infinite loop and player could provide some input to create some disturbance.
-  I have used PyGame to create it.
- It demonstrates use of classes.
## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

I have tested my code on Local Machine.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

- [animation_img](https://github.com/AK-Subodh/Awesome_Python_Scripts/blob/main/PyGamesScripts/Oddly-Satisfying-Game/assets/animation_img.PNG)
-  [main_menu](https://github.com/AK-Subodh/Awesome_Python_Scripts/blob/main/PyGamesScripts/Oddly-Satisfying-Game/assets/main_menu_img.PNG)

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Kindly follow the project structure.

What are those .vs files? And you had added directly in the main repo? Do you need help? @AK-Subodh

**Comment by AK-Subodh** [comment]
> 
> 
> Kindly follow the project structure.
> 
> What are those .vs files? And you had added directly in the main repo? Do you need help? @AK-Subodh

@prathimacode-hub Yes Mam, I need help. Please Guide me about how to make changes now.

**Comment by prathimacode-hub** [comment]
> > Kindly follow the project structure.
> > What are those .vs files? And you had added directly in the main repo? Do you need help? @AK-Subodh
> 
> @prathimacode-hub Yes Mam, I need help. Please Guide me about how to make changes now.

Ok, what's the project title you had considered? @AK-Subodh

**Comment by AK-Subodh** [comment]
> 
> 
> > > Kindly follow the project structure.
> > > What are those .vs files? And you had added directly in the main repo? Do you need help? @AK-Subodh
> > 
> > 
> > @prathimacode-hub Yes Mam, I need help. Please Guide me about how to make changes now.
> 
> Ok, what's the project title you had considered? @AK-Subodh

Oddly Satisfying Animation

**Comment by prathimacode-hub** [comment]
Ok, I shall get back with you with a discussion link. You can join me there. I shall guide you further. @AK-Subodh

**Comment by prathimacode-hub** [comment]
This is the link : https://github.com/prathimacode-hub/Awesome_Python_Scripts/discussions/213

Hope this solves all your queries, clears your confusion and helps you in creating a finest PR. @AK-Subodh

**Pull request closed without merging**
