### PR TITLE
Login System

### PR DESCRIPTION
**Pull request by AmitGupta700**
- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #221 

### Describe the changes you've made
- This small project will contain features of login and signup systems as we saw in your daily life.
- Using this project, you will come to know a little information about how the login systems of all websites/applications work.
- In this, we are going to make a Login System in Tkinter Python.
- For this project, you need to have the Tkinter module.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
I have tested my code on Local Machine.

Describe how have you verified the changes made

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots
output

### CODE REVIEW

**Comment by Debashish-hub** [comment]
Do comment your codes wherever necessary, and what is the login.txt file @AmitGupta700

**Comment by AmitGupta700** [comment]
> Do comment your codes wherever necessary, and what is the login.txt file @AmitGupta700
> what's the issue you are fixing

Sir, I have elaborated in the readme file about the login.txt file, and sir I have commented in the code also now.

**Comment by Debashish-hub** [comment]
Add the issue number you are fixing in the template @AmitGupta700

**Review by prathimacode-hub — COMMENTED** [review]
Small change:

The project file name should be as login_system.py

Do this change. @AmitGupta700

**Comment by prathimacode-hub** [comment]
Add the issue number in PR commit message. @AmitGupta700

**Comment by AmitGupta700** [comment]
> Add the issue number in PR commit message. @AmitGupta700

Yes Ma'am Done

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved. It will be merged soon. You can take up another issue to work on. Well done. ✨@AmitGupta700

**Pull request merged**
