### PR TITLE
Faker API

### PR DESCRIPTION
**Pull request by photon149**
## Related Issue 

- Info about the related issue 

- [x] Hacktoberfest2021 Participant 
- [x] Contributor

Closes: #1072  issue number that will be closed through this PR

### Describe the add-ons or changes you've made

We implemented Faker API , with a detailed explanation of its working , and with a lot of examples.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Manually run and tested 

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by photon149** [comment]
@prathimacode-hub  please check and review the same.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Add output screenshots in "Images" folder in this project and add the links of the images present in this repo to your README file instead of user-images content. @photon149

**Comment by photon149** [comment]
Done with the suggested changes @prathimacode-hub .

**Review by prathimacode-hub — APPROVED** [review]
PR approved.  Great going. Keep it up. 👏👌@photon149

**Pull request merged**
