### PR TITLE
Income Tax Calculator

### PR DESCRIPTION
**Pull request by baljeet-singh97**
## Related Issue 
Name - Baljeet Singh
Issue no - 750

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [x] Contributor

Closes: #750 

### Describe the changes you've made

added a python script to calculate income tax calculator used tkinter for GUI.

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

tested on my local system using jupyter.

## Checklist:
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by Debashish-hub — CHANGES_REQUESTED** [review]
Follow proper project template @baljeet-singh97 
Add requirements.txt, Images and be elaborative in readme with purpose. compilation steps, workflow and images

**Review by Debashish-hub — CHANGES_REQUESTED** [review]
Add comments to your code wherever necessary
Add all the images to a folder named 'Images'
Rename your folder to Income Tax Calculator
Follow the proper README template, You can watch some other for reference and don't add githubusercontent link for images , add proper image path i.e. 'Images/imageName.png'

@baljeet-singh97

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Follow the project structure given. @baljeet-singh97

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
The project fiel should be as "income_tax_calculator.py"
For README.md, there is a template provided to follow. Kindly look through it. This is not how it should look like
The images should be in "Images" folder
Delete .gitignore and empty file of img.txt.

Kindly do these changes. @baljeet-singh97

**Comment by baljeet-singh97** [comment]
updated the readme and made changes as mentioned above and followed readme template.

**Review by Debashish-hub — CHANGES_REQUESTED** [review]
Rename your "images" folder to Images
Replace the image src in README with 'Images/imageName.png'
@baljeet-singh97

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Only change it needs, add image in "Images" folder. That's it. @baljeet-singh97

**Comment by baljeet-singh97** [comment]
Review my changes @Debashish-hub 
@prathimacode-hub

**Review by prathimacode-hub — APPROVED** [review]
Hey, welcome to the repo officially. Conngrats on your first PR. Yayy. Amazing work. Keep it up. Great start. 🎉✨👏@baljeet-singh97

**Pull request merged**
