### PR TITLE
Added Wikipedia GUI

### PR DESCRIPTION
**Pull request by cybot-des**
## Related Issue 

- Added Wikipedia GUI that fetches whole wiki page info for that topic

- [x] LGM-SOC'21 Participant 

Closes: #402

### Describe the changes you've made

Made a GUI with Tkinter Python that helps user to fetch information for a specific topic
Uses Wikipedia-API module

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
Tested by running it on my local machine
coded by considering passing of null value in topic name

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |

[Demo Video](https://drive.google.com/file/d/16tfrVZO_fihEZqw8wg9NXGGPptXJh4M2/view?usp=sharing)
[Image 1](https://github.com/cybot-des/Awesome_Python_Scripts/blob/main/GUIScripts/Wikipedia%20GUI/Images/image_1.JPG)
[Image 2](https://github.com/cybot-des/Awesome_Python_Scripts/blob/main/GUIScripts/Wikipedia%20GUI/Images/image_2.JPG)

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
This issue is already done, you can take up an another issue to work on. Before taking up, do check if it's already done. By the way always follow the template given while raising an issue to get it assigned. @cybot-des

**Comment by cybot-des** [comment]
Maam, I was assigned this issue first

**Comment by prathimacode-hub** [comment]
> Maam, I was assigned this issue first

How would i know if the issue is assigned, if you haven't followed the template? @cybot-des

**Comment by cybot-des** [comment]
Ok my bad, I will rectify it and submit

**Comment by cybot-des** [comment]
Maam I have updated PR with template

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
In README.md, add purpose, compilation steps and add your name at end of your file.

Kindly do this change. @cybot-des

**Review by prathimacode-hub — APPROVED** [review]
Keep it up. Good work. Congrats. Your PR is approved. Well done. ✨🏷@cybot-des

**Pull request merged**
