### PR TITLE
Added Road cross turtle game in pygame scripts folder

### PR DESCRIPTION
**Pull request by AJgthb2002**

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Wait, is issue assigned to you. You cannot work without getting issue assigned. Also go through contributing guidelines and process. We have templates to be followed as well. @AJgthb2002

**Comment by AJgthb2002** [comment]
oh okay. I'll create an issue regarding this.

**Comment by prathimacode-hub** [comment]
This issue is already done. Before creating check if the issue is already available in repo or not else you can choose from open issues. @AJgthb2002

**Comment by prathimacode-hub** [comment]
And one more thing, you should never close PR's from your end. It's against open source. I'm just letting you know so that next time you do. No worries. @AJgthb2002

**Comment by AJgthb2002** [comment]
Oh I wasn't aware of this. I am just a beginner in open-source. Thank you!

**Comment by prathimacode-hub** [comment]
I understood that's the reason I mentioned. Do let me know if you have chose any issue. @AJgthb2002

**Pull request closed without merging**
