### PR TITLE
Added Guess The Number

### PR DESCRIPTION
**Pull request by jigar-sable**
## Guess The Number

- Guess The Number Game is a python program i.e, developed in python programming language using random module and some user inputs. 

- [x] LGM-SOC'21 Participant

Closes: #61 

### Describe the changes you've made
- Added a compiled code of the project.
- Added respective screenshots to demonstrate the working and output of the project.
- Added proper description for the project in the README.md

## Type of change

What sort of change have you made:
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
I have executed the program in my local computer and it executes successfully.

## Checklist:
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots
guessnum

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Just a small change.
The folder name should be "Guess The Number".

Other than this, it's all perfect. @jigar-sable

**Comment by jigar-sable** [comment]
> Just a small change.
> The folder name should be "Guess The Number".
> 
> Other than this, it's all perfect. @jigar-sable

Okay Ma'am Thank you.. I'll do those changes soon!

**Comment by jigar-sable** [comment]
@prathimacode-hub please guide me how should I rename the folder now!

**Comment by prathimacode-hub** [comment]
> @prathimacode-hub please guide me how should I rename the folder now!

You cannot rename it here directly. Any changes you make should come only from you. Again you should follow the same procedure from your end. Go to my forked repository in your profile. Delete this directory. Create a folder name as suggesred. Add the required files as you did earlier. And push back the code again.

**Comment by jigar-sable** [comment]
Ok I'll do the same.

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved and merged succesfully. Congrats. 🎇@jigar-sable

**Comment by jigar-sable** [comment]
> Your PR is approved and merged succesfully. Congrats. 🎇@jigar-sable

Thanks ma'am

**Pull request merged**
