### PR TITLE
Add image to text converter

### PR DESCRIPTION
**Pull request by nirbhay12345**
## Adding a new project

- [ ] Hacktoberfest2021 Participant 
- [x] Contributor

Closes: #1076

### Describe the changes you've made

I have add a new Python Script for an Image to text converter in the ImageProcessingScripts folder

## Type of change

- [x] My code follows the code style of this project.
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the code style of this project.
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly where ever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Add comments in your code to get understanding of it.
Elaborate your README file in detailed and keep it as README.md. We have a README template as well.

@nirbhay12345

**Comment by nirbhay12345** [comment]
> Add comments in your code to get understanding of it. Elaborate your README file in detailed and keep it as README.md. We have a README template as well.
> 
> @nirbhay12345

I HAVE UPDATED THE README.

**Comment by nirbhay12345** [comment]
Please review this PR.
@prathimacode-hub

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Welcome to the repo officially. Congratulations. Keep contributing. Well done. 🎉👏 @nirbhay12345

**Pull request merged**
