### PR TITLE
Send Push Notification To Your Phone

### PR DESCRIPTION
**Pull request by Iamtripathisatyam**
- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #379 

### Describe the changes you've made
I'll write a Python script that will send Push Notification to your phone using the Pushbullet module in Python. Essentially, this project will deliver notifications to all devices from a single system. We must first download the Pushbullet app on our phone or PC, then share the access token, and last, I will use that token to send you the notification on your device.

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
This code has been tried on my local machine.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots
output

### CODE REVIEW

**Review by Debashish-hub — CHANGES_REQUESTED** [review]
For the images and gif use 'Images/imageName.png' in the readme instead of the link @Iamtripathisatyam

**Comment by Iamtripathisatyam** [comment]
Sir, if I use the image link in this readme, there will be no image displayed. You also provided the same feedback on my previous code.

**Comment by Debashish-hub** [comment]
> Sir, if I use the image link in this readme, there will be no image displayed. You also provided the same feedback on my previous code.

I am not saying to use the image link. Just have a look at this for the image
https://github.com/prathimacode-hub/Awesome_Python_Scripts/pull/502/files#diff-4bcd166a23646e40712db678d5fe183e03660581759f03b85cbf0b1eda8a6ede
This is a better choice instead of using the links.

**Comment by Debashish-hub** [comment]
Great! That should be working fine @Iamtripathisatyam

**Review by prathimacode-hub — APPROVED** [review]
Good to see your here back. PR approved. Well needed script. Amazing work. Keep rising. 👏🤩@Iamtripathisatyam

**Comment by Iamtripathisatyam** [comment]
Thank you so much ma'am and sir

**Review by Debashish-hub — APPROVED** [review]

**Review by prathimacode-hub — COMMENTED** [review]
Good to see your progress of how far you had come in this journey of open source. Keep rocking.  
👏👏👏 @Iamtripathisatyam

**Comment by Iamtripathisatyam** [comment]
Thank you so much, ma'am

**Pull request merged**
