### PR TITLE
Added a python script to search for locations on gmaps

### PR DESCRIPTION
**Pull request by KevinKurian7**
this script takes arguments, in this case your desired location and opens the browser and search pull up the loaction on google maps.
you have two option to search enter the location through the command line itself or copy the location and the code will read it from your clipboard 
: )
ps: i have a python bot that uses selenium to scrape the web.it kind automates your instagram. 
     it will login to your ig account and it will search for post from the tags  we provide and likes and comments on it.
    should i add it on awsesomeautomatio section or here on webscraping

### CODE REVIEW

**Comment by KevinKurian7** [comment]
why is this Added a python script to search for locations on gmaps #12 has been not approved can i have a feedback

**Comment by prathimacode-hub** [comment]
Hey, can you please create a separate pull request for Instagram Bot and included all the files you had created earlier. @KevinKurian7

**Comment by KevinKurian7** [comment]
yeah sure 😊

**Comment by prathimacode-hub** [comment]
> why is this Added a python script to search for locations on gmaps #12 has been not approved can i have a feedback

Program was perfect, but it didn't follow the contributing guidelines for Map Launch project. This fits the "AutomationScripts" repository.

It should look like this :
prathimacode-hub/Awesome_Python_Scripts/AutomationScripts/LaunchMaps/Launch_Maps.py

Don't forget to add a README file with short description with requirements needed. Screenshot inclusion is must.

And one more thing, don't close the merge request from your end. That's against open source. Letting you know. Not everyone would take it positive. 

So now you got to create a separate pull request for Launch Maps project now  since you closed the merged request from your end as you did for Instagram Bot. 

Any more queries, don't hesitate to create it in a discussions tab. @KevinKurian7

**Comment by KevinKurian7** [comment]
oh i was confused sorry 😅

**Comment by prathimacode-hub** [comment]
Make the things right @KevinKurian7. You can do it. Never close the PR from ur end.

**Comment by KevinKurian7** [comment]
oh sorry i'm kind of new to github

**Comment by prathimacode-hub** [comment]
No worries I understand. Any help you need, don't hesitate to ask. Make them right. It all needs the extra push for first timers. @KevinKurian7

**Pull request closed without merging**
