### PR TITLE
Excel File Automation

### PR DESCRIPTION
**Pull request by neelshah2409**
# Excel File Automation

## Description:
Here we make excel file using openpyxl library and making excel file in the same folder as of script .
Here we can customize the columns and the data in the script , it will make us easier to customize the file .
- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #518 

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots
output(excel)

### CODE REVIEW

**Comment by neelshah2409** [comment]
@prathimacode-hub @Debashish-hub Please review my PR.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Add appropriate comments in ur code wherever needed.
Also README file is not elaborative. Kindly do these changes. @neelshah2409

**Comment by neelshah2409** [comment]
@prathimacode-hub mam I had made the changes so please review it.

**Review by prathimacode-hub — APPROVED** [review]
Kudos, Clean work. Good job. 🎊🎊@neelshah2409

**Pull request merged**
