### PR TITLE
Editor App

### PR DESCRIPTION
**Pull request by rammya29**
## Related Issue 

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #542 

### Describe the changes you've made

Give a clear description of what modifications you have made
  It is a simple image editor app which has a feature like a blur, contrast, brightness and also rotate, flip flop, adding a border.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how have you verified the changes made 
  This app is tested with the sample images and tested all the features

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:

The image links added in README.md are user-images content instead it should be file path of the images present in this repo.
Add aim and compilation steps in README.md
Add libraries imported in this project in "requirements.txt" file. You haven't included all the libraries. 

Kindly do the needful changes. @rammya29

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
The images added up in output are user-images content instead it should be file path of the images present in this repo. @rammya29

**Comment by rammya29** [comment]
I am not able to understand, can you explain little bit

**Comment by prathimacode-hub** [comment]
> I am not able to understand, can you explain little bit

This is the sample of how image link should look like:

https://github.com/rammya29/Awesome_Python_Scripts/blob/main/ImageProcessingScripts/Editor%20App/Images/test_image.jpg

I took it from your forked repo. Meanwhile add all such image links and make sure the images are added up in "Images" folder.
This project is "Image Editor", not an Editor App.. So change the project title to "Image Editor".

Kindly do the needful changes. @rammya29

**Review by prathimacode-hub — APPROVED** [review]
Whooa, your PR is approved. Fab work. Well done. 👌🤩@rammya29

**Comment by rammya29** [comment]
@prathimacode-hub , You have added the To Do label, what else I have to do?

**Comment by prathimacode-hub** [comment]
> @prathimacode-hub , You have added the To Do label, what else I have to do?

That's nothing about your work, it's for us. To update your scores. @rammya29

**Pull request merged**
