### PR TITLE
added code for tower of hanoi

### PR DESCRIPTION
**Pull request by richabh456**
## Related Issue 
Tower of Hanoi Game

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #272 

###  i Have added code for tower of hanoi.

Give a clear description what modifications you have made

## Type of change

What sort of change have you made:

- [] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how have you verified the changes made

## Checklist:

- [x] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly whereever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by richabh456** [comment]
issue#272

**Comment by richabh456** [comment]
@prathimacode-hub please do suggest the required changes ma'am.

**Comment by richabh456** [comment]
Title: Tower of Hanoi
description: The objective of this puzzle is to move the entire stack to one rod.
Lgmsoc'21 Participants.

**Comment by prathimacode-hub** [comment]
Add the PR template and issue number in PR commit message @richabh456

**Comment by richabh456** [comment]
@prathimacode-hub Now is it okay ma'am

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Kindly follow the project structure. 
Changes to be done:

- You should create a separate project folder of "Tower OF Hanoi" in "BasicPythonScripts"
- Then add all the related project files.
- The file name should be as tower_of_hanoi.py
- Add appropriate comments in the code to get good understanding of the project.
- Add the imported libraries used in your project in "requirements.txt" file
- Add the elaborative "README.md" file for this project. There is a template for it as well in README file of the project. This README.md" file should have aim, purpose, what it does, workflow of the project, compilation steps, output screenshots and your name at last.
- The screenshot inclusion is must in your README.md file of your project. And it should be file path of the images that's added in "Images" folder.
- Add all the images and screenshots in 'Images' folder
- Here, all these changes are subject to case-sensitive 

Always, read the README and CONTRIBUTING GUIDELINES of the project to know how you should create a PR. It would clear out your queries and as well your efforts don't go wasted,
Quality matters over quantity and doing meaningful contribution is important. Letting you know of the things how it works as you're new to the repo. 

Kindly do the needful changes. @richabh456

**Comment by prathimacode-hub** [comment]
You should never close an issue or PR from your end. @richabh456

**Comment by richabh456** [comment]
@prathimacode-hub sorry ma'am i am not getting what to do next.

**Comment by prathimacode-hub** [comment]
> @prathimacode-hub sorry ma'am i am not getting what to do next.

I had already listed out the changes to be done. Just do these changes in your forked repository and push back those changes. If any queries, don't hesitate to ask. @richabh456

**Comment by richabh456** [comment]
@prathimacode-hub iam not getting ma'am what to do.

**Comment by prathimacode-hub** [comment]
> @prathimacode-hub iam not getting ma'am what to do.

Ok, give me few mins. I shall get back to you with the discussion link. @richabh456

**Comment by prathimacode-hub** [comment]
> > @prathimacode-hub iam not getting ma'am what to do.
> 
> Ok, give me few mins. I shall get back to you with the discussion link. @richabh456

https://github.com/prathimacode-hub/Awesome_Python_Scripts/discussions/284
Join this discussion. It will help you in creating a PR easily and solving out all your queries. Anything else, you can let me know. @richabh456

**Comment by richabh456** [comment]
@prathimacode-hub i have made the required changes ma'am now please review my pr and suggest me what can i do.

**Comment by richabh456** [comment]
image

**Comment by richabh456** [comment]
@prathimacode-hub please review my pr ma'am

**Comment by prathimacode-hub** [comment]
> @prathimacode-hub please review my pr ma'am

Follow the project stsructure given Iin README file of the project. I had already mentioned all the changes that needs to be done in above comment. If you need any help, you can let me know about it. @richabh456

**Comment by richabh456** [comment]
@prathimacode-hub MA'AM i am facing issue in adding readme file.

**Comment by prathimacode-hub** [comment]
> @prathimacode-hub MA'AM i am facing issue in adding readme file.

Ok, cool. Just give me 2mins. I shall share you with the steps of how it can be done easily. @richabh456

**Comment by prathimacode-hub** [comment]
> > @prathimacode-hub MA'AM i am facing issue in adding readme file.
> 
> Follow this. https://github.com/prathimacode-hub/Awesome_Python_Scripts/discussions/284
 @richabh456

**Comment by richabh456** [comment]
@prathimacode-hub ma'am i have updated please check now.

**Comment by richabh456** [comment]
@prathimacode-hub now is it fine ma'am?

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:

You should always follow the project structure given.

The project folder should be titled as " Tower Of Hanoi"
The images and screenshots should be in "Images" folder
The README file should be titled as "README.md" file. There is a template enclosed of how to write README in "README" file of this project. This file should have, aim, purpose, description, workflow, compilation steps, output screenshot and your name at last.
The project file should be titled as "tower_of_hanoi.py"
Add appropriate comments in the project file to get good understanding of the project.

Kindly do the needful changes. @richabh456

**Comment by Debashish-hub** [comment]
Hey @richabh456 Please complete the changes requested to you.

**Comment by prathimacode-hub** [comment]
No changes from you yet? @richabh456

**Comment by prathimacode-hub** [comment]
Are you willing to do the changes or not? @richabh456

**Comment by prathimacode-hub** [comment]
Will you update it or not? Holding the PR for this long is not right. @richabh456

**Comment by prathimacode-hub** [comment]
It's been 27days, since I had addressed the last changes, and no update yet. I shall see for 2 more days else I have no option but to close the PR. @richabh456

**Comment by Ashu-1309** [comment]
Can I work on this issue ??

**Comment by prathimacode-hub** [comment]
> Can I work on this issue ??

@Ashu-1309, you can raise this project as a separate issue from your end. And get it assigned to you. This PR will be closed now.

**Pull request closed without merging**
