### PR TITLE
Dodge Charger Game

### PR DESCRIPTION
**Pull request by MuditCh57**
## Related Issue 

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #495 

### Describe the changes you've made

Added Dodge Charger game on PyGamesScripts folder. which was made with pygame module of python.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

None

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Kindly follow the project structure given in "README" file of this project. @MuditCh57

**Comment by MuditCh57** [comment]
Sorry but I don't understand. which README file are you talking about?
can you please explain more?

**Comment by Debashish-hub** [comment]
> Sorry but I don't understand. which README file are you talking about?
> can you please explain more?

Look at the README.md of Awesome_Python_Scripts, you can check the project structure there and make changes accordingly @MuditCh57

**Comment by MuditCh57** [comment]
> Kindly follow the project structure given in "README" file of this project. @MuditCh57

Done Changes 👍

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done :
The project folder should be titled as "Dodge Charger Game"
All the imported libraries of your project should be added up in "requirements.txt". you had added only one.
In project file, add appropriate comments in your code wherever needed. 
Add aim and purpose in your README.md file.

Kindly do the needful changes @Debashish-hub

**Comment by MuditCh57** [comment]
> Changes to be done :
> The project folder should be titled as "Dodge Charger Game"
> All the imported libraries of your project should be added up in "requirements.txt". you had added only one.
> In project file, add appropriate comments in your code wherever needed.
> Add aim and purpose in your README.md file.
> 
> Kindly do the needful changes @MuditCh57
Update changes.
Comments were already added.  Each function defines what it does.
Hope everything is great now.

**Review by prathimacode-hub — APPROVED** [review]
Excellent work. Glad to see you once again here in this repo. Welcome back. By the way, good to see you as LGMSOC participant. You had put up a bang in your very first PR as a participant. Keep it up. 🤩🎊🎉@MuditCh57

**Comment by MuditCh57** [comment]
> Excellent work. Glad to see you once again here in this repo. Welcome back. By the way, good to see you as LGMSOC participant. You had put up a bang in your very first PR as a participant. Keep it up. 🤩🎊🎉@MuditCh57

Thank You 🙏.

**Pull request merged**
