### PR TITLE
Alarm Clock Program 

### PR DESCRIPTION
**Pull request by pratimakush10**
Title: *Alarm Clock Program*

LGM-SOC'21 Participant

Closes: #75 

Description :  This script is the basic  alarm clock using time module of Python.
when you input hours and minutes for alarm to ring at that respective time alarm will ring

Type of change
What sort of change have you made:
👍  New feature (non-breaking change which adds functionality)
Bug fix (non-breaking change which fixes an issue)
Code style update (formatting, local variables)
Breaking change (fix or feature that would cause existing functionality to not work as expected)
This change requires a documentation update

Checklist:
👍 My code follows the guidelines of this project.
👍 I have performed a self-review of my own code.
👍 I have commented my code, particularly where ever it was hard to understand.
I have made corresponding changes to the documentation.
👍 
My changes generate no new warnings.
I have added tests that prove my fix is effective or that my feature works.
Any dependent changes have been merged and published in downstream modules.

Screenshots

Screenshot

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Your issue number is #75. Do the change. Always you should the issue number that you got yourself assigned to.
You PR doesn't follow the template. Check for the PR template in README file of the project.
Follow the right project structure. Always have a good glance of README for guidelines before you create an issue or PR.
You project folder name should be "Alarm Clock"
The file name of readme file should be README.md
Screenshots and Images should be in "Images" folder. 
The file name to add requirements should be "requirements.txt" file
Add libraries used in this project and any other requirements in "requirements.txt" file.
Steps you had mentioned it in 'requirements' file should come in README.md file of your project.
You also have a template to follow for your README.md file. It's mentioned in the README file of the project.

Kindly do the needful changes. @pratimakush10

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Screenshot you added should be in "Images" folder.
It's in Image folder. Do this change. @pratimakush10

**Comment by prathimacode-hub** [comment]
Thanks for rectifying the changes. Official labels had come out. I would merget this PR with the labels once I clarify about it. So you are good to take up a new issue to work on. You had done an amazing work.✔✨ @pratimakush10

**Comment by pratimakush10** [comment]
ok ma'am 
Thank you

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved. @pratimakush10

**Pull request merged**
