### PR TITLE
Word Transfer

### PR DESCRIPTION
**Pull request by kumarjeetray**
For transfer of information between one computer to another or from virtual machine to computer through sockets

### CODE REVIEW

**Comment by Debashish-hub** [comment]
Follow the PR template @kumarjeetray

**Comment by kumarjeetray** [comment]
> Follow the PR template @kumarjeetray 

Can you please tell me what I am missing, I am a bit confused

**Comment by Debashish-hub** [comment]
> > Follow the PR template @kumarjeetray
> 
> Can you please tell me what I am missing, I am a bit confused

Follow the CONTRIBUTING_GUIDELINES @kumarjeetray

**Comment by prathimacode-hub** [comment]
@kumarjeetray First and foremost you hadn't followed the format. You worked on your PR without raising an issue nor you got it assigned to yourself. Always read the README and CONTRIBUTING GUIDELINES of the project. @kumarjeetray

**Comment by kumarjeetray** [comment]
> 
> 
> > > Follow the PR template @kumarjeetray
> > 
> > 
> > Can you please tell me what I am missing, I am a bit confused
> 
> Follow the CONTRIBUTING_GUIDELINES @kumarjeetray

Yeah I saw them now. So can you please tell me what to do now. Please

**Comment by kumarjeetray** [comment]
Issue #427 
Changes made: I have added the files
Tested: The code has been tested by me by running it 
Checklist:

    My code follows the guidelines of this project.
  [X] I have performed a self-review of my own code.
    I have commented my code, particularly whereever it was hard to understand.
  [X] I have made corresponding changes to the documentation.
  [X] My changes generate no new warnings.
    I have added tests that prove my fix is effective or that my feature works.
    Any dependent changes have been merged and published in downstream modules.

**Comment by kumarjeetray** [comment]
## Related Issue 

- Info about the related issue 

- [ ] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #[issue number that will be closed through this PR]

### Describe the changes you've made

Give a clear description what modifications you have made

I have made the file

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

I have run and tested the code

## Checklist:

- [X] My code follows the guidelines of this project.
- [X] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly whereever it was hard to understand.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

**Comment by prathimacode-hub** [comment]
> > > > Follow the PR template @kumarjeetray
> > > 
> > > 
> > > Can you please tell me what I am missing, I am a bit confused
> > 
> > 
> > Follow the CONTRIBUTING_GUIDELINES @kumarjeetray
> 
> Yeah I saw them now. So can you please tell me what to do now. Please

You hadn't raised the issue, neither issue was assigned to you. You created your PR directly which is completely out of context. First raise an issue using the issue template given and get an issue assigned to you first. This PR doesn't stand valid, unless you do that. You now added PR template but it should show up in the first commit message above. You can edit it and add. And one more thing, your PR template doesn't have an issue number, because you didn't get your issue assigned. Follow the process. Hope you understood what I meant. @kumarjeetray

**Comment by kumarjeetray** [comment]
Thanks a lot for clearing the doubts. So will you be merging this or should I start afresh ?

**Comment by prathimacode-hub** [comment]
> Thanks a lot for clearing the doubts. Can you please merge this or should I start afresh :"3

This won't be closed, neither you are supposed to from your end. First create an issue and get it assigned. @kumarjeetray

**Comment by kumarjeetray** [comment]
> 
> 
> > Thanks a lot for clearing the doubts. Can you please merge this or should I start afresh :"3
> 
> This won't be closed, neither you are supposed to from your end. First create an issue and get it assigned. @kumarjeetray

I have already done it. Please do assign. Thanks

**Comment by prathimacode-hub** [comment]
> > > Thanks a lot for clearing the doubts. Can you please merge this or should I start afresh :"3
> > 
> > 
> > This won't be closed, neither you are supposed to from your end. First create an issue and get it assigned. @kumarjeetray
> 
> I have already done it. Please do assign. Thanks

Check on with issue, it needs improvements. @kumarjeetray

**Comment by kumarjeetray** [comment]
> 
> 
> > > > Thanks a lot for clearing the doubts. Can you please merge this or should I start afresh :"3
> > > 
> > > 
> > > This won't be closed, neither you are supposed to from your end. First create an issue and get it assigned. @kumarjeetray
> > 
> > 
> > I have already done it. Please do assign. Thanks
> 
> Check on with issue, it needs improvements. @kumarjeetray

I did the changes. Please let me know if it is okay

**Comment by prathimacode-hub** [comment]
Now raise a separate PR with your project title, proper commit message using the PR template along with your issue number.  And include all your project details. @kumarjeetray

**Comment by kumarjeetray** [comment]
## Related Issue 

- Info about the related issue 

- [X] LGM-SOC'21 Participant 
- [X] Contributor

Closes: #434 

### Describe the changes you've made

Give a clear description what modifications you have made

I have made the file

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

I have run and tested the code

## Checklist:

- [X] My code follows the guidelines of this project.
- [X] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly whereever it was hard to understand.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

**Comment by prathimacode-hub** [comment]
You have raise a new PR with your project title. @kumarjeetray

**Comment by kumarjeetray** [comment]
> 
> 
> You have raise a new PR with your project title. @kumarjeetray

I guess so because this is the only option showing up

**Comment by kumarjeetray** [comment]
You will be merging this right ?

**Comment by kumarjeetray** [comment]
> 
> 
> > You have raise a new PR with your project title. @kumarjeetray
> 
> I guess so because this is the only option showing up

You will be merging this right ?

**Comment by prathimacode-hub** [comment]
> > > You have raise a new PR with your project title. @kumarjeetray
> > 
> > 
> > I guess so because this is the only option showing up
> 
> You will be merging this right ?

No, you have to raise a new PR with the template changes you made now and add all the related files. This PR title doesn't justify your project. This time add a proper project title to your PR commit. I thought u would do that. @kumarjeetray

**Comment by kumarjeetray** [comment]
> > > > You have raise a new PR with your project title. @kumarjeetray
> > > 
> > > 
> > > I guess so because this is the only option showing up
> > 
> > You will be merging this right ?
> 
> No, you have to raise a new PR with the template changes you made now and add all the related files. This PR title doesn't justify your project. This time add a proper project title to your PR commit. I thought u would do that. @kumarjeetray 

Whenever I am going to add new files and create a new pr this one is only showing up. Unless this is closed. It cannot be done as it is showing me. So I shall be closing this one then

**Comment by kumarjeetray** [comment]
> > > > You have raise a new PR with your project title. @kumarjeetray
> > > 
> > > 
> > > I guess so because this is the only option showing up
> > 
> > You will be merging this right ?
> 
> No, you have to raise a new PR with the template changes you made now and add all the related files. This PR title doesn't justify your project. This time add a proper project title to your PR commit. I thought u would do that. @kumarjeetray 

Done something else this time. Do check

**Pull request closed without merging**
