### PR TITLE
Air Quality Detector(API)

### PR DESCRIPTION
**Pull request by neelshah2409**
## Air Quality Detector 

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #470 
## Description:
Here we will fetch the air quality index using api and extracting it through json and request and then showing the result through tkinter. Here it will also show whether it is good or bad.
Here for the usage of api we need to generate a api key from the website and then we just need to specify the city name for which we need to fetch data in the script and then output will be shown.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly where ever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

output(air)

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Small changes :

Add appropriate comments in code wherever needed.
In README.md file, add aim, purpose, workflow and compilation steps.

@neelshah2409

**Comment by neelshah2409** [comment]
@prathimacode-hub Please review my PR I had done the changes.

**Review by prathimacode-hub — APPROVED** [review]
That's a good script choosen. You stay in Ahmedabad? Good to see your consistency. I want to see you increase your issue levels. All the best. 👏🎊@neelshah2409

**Comment by neelshah2409** [comment]
> That's a good script choosen. You stay in Ahmedabad? Good to see your consistency. I want to see you increase your issue levels. All the best. 👏🎊@neelshah2409

Yes mam Ahmedabad and would surely increase the level.

**Comment by prathimacode-hub** [comment]
> > That's a good script choosen. You stay in Ahmedabad? Good to see your consistency. I want to see you increase your issue levels. All the best. 👏🎊@neelshah2409
> 
> Yes mam Ahmedabad and would surely increase the level.

Good to know. 👍

**Pull request merged**
