### PR TITLE
Add Scrabble 

### PR DESCRIPTION
**Pull request by NancyNegi23**
## Related Issue 

- Add a new script under BasicPythonScripts

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #568 

### Description
This is a basic Python project made using if-else structure and some other in-built functions of Python. It is a simpler version of Scrabble game.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
I have tested the code by checking it through multiple cases.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Output
Outputimage

### CODE REVIEW

**Review by Debashish-hub — CHANGES_REQUESTED** [review]
Replace the githubusercontent link with the path of image i.e. 'Images/imageName.png' in the readme
Rename images to Images folder.
DO follow the PR template while raising a PR
@NancyNegi23

**Comment by NancyNegi23** [comment]
I'll change the PR format. But the link of the image will work once you merge this request.

**Comment by Debashish-hub** [comment]
> I'll change the PR format. But the link of the image will work once you merge this request.

You need to change the link with file path of image

**Comment by NancyNegi23** [comment]
okay

**Comment by NancyNegi23** [comment]
@Debashish-hub I've made the changes

**Review by prathimacode-hub — APPROVED** [review]
Welcome to the repo officially. Congrats, your PR is approved. Good start and selection of project. Well done. Yayy. ✨👏🎉@NancyNegi23

**Pull request merged**
