### PR TITLE
Added Virtual keyboard in GUIScripts

### PR DESCRIPTION
**Pull request by akash435**
## Related Issue 

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

fixes : #460
Closes: #460

### Describe the changes you've made
- A Virtual Keyboard is an application created in python with tkinter gui.
- In this application user can enter any text or sentence or paragraph using the virtual keyboard that is embedded under keyboard button.
- This virtual keyboard can print any character (lower or uppercase), any special characters, digits.
- It also supports typing emoji's also.
- Also there are clear, backspace, space, tab keys also in this virtual keyboard.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

yes , below i have provided the a screenshots and video link for showing how it works. and video of its working also.

## Checklist:

- [x] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |

## Below is the video link showing how application works :
https://user-images.githubusercontent.com/57003737/123205508-acf92b80-d4d7-11eb-8b60-f3cb6cda222e.mp4

### CODE REVIEW

**Review by Debashish-hub — CHANGES_REQUESTED** [review]
Just use the path of the video instead of the usercontent link in the readme @akash435

**Comment by akash435** [comment]
@Debashish-hub , can you please guide me how to add video using path in readme?
I don't know how to do that.

**Comment by Debashish-hub** [comment]
> @Debashish-hub , can you please guide me how to add video using path in readme?
> I don't know how to do that.

If you can convert your video to gif file, then it will be similar to images. Just convert your video to gif online.

**Comment by akash435** [comment]
ok got it, thanks.

**Comment by akash435** [comment]
@Debashish-hub , added the gif in readme , please check it.

**Review by Debashish-hub — APPROVED** [review]
Great! Your PR is approved @akash435 Keep it up.

**Pull request merged**
