### PR TITLE
add dynamic bg color feature

### PR DESCRIPTION
**Pull request by rivelez65**
#45  
I have added a new feature to this game which changes the bg color of the work to the previous word's color.

### CODE REVIEW

**Review by prathimacode-hub — APPROVED** [review]
Awesome. Glad to see your enhancement. Sounds perfect. @rivelez65 

Can you as well elaborate the [README](https://github.com/prathimacode-hub/Awesome_Python_Scripts/tree/main/ImageProcessingScripts/Watermark%20Inserter%20GUI/README.md). Do brief about the project, libraries needed, how the program flow works and screenshot of the final output. So that readers can understand it better. Kudos to you. 👍

**Comment by rivelez65** [comment]
Thanks, and Done

**Comment by prathimacode-hub** [comment]
Do notify me when you have pushed the README changes of this [project](https://github.com/prathimacode-hub/Awesome_Python_Scripts/blob/main/ImageProcessingScripts/Watermark%20Inserter%20GUI/README.md). @rivelez65

**Comment by rivelez65** [comment]
I was having a bit of a mixup making the push, i thought I needed to make a new branch. It's all done on a new PR now

**Pull request merged**
