### PR TITLE
Enhanced Covid Cases Bot

### PR DESCRIPTION
**Pull request by DelionA**
### Related Issue

   - Info about the related issue

- [x] Contributor

Closes: #166
### Describe the add-ons or changes you've made

Add module notify2 for work notification in linux
### Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by DelionA** [comment]
> > I'm a beginner. I work under linux.
> > I added linux support.
> 
> What's the project? Have you created an issue and got it assigned? @DelionA

Covid Cases Bot. 
added linux support. do I need to create an issue and assign it, and then provide a solution?
sorry, this is my first experience with github.

**Comment by prathimacode-hub** [comment]
> > > I'm a beginner. I work under linux.
> > > I added linux support.
> > 
> > 
> > What's the project? Have you created an issue and got it assigned? @DelionA
> 
> Covid Cases Bot.
> added linux support. do I need to create an issue and assign it, and then provide a solution?
> sorry, this is my first experience with github.

That's ok. First create an issue and get assigned. Then you have to work on it and create pull request. Before you dot hat, first go throught the README and CONTRIBUTING GUIDELINES of the project. Whether you create an issue or PR or README file, each and every thing you take up has a template provided. Follow th templates given. This is the workflow.  And most important thing, check if the taken script is already present in the repo or not. So that your efforts don't go wasted. @DelionA

**Comment by DelionA** [comment]
> > > > I'm a beginner. I work under linux.
> > > > I added linux support.
> > > 
> > > 
> > > What's the project? Have you created an issue and got it assigned? @DelionA
> > 
> > 
> > Covid Cases Bot.
> > added linux support. do I need to create an issue and assign it, and then provide a solution?
> > sorry, this is my first experience with github.
> 
> That's ok. First create an issue and get assigned. Then you have to work on it and create pull request. Before you dot hat, first go throught the README and CONTRIBUTING GUIDELINES of the project. Whether you create an issue or PR or README file, each and every thing you take up has a template provided. Follow th templates given. This is the workflow. And most important thing, check if the taken script is already present in the repo or not. So that your efforts don't go wasted. As this is an enhancement to the project. First, do the discussion of do's and dont's before creating a PR @DelionA

ok. thanks.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:

Add appropriate comments in your code to get good understanding of the project. 
README_enhanced.md needs brief elaboration. There is a template given to follow. It should have aim, purpose, description, workflow of the project, compilation steps. output screenshots and your name at the end of the file.

Kindly do these needful changes. @DelionA

**Comment by DelionA** [comment]
> Changes to be done:
> 
> Add appropriate comments in your code to get good understanding of the project.
> README_enhanced.md needs brief elaboration. There is a template given to follow. It should have aim, purpose, description, workflow of the project, compilation steps. output screenshots and your name at the end of the file.
> 
> Kindly do these needful changes. @DelionA

@prathimacode-hub 
Changes have been made.
Please check it out.

**Comment by prathimacode-hub** [comment]
> > Changes to be done:
> > Add appropriate comments in your code to get good understanding of the project.
> > README_enhanced.md needs brief elaboration. There is a template given to follow. It should have aim, purpose, description, workflow of the project, compilation steps. output screenshots and your name at the end of the file.
> > Kindly do these needful changes. @DelionA
> 
> @prathimacode-hub
> Changes have been made.
> Please check it out.

Couldn't see any improved chanegs here. Kindly check if it's pushed to the PR. @DelionA

**Review by prathimacode-hub — APPROVED** [review]
Congrats. Your PR is approved. Welcome to the repo officially. Glad to have you here. You had choosen a wonderful script to enhance and contribute. Very well done. Kindly share your mail Id. 🙌👌✨@DelionA

**Pull request merged**
