### PR TITLE
Collison detection

### PR DESCRIPTION
**Pull request by GVictorsd**
It's a PR regarding the issue #736 .
Kindly review and merge the pull request.

### CODE REVIEW

**Comment by GVictorsd** [comment]
## Related Issue 

- Info about the related issue 

- [ ] LGM-SOC'21 Participant 
- [x] DevIncept Participant
- [x] Contributor

Closes: #736  

### Describe the changes you've made

I have included the necessary script and it's dependency scripts in the corresponding folder. I have also created the README file, which holds the description of the project and other stuff. The sample output images have also been updated.

## Type of change


- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

All the scripts have been tested locally using regular python 3 install and seem to work fine.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Follow the project structure given. It's not in right template, right project stricture and few files missing. Check on it. Everything is provided in README file of the project. 
@GVictorsd

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Add description of the project in "README.md" file. @GVictorsd

**Review by prathimacode-hub — APPROVED** [review]
Welcome to repo officially. Congrats on your first PR. it's approved. Amazing work. Keep it up. ✨🎉👏@GVictorsd

**Pull request merged**
