### PR TITLE
Word Transfer

### PR DESCRIPTION
**Pull request by kumarjeetray**
## Related Issue 

- Info about the related issue 

- [X] LGM-SOC'21 Participant 
- [X] Contributor

Closes: #434 

### Describe the changes you've made

Give a clear description what modifications you have made

I have made the file

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

I have run and tested the code

## Checklist:

- [X] My code follows the guidelines of this project.
- [X] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly whereever it was hard to understand.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done :

Add appropriate comments wherever needed in your project files to get good understanding of the project.
README.md doesn't follow the template given. It needs more precise elaboration. It only has workflow of the project. Kindly add aim, purpose, description, compilation steps, output screenshot and your name at the end of the file. You would understand when you see the README template
Add the output screenshots and images in "Images" folder and add those image links/file path present in this repo to your README.md file in "Screenshot" section.
Add the libraries imported in your project in "requirements.txt" file.

Kindly do the needful changes. @kumarjeetray

**Review by kumarjeetray — COMMENTED** [review]
Done with the changes

**Comment by kumarjeetray** [comment]
> 
> 
> Changes to be done :
> 
> Add appropriate comments wherever needed in your project files to get good understanding of the project.
> README.md doesn't follow the template given. It needs more precise elaboration. It only has workflow of the project. Kindly add aim, purpose, description, compilation steps, output screenshot and your name at the end of the file. You would understand when you see the README template
> Add the output screenshots and images in "Images" folder and add those image links/file path present in this repo to your README.md file in "Screenshot" section.
> Add the libraries imported in your project in "requirements.txt" file.
> 
> Kindly do the needful changes. @kumarjeetray

Done with them. Please do check.

**Review by prathimacode-hub — APPROVED** [review]
Perfect and crystal clear. Welcome to the repo officially. That was a wonderful work and good choice of the script. Keep blazing high. Well done. Yayy. Your PR is approved. ✨👏🎉@kumarjeetray

**Comment by kumarjeetray** [comment]
> 
> 
> Perfect and crystal clear. Welcome to the repo officially. That was a wonderful work and good choice of the script. Keep blazing high. Well done. Yayy. Your PR is approved. ✨👏🎉@kumarjeetray

Thanks a lot

**Pull request merged**
