### PR TITLE
Snake_game

### PR DESCRIPTION
**Pull request by muskantayal123**
Related Issue
Info about the related issue
 LGM-SOC'21 Participant

 Contributor

Closes: #77 

Describe the changes you've made
My project works on Snake game.
I have used the turtle , random and time library.

Type of change
What sort of change have you made:
 Bug fix (non-breaking change which fixes an issue)
 New feature (non-breaking change which adds functionality) 

How Has This Been Tested?
 I have tested my code on my laptop.

Describe how have you verified the changes made.

Checklist:
 My code follows the guidelines of this project.
 I have performed a self-review of my own code.
 I have commented my code, particularly whereever it was hard to understand.
 I have made corresponding changes to the documentation.
 I have added tests that prove my fix is effective or that my feature works.
 Any dependent changes have been merged and published in downstream modules.

ScreenShots
image_2021-06-14_160532

@prathimacode-hub Please review it mam.

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Kindly raise a PR again. You tried to do changes in main repository and .github, due to which conflicts had arised. Almost 41 files. @muskantayal123

**Comment by muskantayal123** [comment]
@prathimacode-hub  mam i am confused. What i have to do exactly mam?

**Comment by prathimacode-hub** [comment]
Kindly add your project files in the project repo u had created in the "folder" that fits the clause. Do don't external changes.

@muskantayal123

**Comment by prathimacode-hub** [comment]
You should not change up your things in the template. You should follow the template to create your own files. @muskantayal123

**Comment by muskantayal123** [comment]
@prathimacode-hub  so basically i have to create a different folder for all my files in the clonned repo. And i have to repeat all the cmd steps again?

**Comment by prathimacode-hub** [comment]
Do you need help? @muskantayal123

**Comment by muskantayal123** [comment]
@prathimacode-hub mam just tell me one thing when i use git add then i have to write dot(.) or the folder name like git add folder name.

**Comment by muskantayal123** [comment]
@prathimacode-hub yes ma'am i need help.

**Comment by prathimacode-hub** [comment]
> @prathimacode-hub yes ma'am i need help.

Join this link:
https://github.com/prathimacode-hub/Awesome_Python_Scripts/discussions/209

**Comment by muskantayal123** [comment]
@prathimacode-hub  joined mam

**Comment by prathimacode-hub** [comment]
> @prathimacode-hub joined mam

Check it now. Hope this would help you clear out your confusion.@muskantayal123

**Comment by muskantayal123** [comment]
@prathimacode-hub mam changes has been done in this pull request So what should i do now? Is there any Problem?

**Comment by prathimacode-hub** [comment]
You had done the changes, but old things still reflecting. So I had closed the PR. Create it again using the steps given? @muskantayal123

**Pull request closed without merging**
