### PR TITLE
Crack Any Password

### PR DESCRIPTION
**Pull request by AmitGupta700**
- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #372 

### Describe the changes you've made
- My project works on Crack Any Password.
- To create a python script which is cracks any password, we will need to import a random module.
- It works on the concept of brute force,
- So, the process is something like that we will ask the user to enter some characters i.e. password, and then we will try to 
    guess the password using a brute force attack.
## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
I have tested my code on Local Machine.

Describe how have you verified the changes made

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots
output

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Add aim, purpose and compilation steps in README.md file of the projects.

Kindly do this change. @AmitGupta700

**Comment by AmitGupta700** [comment]
> Add aim, purpose and compilation steps in README.md file of the projects.
> 
> Kindly do this change. @AmitGupta700

Ma'am Done.

**Review by prathimacode-hub — APPROVED** [review]
Yayy. You're going strong. Good choice of the script. Keep it up. Your dedication is appreciated. ✔🎇@AmitGupta700

**Comment by AmitGupta700** [comment]
> Yayy. You're going strong. Good choice of the script. Keep it up. Your dedication is appreciated. ✔🎇@AmitGupta700

Thank You, Ma'am.

**Pull request merged**
