### PR TITLE
Creating Address Book

### PR DESCRIPTION
**Pull request by Aditya8821**
## Related Issue 

I have created a python script that creates an interface for address book using Python Tkinter. this script has many functions inside it like adding, deleting, displaying, etc. address and phone number of persons.

- [x] LGM-SOC'21 Participant 
- [x] Contributor

Closes: #384 

### Describe the changes you've made

I have created a python script that creates an interface for address book using python Tkinter, this script has many functions inside it like adding, deleting, displaying, etc. address and phone number of persons. Tkinter is a standard library in Python which is used for GUI application. Tkinter has various controls which are used to build a GUI-based application. It comes with many functions which are very useful to create an entry box, buttons, checkboxes, and many more.

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

I have tested this script on my local machine.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots
Demo Output

### CODE REVIEW

**Comment by Debashish-hub** [comment]
Add the image source as 'Images/imageName.png' in the readme @Aditya8821

**Comment by Aditya8821** [comment]
Sir, i have already given image source as https://github.com/Aditya8821/Awesome_Python_Scripts/blob/main/GUIScripts/Address%20Book/Images/Demo%20Output.png
in the readme

**Comment by Debashish-hub** [comment]
> Sir, i have already given image source as https://github.com/Aditya8821/Awesome_Python_Scripts/blob/main/GUIScripts/Address%20Book/Images/Demo%20Output.png
> in the readme

Don't use that github link, use the source from your Images folder

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
In README.md file you had mentioned that this script checks for plagiarism, I guess it's by mistake. Kindly change that. @Aditya8821

**Comment by Aditya8821** [comment]
Done mam!🙌

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved. Your dedication is awesome to this repo. 👌😎🎇@Aditya8821

**Pull request merged**
