### PR TITLE
Caesar Encryption

### PR DESCRIPTION
**Pull request by neelshah2409**
Info about the related issue: Here we encrypt the given sentence or word using the caesar -cipher encryption.
 

-> LGM-SOC'21 Participant
     Contributor

Closes: #98 

Describe the changes you've made
In this we will take a string from the user in   the script and then shift the alphabets as per the requirement.
Type of change
What sort of change have you made:

    
  ->New feature (non-breaking change which adds functionality)
     Bug fix (non-breaking change which fixes an issue)
    Code style update (formatting, local variables)
    Breaking change (fix or feature that would cause existing functionality to not work as expected)
    This change requires a documentation update

Describe how have you verified the changes made

Checklist:
-> My code follows the guidelines of this project.
 ->I have performed a self-review of my own code.
 ->I have commented my code, particularly where ever it was hard to understand.
 ->I have made corresponding changes to the documentation.
-> My changes generate no new warnings.
 I have added tests that prove my fix is effective or that my feature works.
 Any dependent changes have been merged and published in downstream modules.
Screenshots
input(caesar)
output(caesar)

### CODE REVIEW

**Review by prathimacode-hub — COMMENTED** [review]
Hey @neelshah2409. Can you explain this output?

**Comment by neelshah2409** [comment]
Mam here the input string is decrypted and that string was hello world .Here we had shifted the alphabets by 3.

**Comment by prathimacode-hub** [comment]
> Mam here the input string is decrypted and that string was hello world .Here we had shifted the alphabets by 3.

What was the final output when it's shifted?

**Comment by neelshah2409** [comment]
Mam we had given "ebiil tloia" as input in the code itself and stored in the string and after shifting the letters by 3 we got the encrypted value as hello world.

**Review by prathimacode-hub — APPROVED** [review]
Perfect. Your PR is merged successfully. Congrats for your 2nd contribution. 🎇 @neelshah2409

**Pull request merged**
