### PR TITLE
i have moved all folders to mentioned branches

### PR DESCRIPTION
**Pull request by KevinKurian7**
I have added launch map in the automation branch
and the Instagrambot to the webscraping branch

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
For launch maps, repository has wrong typo.
It should be LaunchMaps/Launch_Maps.py

Also you had included both the projects in same PR. But that's  ok I will merge it for now. Do the above change and it will be done. Instagram Bot is perfect.

**Comment by prathimacode-hub** [comment]
I said to change the folder name. 

LaunchMaps -This is the folder name
Launch_Maps.py - This is the file name

Correct this. Both should look like this @KevinKurian7 

Always read comments properly. Else it will strain you only.

**Comment by KevinKurian7** [comment]
i have made the changes mam.

**Review by prathimacode-hub — APPROVED** [review]
Whooaa. Your dedication is awesome. Welcome to this repository by being anofficial contributor. 🎉🎉
Do star the repository, if it helped you in open sourcing or got you green squares.

Thanks for opening up this pull request! 🤗

Are you looking for more beginner-friendly issues? Check out this [repo](https://github.com/prathimacode-hub/HelloWorld/).

Any more queries to talk or discuss, don't hesitate to connect. 👍

Your PR is merged successfully.

**Comment by KevinKurian7** [comment]
THANK YOU

**Comment by prathimacode-hub** [comment]
Sure. You had done an exceptional work. ✨@KevinKurian7

**Pull request merged**
