### PR TITLE
Star Pattern

### PR DESCRIPTION
**Pull request by Ashu-1309**
## Related Issue 

-Star Pattern

- [x] LGM-SOC'21 Participant 
- [x] Contributor

Closes: #567

### Describe the changes you've made

This is used to draw star

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested?

I tested the code in Online python compiler as well as in offline compiler.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly where ever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Ashu-1309** [comment]
I have uploaded the code , images and video .  Tomorrow I will upload the remaining documents

**Comment by Ashu-1309** [comment]
All the required changes are done .Can you please cross check .

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:

The project folder shoudl be titled as "Star Pattern"
The requirements file should be as "requirements.txt" file
Add appropriate comments in your code to get good understanding of the project
The images and videos should be in "Media" folder as this is not purely images.
In README.md file, be elaborative. Add briefly about aim, purpose and compilation steps in the file.

Kindly do these needful changes. @Ashu-1309

**Comment by Ashu-1309** [comment]
All the changes are made . Now you can verify it .

**Review by prathimacode-hub — APPROVED** [review]
Good to see your progress. PR approved. Expecting higher level issues from you.👏🙌@Ashu-1309

**Pull request merged**
