### PR TITLE
QR Code Scanner Web Application 

### PR DESCRIPTION
**Pull request by Iamtripathisatyam**
- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #[issue number that will be closed through this PR]

### Describe the changes you've made
This Python script uses the **Pillow** module to scan a QR code, decode it with **pyzbar**, and display the web result using **pywebio**.

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
I have tested this code in my local machine.

Describe how have you verified the changes made

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented on my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots
hey

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done

- Add all the libraries imported in "requirements.txt" file
- Elaborate the README file.
- The images and screenshots should be in "Images" folder.
- The image link you added in README file of the project is user-images. Add the image link that's added up in the epository.

Kindly do the needful changes. @Iamtripathisatyam

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:

Elaborate the README file. Add steps to compile and aim of the project.
The image link you added in README file of the project is user-images. Add the image link that's added up in this repository.

Kindly do the needful changes. @Iamtripathisatyam

**Comment by Iamtripathisatyam** [comment]
Ma'am, please explain the second point i.e. Image point, I am not getting that

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved. Congo. Keep up your amazing work. 👏 @Iamtripathisatyam

**Pull request merged**
