### PR TITLE
Added the splash screen and logo to the title bar in Calculator App under GUI Scripts

### PR DESCRIPTION
**Pull request by Khushi-sharma07**
- Info about the related issue

- [x] LGM-SOC'21 Participant
- [ ] Contributor

Fixes: #357 
Issue Number: #357 
Closes: #357 

Describe the changes you've made
Added a splash screen to Calculator App in GUI Scripts.
The splash screen will appear for 5 sec before the application opens.
Added the logo to the title bar.
I had also resized the screen and buttons for better presentation.
Added two files Splash Screen_Calculator App.gif and Logo_Calculator App.gif as they were required in the code.

Type of change
What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x]  New feature (non-breaking change which adds functionality)
- [x]  Code style update (formatting, local variables)
- [ ]  Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ]  This change requires a documentation update

Checklist:
 My code follows the guidelines of this project.
 
- [x] I have performed a self-review of my own code.
- [x]  I have commented my code, particularly where ever it was hard to understand.
- [ ]  I have made corresponding changes to the documentation.
- [x]  My changes generate no new warnings.
- [ ]  I have added tests that prove my fix is effective or that my feature works.
- [ ]  Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:

Add ".gif" files in "Media" folder
Add README_enhanced.md file for the changes you had done to the project. 

Kindly do the needful changes. @Khushi-sharma07

**Comment by Khushi-sharma07** [comment]
Okay mam

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Add 'README_enhanced.md' file for the changes you had done. @Khushi-sharma07

**Comment by Khushi-sharma07** [comment]
Mam can you please recheck now, there was some problem in adding it from my side

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Change the title of README file to "README_enhanced.md"

And this will be done. @Khushi-sharma07

**Review by prathimacode-hub — APPROVED** [review]
Yayy, Your PR is approved. Fab work and good initiation to enhance the existing script. Wonderfully executed. Keep rising. Kudos to you. @Khushi-sharma07

**Pull request merged**
