### PR TITLE
Crypto price checker

### PR DESCRIPTION
**Pull request by vkb20**
## Related Issue 

- Using python script to fetch the top 100 cryptocurrencies from https://www.cointracker.io/ and then displaying cryptocurrency name and price.

- [x] Hacktoberfest2021 Participant 
- [x] Contributor

Closes: #957

### Describe the changes you've made

I did all the tasks from scratch. Created the crypto_price_checker.py file for script. Created README.md file for explaining the project. Added relevant screenshots and added requirement.txt file.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

I ran the script in the command prompt

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots
crypto_output_1

crypto_output_2

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Add PR template and details of your issue. And don't include 2 issues in 1 PR. It will count as only 1PR then. Create 2 PR's separately one after the other. Change the title to first PR. Remove 2nd PR files and push the changes back. Yes. @vkb20

**Comment by vkb20** [comment]
Is it correct now?

**Comment by vkb20** [comment]
Is it correct now? @prathimacode-hub

**Comment by vkb20** [comment]
I did one pull request and now to do the second what am I supposed to do?

**Comment by vkb20** [comment]
If I make changes to the repository it will be reflected to this pull request only. That's why I am a bit confused here.

**Comment by vkb20** [comment]
Two seperate pull requests done. @prathimacode-hub

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Keep it up. ✨🎉@vkb20

**Pull request merged**
