### PR TITLE
Add New GUI Script (QR Code Generator)

### PR DESCRIPTION
**Pull request by vivekthedev**
## Related Issue 

- Info about the related issue 

- [ ] Hacktoberfest2021 Participant 
- [x] Contributor

Closes: #1081 number that will be closed through this PR

### Describe the changes you've made

Added a new python GUI Script that generates and download a QR code after taking user's input.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

The code is properly tested. 

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshot

 Original           | Description
 :--------------------: |:--------------------:
  | GUI Window |
 | Sample Output

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Kindly follow the guidelines given. First create an issue using issue template and include the issue number in your PR.

Changes to be done :

Screenshot you shared is of entering the text input but not generated output screenshot
And all images should be in "Images" folder in your project repository
The project filename should be in snake_case letters
We have a README template to follow and it needs more detailing
Add appropriate comments in you code to get good understanding of the project

Kindly do the needful changes. @vivekthedev

**Comment by vivekthedev** [comment]
@prathimacode-hub Thanks for the review. I have made the needful change to the pull.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
README needs some more detailing. You can follow this [template](https://github.com/prathimacode-hub/Awesome_Python_Scripts/blob/main/.github/readme_template.md) as reference. Other than that, all perfect. 👍

**Comment by vivekthedev** [comment]
@prathimacode-hub Thank you for providing the template, I have added necessary sections in the README

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Congrats and welcome to repo. Good initiation. Keep contributing. 👏🎉@vivekthedev

**Pull request merged**
