### PR TITLE
Object Detector

### PR DESCRIPTION
**Pull request by BMaster123**
## Related Issue 

- Info about the related issue 

- [ ] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [x] Contributor

Closes: #913

### Describe the changes you've made

I made a program that detects an object in a picture and draws a green rectangle around the detected object

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

I tested the program myself

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Kindlty follow the project structure and there are many other things as well that needs to be added. README also has a template given. @BMaster123

**Comment by BMaster123** [comment]
Do I need to update the documentation for a new feature and if so where is the documentation I need to update?

**Comment by prathimacode-hub** [comment]
> Do I need to update the documentation for a new feature and if so where is the documentation I need to update?

I didn't get you. Fllow the project structure given. It's already in README file of the project. You will know the following files that you need to add along with the README template provided in Template to Follow section. @BMaster123

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Checked your PR. Your README.md needs more details. It lacks information. Kindly Elaborate it briefly. @BMaster123

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved. Yay. Congrats on your first PR. Welcome to the repo officially. This was a n amazing start. Keep rising high. 🎉👏✨@BMaster123

**Comment by prathimacode-hub** [comment]
Kindly share your full name and your mail address. @BMaster123

**Comment by BMaster123** [comment]
My name is Bhavesh Mandalapu and my email is bhaveshmandalapu@hotmail.com. May I ask why you need this information?

**Comment by prathimacode-hub** [comment]
> My name is Bhavesh Mandalapu and my email is [bhaveshmandalapu@hotmail.com](mailto:bhaveshmandalapu@hotmail.com). May I ask why you need this information?

You will know it soon. Thanks for sharing. 😎

**Pull request merged**
