### PR TITLE
Added Battery Notification Script

### PR DESCRIPTION
**Pull request by pankaj892**
Signed-off-by: Pankaj Biradar <pankaj28988@gmail.com>

This Script solves #30 it asks the user for a threshold and if there is a change in threshold it notifies the user

### CODE REVIEW

**Review by prathimacode-hub — APPROVED** [review]
Congrats on merging your first pull request in this repository. It's a well needed script used for daily use. Keep up the great work. You commitment is amazing. 👏@pankaj892

**Comment by pankaj892** [comment]
Thanks for your feedback @prathimacode-hub

**Comment by prathimacode-hub** [comment]
You're welcome. Hope it helped you in rising up better. Do ✨ this repository if it helped you in getting a green square. @pankaj892

**Comment by pankaj892** [comment]
@prathimacode-hub Yeah sure I'll 🌟this repo

**Pull request merged**
