### PR TITLE
spirograph using turtle

### PR DESCRIPTION
**Pull request by shreyamalogi**
## The Spirograph

to generate a spirograph is a very interesting geometrical figure which is often symmetrical to both the axes

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #116

### Describe the changes you've made

- README should be brief and elaborative. Look through the template I had given for README in README file of the project

- In program file, added appropriate comments whenever necessary
- In program line,checked 1st line and nothing was missing
- In requirements.txt, added the dependencies and libraries.
-  Updated README  what it does, the workflow, steps to compile, output screenshot and conclusion.
- added Images in this project should be in "Images" folder.
- Also in PR commit message, added the template given in README file of the project.
- Added the issue number and link to PR (Ex : #IssueNumber)

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

I have executed the python script on my local computer and it executes successfully.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly where ever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

spirograph

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
This is not right. You haven't got your issue assigned. You haven't followed the template. Kindly ready the README and CONTRIBUTING GUIDELINES before creating issue and PR. There are some steps to be the followed. First get issue assigned to you, using the template given. I had already asked you to elaborate things and make it clear. After issue is assigned to you, that's when you have to work or raise a PR. @shreyamalogi

**Comment by shreyamalogi** [comment]
Oops! So sorry! Thank you for the guidance ❤, I'll look into the guidelines. @prathimacode-hub

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Do these changes 

- README should be brief and elaborative. Look through the template I had given for README in README file of the project
- In program file, add appropriate comments whenever necessary
- In program line, 1st line is missing something. Check it out.
- In requirements.txt, you add the dependencies and libraries.
- README should have the purpose, what it does, the workflow, steps to compile, output screenshot and conclusion. 
- Images you add in this project should be in "Images" folder.
- Also in PR commit message, add the template given in README file of the project. 
- Add the issue number and link to PR (Ex : #IssueNumber)

Kindly do these needful changes. @shreyamalogi

**Comment by shreyamalogi** [comment]
## The Spirograph

to generate a spirograph is a very interesting geometrical figure which is often symmetrical to both the axes

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #116

### Describe the changes you've made

- README should be brief and elaborative. Look through the template I had given for README in README file of the project

- In program file, added appropriate comments whenever necessary
- In program line, checked 1st line and nothing was missing
- In requirements.txt, added the dependencies and libraries.
-  Updated README  what it does, the workflow, steps to compile, output screenshot and conclusion.
- added Images in this project should be in "Images" folder.
- Also in PR commit message, added the template given in README file of the project.
- Added the issue number and link to PR (Ex : #IssueNumber)


## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

I have executed the python script on my local computer and it executes successfully.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly where ever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

spirograph

**Review by prathimacode-hub — COMMENTED** [review]
Do these changes

README should have the workflow and steps to compile for user to understand it easily. Resources are secondary.
Folder name should be "Spirograph"
Images you add in this project should be in "Images" folder.
Also in PR commit message, add the template given in README file of the project.
Add the issue number and link to PR (Ex : #IssueNumber)

Kindly do these needful changes. @shreyamalogi

**Comment by shreyamalogi** [comment]
everything is done ma'am, once please review it.

> Do these changes
> 
> README should have the workflow and steps to compile for user to understand it easily. Resources are secondary.
> Folder name should be "Spirograph"
> Images you add in this project should be in "Images" folder.
> Also in PR commit message, add the template given in README file of the project.
> Add the issue number and link to PR (Ex : #IssueNumber)
> 
> Kindly do these needful changes. @shreyamalogi


Done ma'am!

**Comment by prathimacode-hub** [comment]
Changes to be done

README should have the workflow and steps to compile for user to understand it easily. Resources are secondary.
Folder name should be "Spirograph"
Images you add in this project should be in "Images" folder.

Do these changes. You hadn't done all the changes yet. @shreyamalogi

**Comment by shreyamalogi** [comment]
> Changes to be done
> 
> README should have the workflow and steps to compile for user to understand it easily. Resources are secondary.
> Folder name should be "Spirograph"
> Images you add in this project should be in "Images" folder.
> 
> Do these changes. You hadn't done all the changes yet. @shreyamalogi

yea mam i've checked it, these are already done!!!!

**Comment by prathimacode-hub** [comment]
> > Changes to be done
> > README should have the workflow and steps to compile for user to understand it easily. Resources are secondary.
> > Folder name should be "Spirograph"
> > Images you add in this project should be in "Images" folder.
> > Do these changes. You hadn't done all the changes yet. @shreyamalogi
> 
> yea mam i've checked it, these are already done!!!!

Have you pushed the changes? Because I can't find any changes in my repo. @shreyamalogi

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
You hadn't added the steps of the workflow and compilation process to your README file.
Changes are not reflected here. 
Folder name should be "Spirograph"
To load the images, it should go in "Images" folder

Do these changes. @shreyamalogi

**Comment by shreyamalogi** [comment]
there is nothing to be done with workflow just we have to run it
and the images are there in the images folder only and ive aslo pushed it. aint able to understand why those are not getting refected. https://github.com/shreyamalogi/Awesome_Python_Scripts/tree/main/GUIScripts

**Comment by prathimacode-hub** [comment]
> there is nothing to be done with workflow just we have to run it
> and the images are there in the images folder only and ive aslo pushed it. aint able to understand why those are not getting refected. https://github.com/shreyamalogi/Awesome_Python_Scripts/tree/main/GUIScripts

I had checked it. I had said Folder name should be "Spirograph" and Images folder should be as "Images".
These are case sensitive. You have mentioned them all in small characters. Kindly read the message properly I had pointed earlier. 
Yes, to run it needs compilation steps. Not everyone would understand or refer tutorials. Instead of asking to refer, you can write short intro about it. You should be elaborative. 
There is a README template as well to be followed. It would help you enhance your project right by being descriptive. 
There is nothing wrong in describing. Quality matters. 

@shreyamalogi

**Comment by shreyamalogi** [comment]
> > there is nothing to be done with workflow just we have to run it
> > and the images are there in the images folder only and ive aslo pushed it. aint able to understand why those are not getting refected. https://github.com/shreyamalogi/Awesome_Python_Scripts/tree/main/GUIScripts
> 
> I had checked it. I had said Folder name should be "Spirograph" and Images folder should be as "Images".
> These are case sensitive. You have mentioned them all in small characters. Kindly read the message properly I had pointed earlier.
> Yes, to run it needs compilation steps. Not everyone would understand or refer tutorials. Instead of asking to refer, you can write short intro about it. You should be elaborative.
> There is a README template as well to be followed. It would help you enhance your project right by being descriptive.
> There is nothing wrong in describing. Quality matters.
> 
> @shreyamalogi

oh, understood!. Will do it , thanks again!

**Comment by prathimacode-hub** [comment]
> > > there is nothing to be done with workflow just we have to run it
> > > and the images are there in the images folder only and ive aslo pushed it. aint able to understand why those are not getting refected. https://github.com/shreyamalogi/Awesome_Python_Scripts/tree/main/GUIScripts
> > 
> > 
> > I had checked it. I had said Folder name should be "Spirograph" and Images folder should be as "Images".
> > These are case sensitive. You have mentioned them all in small characters. Kindly read the message properly I had pointed earlier.
> > Yes, to run it needs compilation steps. Not everyone would understand or refer tutorials. Instead of asking to refer, you can write short intro about it. You should be elaborative.
> > There is a README template as well to be followed. It would help you enhance your project right by being descriptive.
> > There is nothing wrong in describing. Quality matters.
> > @shreyamalogi
> 
> oh, understood!. Will do it , thanks again!

You're welcome. Don't get offended. It's just to make you better. @shreyamalogi

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved and merged. Congrats. 👏✨ @shreyamalogi

**Comment by shreyamalogi** [comment]
> Your PR is approved and merged. Congrats. 👏✨ @shreyamalogi

thanks ma'am!❤️

**Pull request merged**
