### PR TITLE
rps.py added in PyGamesScrips [issue43]

### PR DESCRIPTION
**Pull request by MuditCh57**
Fixed issue number #43

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Great to see you contribute again to this repository. Need few changes before I merge. 
1. File name of the script should be as "file_name.py" and Folder name as "Rock Paper Scissors".
2. README should be elaborative for readers to understand. Add a small introduction of what the project is, the workflow of the project, libraries needed, how project can be executed.
3. Screenshot inclusion of the project is must in README file.

Once these things are corrected, I would be happy to merge. ✔ @MuditCh57

**Comment by MuditCh57** [comment]
Thank You mam for your feedback. I will correct my mistake 👍.

**Comment by MuditCh57** [comment]
Hope I've corrected my mistake. If something still wrong please correct me.

**Review by prathimacode-hub — APPROVED** [review]
Congrats on merging your pull request. Amazin work and smart learner. 🎇@MuditCh57

**Pull request merged**
