### PR TITLE
Extracting Information from IP Address (Using API)

### PR DESCRIPTION
**Pull request by its-me-debk007**
## Extracting Information from IP Address (Using API)

- **Info about the related issue** :
    Gives you information related to the IP Address that is entered.

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #266 

### Describe the changes you've made
Created a simple python program that generates information about a particular IP Address with the help of 'ip-api.com' API

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

I have run the program on a variety of online IDEs, and it runs perfectly.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

Output_example1

Output_example2

Output_example3

### CODE REVIEW

**Comment by Debashish-hub** [comment]
Give a short description of your work in the readme, Add the images to the readme and rename it to README.md @its-me-debk007

**Comment by its-me-debk007** [comment]
> Give a short description of your work in the readme, Add the images to the readme and rename it to README.md @its-me-debk007

**All the changes have been made @Debashish-hub Sir!**

**Comment by Debashish-hub** [comment]
Use the image source from your image folder, i.e. Instead of the link of image you are using in readme use 'Images/imageName.jpeg' @its-me-debk007

**Comment by its-me-debk007** [comment]
> Use the image source from your image folder, i.e. Instead of the link of image you are using in readme use 'Images/imageName.jpeg' @its-me-debk007

**Done @Debashish-hub Sir**

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved and merged. Well done. Keep it up. Welcome to the repo officially. Yayy.. ✨👏 @its-me-debk007

**Comment by its-me-debk007** [comment]
> Your PR is approved and merged. Well done. Keep it up. Welcome to the repo officially. Yayy..  @its-me-debk007

**Thanks a lot Ma'am** :smile:

**Pull request merged**
