### PR TITLE
Black Jack Game added

### PR DESCRIPTION
**Pull request by archismansaha**
## Related Issue 
Issue no. #227 
- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #[issue number that will be closed through this PR]

### Describe the changes you've made

Give a clear description what modifications you have made

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
I had tested game by playing 
Describe how have you verified the changes made

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot
black_jack
 |

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Follow the project structure
Changes to be done:

The project file should be titled as "black_jack_game.py"
The readme file should be titled as "README.md"
Add all images and screenshots in "Images" folder.
Elaborate your README.md file
Add the imported libraries in "requirements.txt" file

Kindly do the needful changes. @archismansaha

**Comment by archismansaha** [comment]
ok mam

**Comment by archismansaha** [comment]
mam I made that changes yesterday.Is there any other change I have to make?

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
The images and screenshots should be in "Images" folder
The readme file name should be titled as "README.md"
The project file name should be as "blackjack_game.py"

Kindly do the needful changes. @archismansaha

**Comment by archismansaha** [comment]
@prathimacode-hub  is it now all right?

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved. Congrats. Amazing efforts showcased. Good to see your learning progress. 🎇👌🎉@archismansaha

**Pull request merged**
