### PR TITLE
Image Steganography

### PR DESCRIPTION
**Pull request by skimran2000**
## Related Issue 
- Info about the related issue 
- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #58 

### Describe 

Image Steganography refers to the process of hiding data within an image file. The image selected for this purpose is called the cover-image and the image obtained after steganography is called the stego-image. I have first converted the secret message into 8-bit binary data and then used PIL module of python to extract pixels of image and modify it into 8-bit binary data so that I could store the secret message with it. The value is made odd if 1 occurs and even if 0 occurs.

## Type of change

What sort of change have you made:

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Project folder should be as "Image Stegnography. All screenshots and images should be in 'Images' folder. Kindly do these changes.

**Comment by skimran2000** [comment]
If i put the images in separate Images folder then the path to open the image changes for every desktop. So in order to run the program you need to change the path of the image as it shows in your desktop

**Comment by skimran2000** [comment]
I have done the required changes. You can please look into it.

**Review by prathimacode-hub — COMMENTED** [review]
Looks perfect. Thanks for rectifying the changes. Official labels would come out soon. So you are good to take up a new issue to work on. I shall merge this PR, when official labels are tagged to this PR.

**Comment by skimran2000** [comment]
Okay ma'am, Thankyou.

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved. 🎇@skimran2000

**Pull request merged**
