### PR TITLE
Generate wifi passwords #954

### PR DESCRIPTION
**Pull request by shubhdholakiya**
Issue #954 
Closes : #954 

Thank you for assigning this issue.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done 👍 

- The requirements file should be as "requirements.txt"
- There is a template for README.md available in main page of the project. Refer it and elaborate your README.md. Also add up the project screenshots links in your README file. 
- The project file should be as "file_name.py" format

Kindly do these changes. Thank you. @shubhdholakiya

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Kindly follow this [README](https://github.com/prathimacode-hub/Awesome_Python_Scripts/blob/main/.github/readme_template.md) template given here for README.md file. 

And that's it. It would be ready to merge. Be as elaborative as you could.

@shubhdholakiya

**Review by prathimacode-hub — APPROVED** [review]
Excellent work showcased. Congrats on your PR. Welcome to the repo officially. Yayy. This was a perfect start. ✨🎉👏@shubhdholakiya

**Comment by shubhdholakiya** [comment]
Thank you very much for guiding me and letting me complete perfectly.

**Comment by prathimacode-hub** [comment]
> Thank you very much for guiding me and letting me complete perfectly.

My pleasure, glad to know you as a contributor. You were outstanding and keep enjoying your open source journey. @shubhdholakiya

**Pull request merged**
