### PR TITLE
Piglatin Translator

### PR DESCRIPTION
**Pull request by comnk**
**Description** 

This adds a new feature #939 

Submitting as a Contributor

This project is called Piglatin Translator that takes a string in English and converts it into Pig Latin

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:
The project folder should be as "PigLatin Translator"
README.md needs more elaboration. Kindly check on with the README template so that things would get easier for you. 

Other than this all perfect. Kindly do these changes. @comnk

**Comment by prathimacode-hub** [comment]
Kindly do the changes. @comnk

**Comment by comnk** [comment]
Sorry, have been away on vacation, couldn't bring computer so I am typing on my tablet

Will try to get access to a computer asap

**Comment by prathimacode-hub** [comment]
> Sorry, have been away on vacation, couldn't bring computer so I am typing on my tablet
> 
> Will try to get access to a computer asap

Sure, keep me updated once it's done. 👍

**Comment by comnk** [comment]
can you check my changes on my repo?

**Comment by comnk** [comment]
for this issue?

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Only change it needs, add workflow of the project file as well written in README.md. Then this would be all perfect.

@comnk

**Comment by comnk** [comment]
Ready to check now

**Review by prathimacode-hub — APPROVED** [review]
Yayy. Great work. Congrats on your first PR. Welcome to repo officially. Glad to see you join here. Approved. This was an amazing start and good choice of the script. 🎉✨👏@comnk

**Pull request merged**
