### PR TITLE
Dr Battery

### PR DESCRIPTION
**Pull request by DurgaSai-16**
## Related Issue  (Dr Battery)

- Info about the related issue 

- [ ] LGM-SOC'21 Participant 
- [x] DevIncept Participant
- [ ] Contributor

Closes: #911  `Dr Battery`

### Describe the changes you've made
- Created Dr Battery using following:
    - psutil
    - time
    - pyttsx3
    - win10toast
    - ToastNotifier
    - threading
 - Created necessary conditions for Drain, Over Charging, Full charged conditions.
 - Tested all  of them.
## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested?

- Downloaded and compiled Dr Batter.py 
- left it running in Background
- Notification and voice output obtained during Draining, Over, Full battery condition.
- Posted relevant screenshots in README.md

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by prathimacode-hub — COMMENTED** [review]
PR approved. Whooaa, looks like you had become an expert in PR's . 🙌👏@DurgaSai-16

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Whooaa, looks like you had become an expert in PR's . 🙌👏@DurgaSai-16

**Comment by DurgaSai-16** [comment]
> PR approved. Whooaa, looks like you had become an expert in PR's . 🙌👏@DurgaSai-16

Thank you Ma'm
Credit goes to you🤩🤩

**Comment by prathimacode-hub** [comment]
> > PR approved. Whooaa, looks like you had become an expert in PR's . 🙌👏@DurgaSai-16
> 
> Thank you Ma'm
> Credit goes to you🤩🤩

Glad to know that. 😊

**Pull request merged**
