### PR TITLE
Added Periodic Table Elements Information in GUISripts

### PR DESCRIPTION
**Pull request by akash435**
## Related Issue 

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

fixes : #493 
Closes: #493

### Describe the changes you've made
- A "Periodic Table Elements Information" is an application created in python with tkinter gui.
- In this application, user can find the details about any periodic table elements.
- Here it supports all the 118 elements of the periodic table.
- The details for each mission will be in terms of Name, Symbol, Appearence, Atomic Number, Group Block, Period, Element Category, Atomic Weight, Electronic Configuration, Phase, Melting Point, Boiling Point, Heat of Vaporization, Heat of Fusion, Molar Heat Capacity, Oxidation States, Electronegativity, Ionization Energies, Covalent Radius, Van Der Waal's Radius, Crystal Structure, Thermal Conductivity, Magnetic Ordering.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

yes , below i have provided the a screenshots and video link for showing how it works. and video of its working also.

## Checklist:

- [x] My code follows the guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |

### CODE REVIEW

**Review by Debashish-hub — APPROVED** [review]
Great! Your PR is approved @akash435

**Comment by akash435** [comment]
Thanks

**Review by prathimacode-hub — COMMENTED** [review]
Creative script. Reminds me of chemistry. Great going. ✨🤩@akash435

**Comment by akash435** [comment]
Thanks mam

**Pull request merged**
