### PR TITLE
added age calculator feature

### PR DESCRIPTION
**Pull request by anandalisha**
## Related Issue 

- Implementation of Age Calculator

- [x] LGM-SOC'21 Participant 
- [x] Contributor

Closes: #456 

### Describe the changes you've made

Implemented age calculator using various python modules with GUI python tkinter .

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:
- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots
sample
output

### CODE REVIEW

**Comment by anandalisha** [comment]
@prathimacode-hub please have a look at the feature added.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Follow the project structure, do the changes and add up the files accordingly. @anandalisha

**Comment by anandalisha** [comment]
> Follow the project structure, do the changes and add up the files accordingly. @anandalisha

okay

**Comment by anandalisha** [comment]
> Follow the project structure, do the changes and add up the files accordingly. @anandalisha

@prathimacode-hub added  files according to the project structure

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
The project is still not according to the project structure.

Changes to be done:
In "requirements.txt", add the libraries imported in your project
The file name should be as "age_calculator.py"
The readme file should be as "README.md" 
Add compilations steps in "README.md" file
The images and output screenshots should be in "Images" folder. Create "Images" folder and add appropriate images in that folder.
Add those images links in "README.md" file, not "user-images" content. It should be the file path of the images present in this repo.

Kindly do the needful changes. @anandalisha

**Comment by anandalisha** [comment]
> The project is still not according to the project structure.
> 
> Changes to be done:
> In "requirements.txt", add the libraries imported in your project
> The file name should be as "age_calculator.py"
> The readme file should be as "README.md"
> Add compilations steps in "README.md" file
> The images and output screenshots should be in "Images" folder. Create "Images" folder and add appropriate images in that folder.
> Add those images links in "README.md" file, not "user-images" content. It should be the file path of the images present in this repo.
> 
> Kindly do the needful changes. @anandalisha

@prathimacode-hub made all the changes mentioned above.

**Review by Debashish-hub — APPROVED** [review]

**Comment by anandalisha** [comment]
> Good Job @anandalisha Your PR is approved. Congrats!
Thanks

**Comment by anandalisha** [comment]
> What all these you added @anandalisha

@Debashish-hub  Are you talking about  imgbot?

**Comment by Debashish-hub** [comment]
> > What all these you added @anandalisha
> 
> @Debashish-hub Are you talking about imgbot?

Yes

**Comment by anandalisha** [comment]
> > > What all these you added @anandalisha
> > 
> > 
> > @Debashish-hub Are you talking about imgbot?
> 
> Yes

@Debashish-hub  removed...it was just to optimize the images

**Comment by Debashish-hub** [comment]
> > > > What all these you added @anandalisha
> > > 
> > > 
> > > @Debashish-hub Are you talking about imgbot?
> > 
> > 
> > Yes
> 
> @Debashish-hub removed...it was just to optimize the images

You have made changes to 316 files. Have you deleted or changed some files @anandalisha

**Comment by anandalisha** [comment]
> > > > > What all these you added @anandalisha
> > > > 
> > > > 
> > > > @Debashish-hub Are you talking about imgbot?
> > > 
> > > 
> > > Yes
> > 
> > 
> > @Debashish-hub removed...it was just to optimize the images
> 
> You have made changes to 316 files. Have you deleted or changed some files @anandalisha

yes to remove imgbot I added  images again..nothing much

**Comment by anandalisha** [comment]
@Debashish-hub  reverted my changes. Is it okay now?

**Review by Debashish-hub — APPROVED** [review]
Your PR is approved @anandalisha Congrats!

**Pull request merged**
