### PR TITLE
Wikipedia Summary

### PR DESCRIPTION
**Pull request by pratimakush10**
Title: Wikipedia Summary

LGM-SOC'21 Participant

Closes: #445 

Description : This script is the python program using tkinter GUI in which you need to write the name of the particular topic on which you need the summary and wait for a while then the summary will be there, using wikipedia module.

Type of change
What sort of change have you made:
👍 New feature (non-breaking change which adds functionality)
Bug fix (non-breaking change which fixes an issue)
Code style update (formatting, local variables)
Breaking change (fix or feature that would cause existing functionality to not work as expected)
This change requires a documentation update

Checklist:
👍 My code follows the guidelines of this project.
👍 I have performed a self-review of my own code.
👍 I have commented my code, particularly where ever it was hard to understand.
I have made corresponding changes to the documentation.
👍My changes generate no new warnings.
I have added tests that prove my fix is effective or that my feature works.
Any dependent changes have been merged and published in downstream modules.

Output:
output

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done :

Add libraries imported in "requirements.txt" file
The file name should be as "wikipedia_summary.py"
Add aim, purpose, workflow, compilation steps, output screenshot and output gif and your name at the end of the file. 
Add the link of the .gif present in "Images" folder in "README.md" file, not user-images content. 

Kindly do the needful changes. @pratimakush10

**Comment by pratimakush10** [comment]
@prathimacode-hub 
Mam changes are done please review.

**Review by prathimacode-hub — APPROVED** [review]
Yayy. Your PR is approved. Good initiation. Keep growing. Well done. Congrats. 🏷🎉🙌@pratimakush10

**Comment by pratimakush10** [comment]
Thank you mam

**Pull request merged**
