### PR TITLE
Python based GUI to encrypt and decrypt text

### PR DESCRIPTION
**Pull request by Shivam0705**
[ ] LGM-SOC'21 Participant

☑ DevIncept Participant

 [ ]  Contributor

Closes: #660

In this project, I have developed a GUI app that can encrypt and decrypt text.
This includes implementation of Caesar Cipher algorithm to perform the required operations.
The basic working of this app is that the app consists of a text bar where the user
enters the text. There are two options available, either the user can encrypt the text or can decrypt the text. When the user clicks on any one of the option, the operation is performed and the user is presented with the encrypted / decrypted text.

Checklist:
☑ My code follows the guidelines of this project.
☑ I have performed a self-review of my own code.
☑ I have commented my code, particularly where ever it was hard to understand.
☑ I have made some files for the documentation purpose.
☑ New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:
This project should be under "GUISripts".
And in this, the project folder should be titled as "Text Encryption and Decryption".
pullrequest.md is not needed in the project, remove that file.
readme.md file should be titled as "README.md" and there is a template to follow. Many things missing up.
And all output screenshots and images should be present in "Images" folder. Other than this, output screenshots and images should be added up in README.md file with appropriate titles. Also the image links should be of the file path of the images present in this repo not 'user-images' content.
The project file should be in .py format, it means the project file should be titled as "text_encryption_and_decryption.py"
Also add appropriate comments in code to get good understanding of the project like you did  in .ipynb file.

Kindly do the needful changes. @Shivam0705

**Comment by Shivam0705** [comment]
> Changes to be done:
> This project should be under "GUISripts".
> And in this, the project folder should be titled as "Text Encryption and Decryption".
> pullrequest.md is not needed in the project, remove that file.
> readme.md file should be titled as "README.md" and there is a template to follow. Many things missing up.
> And all output screenshots and images should be present in "Images" folder. Other than this, output screenshots and images should be added up in README.md file with appropriate titles. Also the image links should be of the file path of the images present in this repo not 'user-images' content.
> The project file should be in .py format, it means the project file should be titled as "text_encryption_and_decryption.py"
> Also add appropriate comments in code to get good understanding of the project like you did in .ipynb file.
> 
> Kindly do the needful changes. @Shivam0705

Could you please check once again!!

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Only add up it needs, in README.md, in output section add the project output screenshots as image links but it should be the file path of the images present in this repo but not 'user-images' content. And it would be done. @Shivam0705

**Comment by Shivam0705** [comment]
> Only add up it needs, in README.md, in output section add the project output screenshots as image links but it should be the file path of the images present in this repo but not 'user-images' content. And it would be done. @Shivam0705

Could you please tell me how to add file path of my repository to the image as I am not able to find out what should be written on README.md file so that image should be displayed.

**Comment by Shivam0705** [comment]
> Only add up it needs, in README.md, in output section add the project output screenshots as image links but it should be the file path of the images present in this repo but not 'user-images' content. And it would be done. @Shivam0705

Could you please check it once again?

**Review by prathimacode-hub — APPROVED** [review]
Congrats on your first PR. It's approved. Welcome to repo officially. One of the finest PR I had ever seen. Great start. ✨👏🎉@Shivam0705

**Comment by Shivam0705** [comment]
> Congrats on your first PR. It's approved. Welcome to repo officially. One of the finest PR I had ever seen. Great start. ✨👏🎉@Shivam0705

Thanks a lot for this opportunity!! Much grateful ^_^

**Pull request merged**
