### PR TITLE
Apple Store

### PR DESCRIPTION
**Pull request by kumarjeetray**
## Related Issue 

- Info about the related issue 

- [X] LGM-SOC'21 Participant 
- [X] Contributor

Closes: #574 

### Describe the changes you've made

Give a clear description what modifications you have made

I have made the file

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

I have run and tested the code

## Checklist:

- [X] My code follows the guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly whereever it was hard to understand.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Add aim, purpose and compilation steps in 'README.md'

**Review by kumarjeetray — COMMENTED** [review]
Done with the changes

**Review by prathimacode-hub — APPROVED** [review]
Amazing work showcased. Fab script. Very well executed. Your efforts are highly appreciated. 🤩👏🙌@kumarjeetray

**Comment by kumarjeetray** [comment]
> Amazing work showcased. Fab script. Very well executed. Your efforts are highly appreciated. 🤩👏🙌@kumarjeetray 

Thanks a lot

**Pull request merged**
