### PR TITLE
Hotel Billing System

### PR DESCRIPTION
**Pull request by neelshah2409**
# Billing System For Hotel
## Description:
Here we had made an easier billing system for hotel using tkinter , here we had just kept 4 products and many more can be kept and after giving the quantity of products the final total price will be shown.
- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

Closes: #640 

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots
output(bill)

### CODE REVIEW

**Comment by neelshah2409** [comment]
@prathimacode-hub Please see this PR.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Kindly change the project folder title to "Hotel Billing System"
Also in "README.md" file, add aim, purpose, worfklow of the project and compilation steps. 

Do these changes. @neelshah2409

**Comment by neelshah2409** [comment]
@prathimacode-hub Please see the changes than I can make another PR for unit converter.

**Review by Debashish-hub — APPROVED** [review]
Congrats! @neelshah2409 Your PR is approved.

**Comment by Debashish-hub** [comment]
> @prathimacode-hub Please see the changes than I can make another PR for unit converter.

You can learn to make multiple PR @neelshah2409

**Pull request merged**
