### PR TITLE
HTML to markdown

### LINKED ISSUE #548: HTML to markdown
---
Title: HTML to Markdown
About: CLI script
Name: Tanvi Bugdani
Label: Feature Request
Assignee: ''

---

Define You:

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Description: A script to convert HTML code into markdown format.

### PR DESCRIPTION
**Pull request by tanvi355**
## Related Issue 

Fixes #548 

- [x] LGM-SOC'21 Participant 
- [ ] Contributor

Closes: #[issue number that will be closed through this PR]

### Describe the changes you've made

Added a script to convert HTML file into markdown format.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested?

Made a sample HTML file and tested the script on it. Screenshots are referenced in the REDAME.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by Debashish-hub — CHANGES_REQUESTED** [review]
Keep the images in an 'Images' folder and do changes in readme accordingly @tanvi355

**Comment by tanvi355** [comment]
> Keep the images in an 'Images' folder and do changes in readme accordingly @tanvi355

Can you please tell me how to reference the image from the folder?

**Comment by tanvi355** [comment]
> > > Keep the images in an 'Images' folder and do changes in readme accordingly @tanvi355
> > 
> > 
> > Can you please tell me how to reference the image from the folder?
> 
> You can use 'Images/imageName.png' in place of the link or else you can have a look at other PRs

Got it! Thanks!

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved. Well done. Keep it up. Congrats. Welcome to the repo officially. ✨🎉@tanvi355

**Pull request merged**
