### PR TITLE
Image Ghost Filter

### PR DESCRIPTION
**Pull request by TusharAMD**
## Related Issue 

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

Closes: #956

### Describe the changes you've made

Made a ghost image filter using opencv and added necessary documentations

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
I have ran the script on multiple images and got expected output. I resolved any potential errors that I came across
## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:
Add output screenshot links in README.MD, it should be the path link of image present in this repository.
Also in the project file, add appropriate comments in code to get good understanding of the project.

Kindly do these changes. @TusharAMD

**Comment by TusharAMD** [comment]
Done mam. Sorry I uploaded but forgot to attach

**Comment by prathimacode-hub** [comment]
> Done mam. Sorry I uploaded but forgot to attach

No worries. @TusharAMD

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Keep up your awesome work. Get going. 👏📌@TusharAMD

**Pull request merged**
