### PR TITLE
Change image background

### LINKED ISSUE #968: Change Image background
Define You-

- [x] LGM-SOC'21 Participant
- [x] Contributor

Title:
A project for changing image background 
**Name: Umesh Singh**
Label: Feature Request

### Solution For Issue:
I want to make a project that can help us to change the background of any image using python. I will be adding working instructions for the project in the readme file with some screenshots.

### PR DESCRIPTION
**Pull request by Umesh-01**
### Description
This fixes #968

- [x] LGM-SOC'21 Participant
- [x] Contributor

I have created a project called Change Image Background that can help us to change the background of any image to a different one that you like.

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:
There are few things missing up to be added in README.md. Kindly check it up with the template.
The project file name as said should be as change_image_background.ipynb

Kindly do these changes. @Umesh-01

**Comment by Umesh-01** [comment]
> Changes to be done:
> There are few things missing up to be added in README.md. Kindly check it up with the template.
> The project file name as said should be as change_image_background.ipynb
> 
> Kindly do these changes. @Umesh-01

by mistake, I forgot @prathimacode-hub mam
now check it...

**Comment by prathimacode-hub** [comment]
I couldn't see any changes addressed about README file. Kindly check if you had pushed it properly. @Umesh-01

**Comment by Umesh-01** [comment]
> I couldn't see any changes addressed about README file. Kindly check if you had pushed it properly. @Umesh-01

now check it @prathimacode-hub mam 😅

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:
Add description and workflow of the project in README.md

Other than that all good. Kindly do the changes. @Umesh-01

**Comment by Umesh-01** [comment]
> Changes to be done:
> Add description and workflow of the project in README.md
> 
> Other than that all good. Kindly do the changes. @Umesh-01

done 👍 @prathimacode-hub mam

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Fascinating work. Great going. Keep growing higher. 🙌✔@Umesh-01

**Pull request merged**
