### PR TITLE
Added Snakes and Ladders Game folder

### PR DESCRIPTION
**Pull request by chandu6111**
### Info about related issue
**Title**: Text-based Snakes and Ladders game in python which can be played by 2 players
**Name**: Chandana (chandu6111)
**Label**: Feature Request
Closes: #156 

- [x] LGM-SOC'21 Participant 

### Changes I've made
- Added a folder **Snakes and Ladders game** under **PyGamesScripts** folder.
- The folder contains the **snakes_and_ladders.py** file which consists of the code script along with comments on each line.
- It also has a **Readme.MD** file which explains everything about the code.
- It has a folder named **images** which contains output and other images required.
## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 [Screenshot](https://github.com/chandu6111/images/blob/main/output.png) | Updated Screenshot |

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:

- The images and and screenshots should be in "Images" folder. Here it's case sensitive.
- As well add all the important libraries in "requirements.txt" file.

Kindly do the needful changes. @chandu6111

**Comment by chandu6111** [comment]
I have made the requested changes @prathimacode-hub 
please do review them and let me know if anything else has to be added

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
The images folder should be titled as "Images".

Do this change and it will be done. @chandu6111

**Comment by chandu6111** [comment]
> The images folder should be titled as "Images".
> 
> Do this change and it will be done. @chandu6111

I have changed it in the previous commit itself @prathimacode-hub, could you please cross-verify it. In the Snakes and Ladders Game folder, I have renamed the "images" folder to "Images" and then only changed the name in the code part. 
Again as you have requested,so I tried changing the name again from "Images" to "Images" only and tried pushing commits, but it says "nothing to commit".
So, please do cross-verify

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes hasn't been done yet. @chandu6111

**Comment by chandu6111** [comment]
Just added the required changes @prathimacode-hub 
Please do review

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved. Amazing work. Kudos to you. Congrats on your first PR. 🎉👌✨@chandu6111

**Comment by chandu6111** [comment]
Thank you @prathimacode-hub

**Pull request merged**
