### PR TITLE
Avatar Creator

### PR DESCRIPTION
**Pull request by neelshah2409**
# Avatar Creator
## Description
Here we create our own avatar as per our wish we can customize each and every thing.
- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

Closes: #780 

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 
output_1(avatar)
Output_2(avataar)

### CODE REVIEW

**Review by Debashish-hub — APPROVED** [review]
PR is approved! @neelshah2409

**Comment by prathimacode-hub** [comment]
Whooo, agian a blasting choice of the project. Great going. 🤩🤩@neelshah2409

**Comment by neelshah2409** [comment]
> Whooo, agian a blasting choice of the project. Great going. 🤩🤩@neelshah2409

Thank you so much mam🙇‍♂️🙌⭐ ,you had helped me a lot in this small journey for open source.

**Comment by prathimacode-hub** [comment]
> > Whooo, agian a blasting choice of the project. Great going. 🤩🤩@neelshah2409
> 
> Thank you so much mam🙇‍♂️🙌⭐ ,you had helped me a lot in this small journey for open source.

My pleasure indeed. Mention not. Good to see you as a mentor. 😎🙌@neelshah2409

**Pull request merged**
