### PR TITLE
Enhanced snake game

### PR DESCRIPTION
**Pull request by AlexAdvent**
## Related Issue 

- Info about the related issue 

- [ ] LGM-SOC'21 Participant 
- [x] DevIncept Participant
- [ ] Contributor

Closes: #770 

### Describe the changes you've made
Created separate files for each object and also storing the highest score.
 
Give a clear description of what modifications you have made
I have rewritten all code in object-oriented for better readability and create a new file for each class.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how have you verified the changes made
yes

## Checklist:

- [X] My code follows the guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly whereever it was hard to understand.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have added tests that prove my fix is effective or that my feature works.
- [X] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:
Add appropriate comments in your code to get good understanding of the project
Your "README.md" lacks details, be elaborative enough. You had missed up many things
And add output screenshots in "Images" folder and add those image links in "README.md" file but it should be the file path of the images present in this repo and not "user-images" content
And requirements file should be titled as "requirements.txt"
Remove the empty "data.txt" file

Kindly dot hese changes. @AlexAdvent

**Comment by AlexAdvent** [comment]
I have made all the changes needed.
@prathimacode-hub

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved. Congrats on your first PR and welcome to the repo officially. This was a great start. I expect a newer issue coming from you this time. Yayy. Keep it up. ✨👏🎉@AlexAdvent

**Comment by prathimacode-hub** [comment]
Kindly fill up the PR form given in project channel of Slack. Your response hadn't come yet. Without it, your scores won't be counted. @AlexAdvent

**Comment by AlexAdvent** [comment]
Thanks, mam for reminding me. I have submitted a respone.
@prathimacode-hub

**Pull request merged**
