### PR TITLE
Billing System GUI

### PR DESCRIPTION
**Pull request by Sulagna-Dutta-Roy**
## Related Issue 

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

Closes: #800 

### Describe the changes you've made
I've changed some item names.

Give a clear description what modifications you have made
-added some items
-modified some items
-checked all the errors
-fixes all the typos

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how have you verified the changes made

## Checklist:

- [ ] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [ ] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.

- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |
Bill1
Bill

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Add a PR template provided here in the above comment using edit option along with the issue number you worked on and the project details as shown in the template. That's when I could review your PR. 👍@Sulagna-Dutta-Roy

**Comment by prathimacode-hub** [comment]
And also along with it, follow the proper project structure given. It lacks details. @Sulagna-Dutta-Roy

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:
The README file should be titled as "README.md"
The project file should be titled as "billing_system.py"
Add appropriate comments in code wherever needed to get good understanding of the project.
Add all the libraries imported in the project in "requirements.txt" file
Add all the images and output screenshots of the project in "Images" folder
Elaborate your README.md file. It lacks details and needs more information. Be descriptive.
Also the image links you add in README.md file should be of the file path of the images present in the "Images" folder in this repo but not of 'user-images' content.

Kindly do these needful changes. @Sulagna-Dutta-Roy

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:
You haven't done all the changes mentioned.
You haven't added all the libraries used in "requirements.txt" file
Add appropriate comments in the code to get good understanding of the project.
Elaborate your README.md file
The image link you added in README.md is user-images content instead image link shoudl be the file path of the images present in this repo. 

Kindly do these changes. @Sulagna-Dutta-Roy

**Comment by prathimacode-hub** [comment]
Kindly do the changes asked. @Sulagna-Dutta-Roy

**Comment by Sulagna-Dutta-Roy** [comment]
I updated all the things that mentioned.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes still remaining:
The README.md file should be elaborative and the image link you added is of user-images content instead it should be the file path of the image present in this repo. Describe your project and add the workflow of the project file. It's all like one line answers but not right explanation. 
Add appropriate comments in your code wherever needed to get good understanding of the project. 

@Sulagna-Dutta-Roy

**Review by prathimacode-hub — APPROVED** [review]
Congrats on your first PR and welcome to the repo officially. Amazing work for your first PR. Keep it up. Yayy. Your PR is approved. This was a great start to dive in. ✨👏🎉@Sulagna-Dutta-Roy

**Pull request merged**
