### PR TITLE
ADDED CODE FOR MEMORY_PUZZLE_GAME (ISSUE-231)

### PR DESCRIPTION
**Pull request by HitainKakkar**
## Related Issue 

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [x] Contributor

Closes: #231 
### Describe the add-ons or changes you've made
For this I have prepared 3 python files for the main code/analysis and a few picture for dataset.

### MEMORY_PUZZLE_GAME

- The program runs a memory game that allows you to turn over cards by clicking the mouse.
- Each grey box represents the image of an animal hidden by default.
- If there is a match, the two cards will disappear, leaving a blank white space and giving a message "MATCHED". 
- If not, they will flip back over.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how it has been tested
Describe how have you verified the changes made

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly wherever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added things that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Comment by HitainKakkar** [comment]
Greetings Sir/Mme,
I have made the requested changes.
Kindly check.

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
README.md lacks details. Follow the template and be elaborative in describing your project. @HitainKakkar

**Comment by HitainKakkar** [comment]
ok!!

**Comment by HitainKakkar** [comment]
Is fine now !?

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Add purpose, workflow and compilation steps in README.md file. Workflow means project elaboration. @HitainKakkar

**Comment by HitainKakkar** [comment]
DONE!!

**Review by prathimacode-hub — APPROVED** [review]
Finally, amazing work. PR is approved. Good choice of the script. Welcome to repo officially. Congrats on your first PR in this repo. Yayy. 🤩👍@HitainKakkar

**Comment by HitainKakkar** [comment]
Thank you!!❤

**Pull request merged**
