### PR TITLE
Grammar Correction

### PR DESCRIPTION
**Pull request by neelshah2409**
Title: Grammar Correction

Description: : Here we can easily solve simple grammar mistakes by just running and then writing the sentence as input so the corrected output will be shown.

-> LGM-SOC'21 Participant

     Contributor

Closes: #161 

Describe the changes you've made
Give a clear description what modifications you have made

Type of change
What sort of change have you made:

-> New feature (non-breaking change which adds functionality)
     Bug fix (non-breaking change which fixes an issue)
     Code style update (formatting, local variables)
     Breaking change (fix or feature that would cause existing functionality to not work as expected)
     This change requires a documentation update

Checklist:
-> My code follows the guidelines of this project.
 ->I have performed a self-review of my own code.
 ->I have commented my code, particularly where ever it was hard to understand.
 ->I have made corresponding changes to the documentation.
 ->My changes generate no new warnings.
     I have added tests that prove my fix is effective or that my feature works.
     Any dependent changes have been merged and published in downstream modules.

Screenshots
output_1(grammar)

output_2(grammar)

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:

- The images added in README file are user-images content. Kindly add the images link that shows it's in this repository.

@neelshah2409

**Comment by prathimacode-hub** [comment]
> Changes to be done:
> 
> * The images added in README file are user-images content. Kindly add the images link that shows it's in this repository.
> 
> @neelshah2409

I don't find any changes here. Did u push the code? It still has "user-images" links.

**Comment by neelshah2409** [comment]
Yes, mam done now.

**Review by prathimacode-hub — APPROVED** [review]
Yup, great. Your PR is approved and merged. Congo. Keep rising. 👏@neelshah2409

**Pull request merged**
