### PR TITLE
Invisible Clock using Python #417

### PR DESCRIPTION
**Pull request by Cartikx3**
## Related Issue 

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [ ] DevIncept Participant
- [ ] Contributor

Closes: #417

### Describe the changes you've made

Its a Python script that allows users to get invisible using simple computer vision techniques in OpenCV.

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Yes, the code is tested by several time and the sample output has been provided.

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly whereever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by Debashish-hub — CHANGES_REQUESTED** [review]
Please follow the folder structure and PR template @Cartikx3

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Every project should have README file, project file, requirements file, images and screenshot in images folder. Proper project structure is written in README file of this project. Follow it. @Cartikx3

**Review by Debashish-hub — CHANGES_REQUESTED** [review]
You are not following proper project structure @Cartikx3 
Keep your images in an 'Images' folder
Add a requirements.txt file
Replace the githubusercontent link with the path of image i.e. 'Images/imageName.png'
Add workflow and be more elaborative in readme

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
If you need help you can ask for it, your project files are not in proper project structure. @Cartikx3

**Comment by Cartikx3** [comment]
Mam can you tell me what's wrong with my file structure. now everything is according to Readme . i have made a folder INVISIBLE CLOAK in which there are 4 files :- 
1 MEDIA - which is a folder in which the sample video is 
2 README.md
3. requirements.txt
4. invisiblecloak.py
what the problem ? where i am doing wrong please elaborate mam.

**Comment by prathimacode-hub** [comment]
> Mam can you tell me what's wrong with my file structure. now everything is according to Readme . i have made a folder INVISIBLE CLOAK in which there are 4 files :-
> 1 MEDIA - which is a folder in which the sample video is
> 2 README.md
> 3. requirements.txt
> 4. invisiblecloak.py
> what the problem ? where i am doing wrong please elaborate mam.

You are not following case sensitive structure. Wait I shal guide you with the clear changes. @Cartikx3

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Don't use caps and everything is case sensitive as given.
Changes to be done :

The project folder should be titled as "Invisibility Cloak"
The images and output screenshots, videos should be in "Media" folder
Elaborate your 'README.md' file. It should have aim, purpose, description, workflow of the project, compilation steps, output screenshots and video and your name at the end of the file
The images or video links you add up in the 'README.md' file should be the file path of it present in this repo. Not the user-images content.
The project file should be titled as "invisible_cloak.py"
In "requirements.txt" file, you hadn't added up all the libraries imported.

You would have got these things cleared, if you have followed as mentioned in README and CONTRIBUTING GUIDELINES of the project. Kindly do these needful changes. @Cartikx3

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Good to see your changes. Needs few though.

- Add purpose and compilation steps in your README.md file
- In Media, you ha added .gif file, along with that also add "output screenshot" to this folder. Screenshot is must and include up the link in "README.md" file.
- Also add up a PR template to your PR and do the necessary changes according to the project.
You can check up with how PR template looks like [here](https://github.com/prathimacode-hub/Awesome_Python_Scripts/pull/627), copy ad modify the changes. 

Kindly do these needful changes. Any queries, don't hesitate to ask. @Cartikx3

**Comment by Cartikx3** [comment]
Mam what's the need of "output screenshot" when i already uploaded the sample video in the Readme and media folder.

**Review by prathimacode-hub — APPROVED** [review]
Finally, you got it perfect. Good work. Keep going. Congrats. Welcome to repo officially. Your PR is approved. Yayy. 👌✨👏 @Cartikx3

**Comment by prathimacode-hub** [comment]
> Mam what's the need of "output screenshot" when i already uploaded the sample video in the Readme and media folder.

Screenshot is also must, but I'm letting it go for now. From next time, it's needed. That's basic criteria when you present a project.  @Cartikx3

**Pull request merged**
