### PR TITLE
MOVIE REVIEWS SCRAPING

### PR DESCRIPTION
**Pull request by devkumar24**
## Related Issue 

- Info about the related issue 

- [ ] LGM-SOC'21 Participant 
- [x] DevIncept Participant
- [ ] Contributor

Closes: #791 

### Describe the changes you've made

Give a clear description what modifications you have made
**I have made a script of scraping the movie reviews and stores in a CSV file, and added a code for getting movie names and 
its links in the JSON format.**

## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how have you verified the changes made
**I have counted the list of movies I have fetch from website and cross-check it with website, there are 250 top-rated movies
and 100 most popular movies.**

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |

### CODE REVIEW

**Comment by prathimacode-hub** [comment]
Kindly add the PR template and addup the details according to the template given. Include issue number in your PR template as well, so that I could check on to the PR. @devkumar24

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:
All the images and screenshots should be in "Images" folder and change the links appropriately in "README.md" file
List out all the libraries included in your project in "requirements.txt" file
All the project files should only be in .py format.
Add purpose, short description, compilation steps in the README.md

Kindly do these needful changes. @devkumar24

**Comment by devkumar24** [comment]
I have made changes, please review it.

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved. Congrats on your first PR. Yayy. Welcome to the repo officially. This was a great start. Keep it up. 🎉👏✨@devkumar24

**Pull request merged**
