### PR TITLE
Stone Paper Pencil Rubber & Scissor

### PR DESCRIPTION
**Pull request by kumarjeetray**
## Related Issue 

- Info about the related issue 

- [X] LGM-SOC'21 Participant 
- [X] Contributor

Closes: #450 

### Describe the changes you've made

Give a clear description what modifications you have made

I have made the file

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

I have run and tested the code

## Checklist:

- [X] My code follows the guidelines of this project.
- [X] I have performed a self-review of my own code.
- [X] I have commented my code, particularly whereever it was hard to understand.
- [X] I have made corresponding changes to the documentation.
- [X] My changes generate no new warnings.
- [X] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

### CODE REVIEW

**Review by Debashish-hub — CHANGES_REQUESTED** [review]
Add a requirements.txt file
Rename your folder to "Stone Paper Pencil Rubber & Scissor"
Instead of the image source as the link use image path i.e. "Images/imageName.jpg" as you had done earlier.
Do comment your code wherever necessary
Do these changes @kumarjeetray

**Review by kumarjeetray — COMMENTED** [review]
Done Changes. The code already has comments wherever required

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:
The folder name should be titled as "Stone Paper Pencil Rubber Scissor"
The requirements file should be titled as "requirements.txt". Add libraries imported in this file.
The project file should be titled as "stone_paper_pencil_rubber_Scissor.py"
Add appropriate comments in code wherever needed. 

Kindly do the needful changes. @kumarjeetray

**Comment by kumarjeetray** [comment]
> 
> 
> Changes to be done:
> The folder name should be titled as "Stone Paper Pencil Rubber Scissor"
> The requirements file should be titled as "requirements.txt". Add libraries imported in this file.
> The project file should be titled as "stone_paper_pencil_rubber_Scissor.py"
> Add appropriate comments in code wherever needed.
> 
> Kindly do the needful changes. @kumarjeetray
Please check now

**Review by prathimacode-hub — APPROVED** [review]
Great going. Congo. Your PR is approved. Amazing work. Good to see your progress. Keep growing. ✔👌@kumarjeetray

**Pull request merged**
