### PR TITLE
My Routine Database System

### PR DESCRIPTION
**Pull request by LasyaGanesuni**
**Title**:My Routine Database System
**Description**: This My Routine Database System is a desktop application where we can update our daily routine. The frontend of this project is made up of Tkinter. The backend of the project is developed with MYSQL.

 **LGM-SOC'21** : Participant

**Closes**: #95 

**Describe the changes you've made**
**Give a clear description what modifications you have made**

**Type of change**
**What sort of change have you made:**

New feature (non-breaking change which adds functionality)
Bug fix (non-breaking change which fixes an issue)
Code style update (formatting, local variables)
Breaking change (fix or feature that would cause existing functionality to not work as expected)
This change requires a documentation update

**Checklist:**
-> My code follows the guidelines of this project.
->I have performed a self-review of my own code.
->I have commented my code, particularly where ever it was hard to understand.
->I have made corresponding changes to the documentation.
->My changes generate no new warnings.
I have added tests that prove my fix is effective or that my feature works.
Any dependent changes have been merged and published in downstream modules.

**Screenshot:**

view_all

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes needed:

The project file name should be as "my_routine_database_system.py"
Elaborate the README file. The aim, purpose, use, workflow, compilation steps, output screenshot etc. Be briefer. 
And all add the libraries imported in "requirements.txt" file.

Kindly do the needful changes. @LasyaGanesuni

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Add the aim, workflow of the project and and how to setup MYSQL database in the README file of your project.

Do these changes. @LasyaGanesuni

**Comment by LasyaGanesuni** [comment]
Mam, once check it I have made the mentioned changes.

**Review by prathimacode-hub — APPROVED** [review]
It's done perfectly. Well done. Your PR is approved and merged. Congrats. Welcome to the repo. 🎉🙌@LasyaGanesuni

**Pull request merged**
