### PR TITLE
Py-Browser - Web Browser using Python

### PR DESCRIPTION
**Pull request by abhisheks008**
## Info About the related issue : 
This python script will create a web browser just like other web browsers those we are using in our daily life like, Google Chrome, Mozilla Firefox, Microsoft Edge and many more.

- [x] LGMSOC Participant

Closes : #364 

## Description : 
This python script will create a web browser just like other web browsers those we are using in our daily life like, Google Chrome, Mozilla Firefox, Microsoft Edge and many more.Through this web browser we can do everything, just like other browsers.

## Type of change

What sort of change have you made:

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly where ever it was hard to understand.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.

### CODE REVIEW

**Comment by Debashish-hub** [comment]
No need of Readme inside Images folder
Add a requirements.txt file
Add the link of images of  images folder in the readme i.e. 'Images/imageName.jpg'
@abhisheks008

**Comment by abhisheks008** [comment]
Updates related to the required changes -

- [x] Adding a requirements.txt folder.
- [x] Deleting the README.md file inside the Images folder.
- [x] Updating the image location in the README.md file as Images/Image_name.png.

@Debashish-hub and @prathimacode-hub I have done all the required changes. Please check it now!

Thank you!

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
That was a fab work shown. Keep sparkling. Nailed it. But needs some change. Add the project in "GUIScripts" and project folder should be titled as "PyBrowser". @abhisheks008

**Comment by abhisheks008** [comment]
@prathimacode-hub Updated all the required changes.

- [x] Added the project in the GUIScripts directory
- [x] Renamed the folder's title as "PyBrowser"

Please check it.

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved. Such a drastic improvement in your PR's. Good to see your growth. Wonderful work. 🎇👍@abhisheks008

**Comment by abhisheks008** [comment]
Thank you @prathimacode-hub for providing these amount of opportunities.

Wanted to contribute more!

**Comment by prathimacode-hub** [comment]
> Thank you @prathimacode-hub for providing these amount of opportunities.
> 
> Wanted to contribute more!

Most welcome. Sure, you're always free to contribute. Get going.  @abhisheks008

**Pull request merged**
