### PR TITLE
Add New Project : GUI PDF Utility Tool

### PR DESCRIPTION
**Pull request by vivekthedev**
## Related Issue 

- Info about the related issue 

- [ ] Hacktoberfest2021 Participant 
- [x] Contributor

Closes: [#issue](https://github.com/prathimacode-hub/Awesome_Python_Scripts/issues/1086) number that will be closed through this PR

### Describe the changes you've made

Made a GUI Script that makes it easy to work with PDFs

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 

<br>

 

<br>

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Small Changes :

Replace the file name as pdf_utility.py and add appropriate comments in code to get good understanding of the file.
README can be more detailed too

Kindly do these changes. This is an useful script. Good initiation. @vivekthedev 👍

**Comment by vivekthedev** [comment]
> Small Changes :
> 
> Replace the file name as pdf_utility.py and add appropriate comments in code to get good understanding of the file.
> README can be more detailed too
> 
> Kindly do these changes. This is an useful script. Good initiation. @vivekthedev 👍

Sure

**Comment by vivekthedev** [comment]
I have added comments to describe the code and more points to the README to get a better overview of the script.
@prathimacode-hub

**Review by prathimacode-hub — APPROVED** [review]
PR approved. Good choice of script. Amazing. Great going. Keep contributing.👏🙌@vivekthedev

**Pull request merged**
