### PR TITLE
Covid cases bot

### PR DESCRIPTION
**Pull request by Komal-99**
#166  

- Info about the related issue 

- [x] LGM-SOC'21 Participant 
- [x] Contributor

Closes: #166

### Describe the changes you've made

1.Added Readme.md
2.Added requirements.txt
3.Added Covid-19_cases_notifier.py python script
4. Added Images folder
## Type of change

What sort of change have you made:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Describe how have you verified the changes made

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:

The project folder should be titled as " Covid Cases Bot"
Kindly elaborate the README.md file.

That's it. @Komal-99

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved. Wonderful work. 👌🔖@Komal-99

**Comment by Komal-99** [comment]
> Your PR is approved. Wonderful work. 👌🔖@Komal-99

Thanks 😊 kindly assign #222

**Comment by prathimacode-hub** [comment]
> > Your PR is approved. Wonderful work. 👌🔖@Komal-99
> 
> Thanks 😊 kindly assign #222

The issue you asked for is assigned to you. @Komal-99

**Pull request merged**
