### PR TITLE
Created Music player using pygame and tkinter

### PR DESCRIPTION
**Pull request by coding-geek21**
## Related Issue 

- Created Music player using pygame and tkinter

- [x] LGM-SOC'21 Participant 
- [x] Contributor

Closes: #282 

### Describe the changes you've made

Give a clear description what modifications you have made

## Type of change

What sort of change have you made:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Code style update (formatting, local variables)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested?

Describe how have you verified the changes made

## Checklist:

- [x] My code follows the guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly whereever it was hard to understand.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] Any dependent changes have been merged and published in downstream modules.

## Screenshots

 Original           | Updated
 :--------------------: |:--------------------:
 Original Screenshot | Updated Screenshot |

image

### CODE REVIEW

**Review by prathimacode-hub — CHANGES_REQUESTED** [review]
Changes to be done:

Add aim, purpose and compilation steps in README.md file
Also the image screenshot you included should be the file path of image instead of user-images content
Add appropriate comments in project file to get good understanding of the program
Add all the imported libraries in "requirements.txt" file.
And this "Music Player" project should be in "BasicPythonScripts" 
folder instead of "PyGamesScripts".

Kindly do the needful changes. @coding-geek21

**Comment by coding-geek21** [comment]
> Changes to be done:
> 
> Add aim, purpose and compilation steps in README.md file
> Also the image screenshot you included should be the file path of image instead of user-images content
> Add appropriate comments in project file to get good understanding of the program
> Add all the imported libraries in "requirements.txt" file.
> And this "Music Player" project should be in "BasicPythonScripts" 
> folder instead of "PyGamesScripts".
> 
> Kindly do the needful changes. @coding-geek21 

Sure , I will do it

**Comment by coding-geek21** [comment]
@prathimacode-hub 
I have done the changes , Please review it . Thank You!

**Review by prathimacode-hub — APPROVED** [review]
Your PR is approved and merged. Yayy. Well done. I appreciate your efforts. Keep it up. ✔🎇👌 @coding-geek21

**Comment by coding-geek21** [comment]
> Your PR is approved and merged. Yayy. Well done. I appreciate your efforts. Keep it up. ✔🎇👌 @coding-geek21 

Thanks a lot 🤩

**Pull request merged**
